Add mint module to inflate every begin block
bandprotocol/bandchain pull request #100
Opened 2019-12-24 09:46 UTC by taobun

fixed #12

- Add mint module to inflate every begin block
- Inflated token send to fee collector and will be send to distributor to distribute to validators

2019-12-24 09:48 UTC, taobun commented
After run chain investigate balance of distribution module by this [endpoint](http://localhost:1317/bank/balances/band1jv65s3grqf6v6jl3dp4t6c9t9rk99cd87sy73h)

2019-12-24 10:50 UTC, sorawit requested changes

2019-12-24 10:50 UTC, sorawit commented on chain/docker-config/single-validator/genesis.json
> +  "genesis_time": "2019-12-24T04:31:10.609444Z",
Please generate genesis for multi-val too

2019-12-25 03:36 UTC, sorawit approved these changes

2019-12-25 03:37 UTC, merged