Implement subscribe hook for tx table
bandprotocol/bandchain pull request #1000
Opened 2020-03-26 08:38 UTC by Benzbeeb

Fixed #939

2020-03-26 10:45 UTC, sorawit requested changes

2020-03-26 10:45 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +type t = {
Merge conflict!

2020-03-27 05:49 UTC, taobun requested changes

2020-03-27 05:49 UTC, taobun commented on scan/src/subscriptions/TxSub.re
> +
Can add another hook to get the number of transactions?

2020-03-27 09:30 UTC, taobun approved these changes

2020-03-28 07:04 UTC, sorawit approved these changes

2020-03-28 07:10 UTC, evilpeach approved these changes
LGTM

2020-03-28 07:23 UTC, merged