Implement UI tx index action rows for messages
bandprotocol/bandchain pull request #1004
Opened 2020-03-26 13:02 UTC by tansawit

Fixes: #953

2020-03-26 16:19 UTC, sorawit requested changes

2020-03-26 16:19 UTC, sorawit commented on scan/src/rpc/TxHook.re
> +    AxiosHooks.use({j|txs?tx.height=$height&page=$page&limit=$limit|j});
Please set line length to 100 so your autoformat won't conflict with others. Ask @Benzbeeb how to do that. He did it a few weeks ago.

2020-03-27 07:30 UTC, evilpeach requested changes

2020-03-27 07:30 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> + */
remove?

2020-03-27 08:39 UTC, evilpeach submitted a review, later dismissed

2020-03-27 13:12 UTC, evilpeach approved these changes
LGTM

2020-03-28 07:01 UTC, taobun submitted a review, later dismissed

2020-03-28 07:33 UTC, evilpeach requested changes

2020-03-28 07:33 UTC, evilpeach commented on scan/src/reusable/PubKeyRender.re
> +      spacing={position |> letterSpacing}
add `height={Text.Px(16)}` to make it align.

2020-03-28 12:33 UTC, evilpeach approved these changes

2020-03-28 13:04 UTC, sorawit approved these changes
Looks good. Let's ship it!

2020-03-29 07:53 UTC, merged