borsh encode and test case
bandprotocol/bandchain pull request #1006
Opened 2020-03-26 14:54 UTC by evilpeach

Fixes #933

2020-03-26 15:32 UTC, taobun submitted a review, later dismissed

2020-03-29 06:28 UTC, taobun submitted a review, later dismissed

2020-03-29 06:32 UTC, sorawit requested changes

2020-03-29 06:32 UTC, sorawit commented on scan/src/bindings/Borsh.re
> +let encode: (string, string, array((string, string))) => option(JsBuffer.t) = [%bs.raw
Let's remove `serialize` function up there.

2020-03-29 06:51 UTC, sorawit requested changes

2020-03-29 06:51 UTC, sorawit commented on scan/__tests__/Borsh_test.re
> +  test("should be able to decode from bytes correctly2", () => {
encode?

2020-03-30 07:46 UTC, evilpeach commented on scan/__tests__/Borsh_test.re
> +  test("should be able to decode from bytes correctly2", () => {
My bad, I'll fix it.

2020-03-30 12:50 UTC, sorawit approved these changes

2020-03-30 12:50 UTC, taobun approved these changes

2020-03-30 16:19 UTC, merged