Implement UI all txs action rows for messages
bandprotocol/bandchain pull request #1023
Opened 2020-03-27 05:26 UTC by Benzbeeb

Fixed #952

2020-03-28 07:11 UTC, evilpeach commented
@Benzbeeb Please fix the conflict.

2020-03-30 02:59 UTC, prin-r requested changes
<img width="931" alt="Screen Shot 2563-03-30 at 09 56 48" src="https://user-images.githubusercontent.com/12705423/77871014-1656a400-726d-11ea-8b5c-e8e55776bb04.png">

Some row didn't align. Can we fix this ?

2020-03-31 08:55 UTC, evilpeach commented on scan/src/components/msgs/Msg.re
> -      <div className={Styles.withWidth(width / 2 - 20)}>
Talk with @prin-r. Is it proper to edit this?

2020-03-31 14:23 UTC, evilpeach commented
@Benzbeeb I'm going to take care of this PR.

2020-03-31 16:24 UTC, prin-r approved these changes

2020-03-31 16:25 UTC, evilpeach approved these changes

2020-03-31 16:40 UTC, merged