Implement all requests page UI
bandprotocol/bandchain pull request #1030
Opened 2020-03-27 10:35 UTC by taobun

fixed #856

2020-03-28 07:12 UTC, evilpeach commented
@taobun  Please fix the conflict.

2020-03-28 07:19 UTC, evilpeach requested changes
I cannot click `Request Scripts` tab in Navbar

2020-03-30 05:57 UTC, prin-r requested changes
Please fix a conflict.

2020-03-30 16:33 UTC, evilpeach commented
@taobun Please check, it occurs an error.

2020-03-31 03:01 UTC, prin-r requested changes
Can't see website, found these error
1. "Caml_js_exceptions.Error"
2. "Error: getExn
    at Object.i [as getExn] (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:112:227)
    at W (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:249:1710)
    at Object.e [as _1] (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:6:728)
    at S (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:338:3101)
    at Object.i [as _3] (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:6:1687)
    at P (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:423:4276)
    at Object.e [as _1] (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:6:728)
    at S (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:338:3101)
    at Object.i [as _3] (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:6:1687)
    at U (https://d3n-scan-pr-1030.onrender.com/Index.758dff1c.js:423:5972)"

2020-03-31 04:48 UTC, taobun commented
@prin-r @evilpeach Already fixed

2020-03-31 07:50 UTC, evilpeach requested changes

2020-03-31 07:50 UTC, evilpeach commented on scan/src/reusable/TElement.re
> +        | Unknown => Images.fail
Let's use the question mark image. Download from Flaticon.

2020-04-01 03:32 UTC, prin-r reviewed
Seems ok. So please resolve conflict.

2020-04-01 04:25 UTC, evilpeach approved these changes
LGTM

2020-04-01 04:28 UTC, prin-r approved these changes

2020-04-01 05:13 UTC, merged