scan: oracle script sub wire up
bandprotocol/bandchain pull request #1031
Opened 2020-03-27 12:31 UTC by evilpeach

Fixes #941

2020-03-28 11:42 UTC, sorawit requested changes
The hook file should be removed!

2020-03-30 04:47 UTC, prin-r approved these changes

2020-03-31 03:11 UTC, taobun approved these changes

2020-03-31 09:51 UTC, sorawit approved these changes

2020-03-31 10:02 UTC, merged