scan: client side library
bandprotocol/bandchain pull request #1033
Opened 2020-03-27 15:45 UTC by evilpeach

Fixes #951

2020-03-28 13:08 UTC, taobun submitted a review, later dismissed

2020-03-29 11:05 UTC, sorawit commented
@prin-r Please review through this and make sure you understand what's going on. @evilpeach There's a conflict.

2020-03-30 05:03 UTC, prin-r requested changes
Please fix a conflict first.

2020-03-30 07:35 UTC, prin-r approved these changes

2020-03-30 07:49 UTC, taobun approved these changes

2020-03-30 07:58 UTC, merged