Make tx messages/actions typesafe and wireup front page
bandprotocol/bandchain pull request #1042
Opened 2020-03-28 09:09 UTC by Benzbeeb

Fixed #954

2020-03-29 10:52 UTC, sorawit commented
@Benzbeeb Please fix the conflict. I moved end block logic to its own file here https://github.com/bandprotocol/bandchain/commit/fe1499a2586ff109080f324ead83e0fa9aaf781c. Fixing should be simple but make sure you understand what's going on. Let me know if you have question.

2020-03-29 10:52 UTC, sorawit requested changes
Fix conflict

2020-03-29 10:58 UTC, sorawit requested changes

2020-03-29 10:58 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +    | Request(_) => "yo"
What is this?

2020-03-29 10:58 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +    | AddOracleAddress(_) => "ADDORACLEADDRESS DESCRIPTION"
Also here. Why is it still placeholder?

2020-03-29 10:58 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +    | Send(_) => None
Also here. Shouldn't this ticket wire-up everything?

2020-03-29 10:58 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +module Event = {
Why is it here? Where is this getting used?

2020-03-30 05:51 UTC, taobun requested changes

2020-03-30 05:51 UTC, taobun commented on scan/src/subscriptions/TxSub.re
> +
Why need empty line here?

2020-03-30 09:21 UTC, sorawit approved these changes
LGTM

2020-03-31 03:31 UTC, taobun approved these changes

2020-03-31 03:47 UTC, merged