Implement request index page bottom part ui
bandprotocol/bandchain pull request #1057
Opened 2020-03-28 18:56 UTC by prin-r

Fix #859

2020-03-30 13:25 UTC, evilpeach requested changes
As I go through, I see the Progress Bar works buggy.
For example
![image](https://user-images.githubusercontent.com/14128977/77917227-80e6fe80-72c4-11ea-8f95-a912e043e1be.png)

The requested validators are 3 but the indicator doesn't point at the end of progress bar.

2020-03-30 13:25 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +                 totalValidators
Font Size should be 10px of Pending 3 Validators

2020-03-30 13:25 UTC, evilpeach commented on scan/src/rpc/ProofHook.re
> +  let json =
Let's use the real one.

2020-03-30 13:25 UTC, evilpeach commented on scan/src/components/KVTable.re
> +  | THEME_2;
I think we should name it meaningful.

2020-03-30 13:25 UTC, evilpeach commented on scan/src/components/TypeID.re
> +    | Mini => style([pointerEvents(`auto)]);
It should be 
```
| Text
| Mini => style([pointerEvents(`auto)]);
```

2020-03-31 03:46 UTC, sorawit submitted a review, later dismissed

2020-03-31 03:46 UTC, sorawit commented on scan/src/components/KVTable.re
> +let withSetting = (arr, sizes, isRights) =>
Make it more flexible.

2020-03-31 06:39 UTC, taobun requested changes

2020-03-31 06:39 UTC, taobun commented on scan/src/pages/RequestIndexPage.re
> +                   value="EXPIRATION DATA"
External Data

2020-03-31 06:39 UTC, taobun commented on scan/src/pages/RequestIndexPage.re
> +                 <CopyButton data={"aaaa" |> JsBuffer.fromHex} />
Remove this button.

2020-03-31 06:39 UTC, taobun commented on scan/src/components/KVTable.re
> +let make =
Can you switch theme for header table font size

2020-03-31 15:42 UTC, evilpeach requested changes

2020-03-31 15:42 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +  let minWidth = mw => style([minWidth(`px(mw)), maxWidth(`px(mw))]);
Why don't we set width instead?

2020-03-31 15:42 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +  let centerHFlex = style([display(`flex), alignItems(`center), justifyContent(`center)]);
Let's make `let center = style([justifyContent(center)])` and then use `Css.merge` to combine `hFlex` and `center` together.

2020-04-01 03:16 UTC, evilpeach commented on scan/src/components/KVTable.re
> +        code=true
remove the code props

2020-04-01 08:16 UTC, evilpeach approved these changes
LGTM

2020-04-01 09:11 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +let get: 'a => option(Request.t) =
This file will be removed, so it's ok to land with this

2020-04-01 09:13 UTC, taobun approved these changes

2020-04-01 09:13 UTC, merged