chain: Perform raw report duplication check in ValidateBasic
bandprotocol/bandchain pull request #1059
Opened 2020-03-29 08:33 UTC by sorawit

The check can be performed without needing access to state, so let's check in ValidateBasic. I also don't think the requirement for increasing order matters much here. While it does help with performance, it's extremely minimal and non-significant.

2020-03-30 03:42 UTC, Benzbeeb requested changes

2020-03-30 03:42 UTC, Benzbeeb commented on chain/x/zoracle/internal/types/msgs.go
> +	}
Can we check unique by use map? I think that way is easy to read and better in time complexity

2020-03-30 14:20 UTC, taobun approved these changes

2020-04-01 02:40 UTC, Benzbeeb approved these changes

2020-04-01 03:16 UTC, merged