chain: Convert parameters to uin64 and introduce one function to read…
bandprotocol/bandchain pull request #1061
Opened 2020-03-29 14:35 UTC by sorawit

… any parameter

2020-03-29 14:42 UTC, Benzbeeb submitted a review, later dismissed

2020-03-30 04:47 UTC, taobun requested changes

2020-03-30 04:47 UTC, taobun commented on chain/x/zoracle/internal/keeper/result.go
> +			len(result), int(k.GetParam(ctx, types.KeyMaxResultSize)),
In fmt we need to cast uint64 to int ?

2020-03-30 04:47 UTC, taobun commented on chain/x/zoracle/internal/keeper/request.go
> +			len(calldata), int(k.GetParam(ctx, types.KeyMaxCalldataSize)),
ditto

2020-03-30 12:03 UTC, sorawit commented on chain/x/zoracle/internal/keeper/result.go
> +			len(result), int(k.GetParam(ctx, types.KeyMaxResultSize)),
Good catch

2020-03-30 12:08 UTC, taobun approved these changes

2020-03-30 12:09 UTC, Benzbeeb approved these changes

2020-03-30 12:37 UTC, merged