Add table that stores oracle script code information
bandprotocol/bandchain pull request #1067
Opened 2020-03-30 10:26 UTC by Benzbeeb

Fixed #1036

2020-03-30 11:14 UTC, sorawit requested changes

2020-03-30 11:14 UTC, sorawit commented on chain/db/table.go
> +	ID          int64  `gorm:"unique;auto_increment:false"`
Do not change this

2020-03-30 13:18 UTC, sorawit requested changes

2020-03-30 13:18 UTC, sorawit commented on chain/db/db.go
> +	db.Model(&OracleScript{}).AddForeignKey(
We should not remove OracleScriptRevision foreign key. Please double check your code before pushing for reviews.

2020-03-30 14:25 UTC, taobun requested changes

2020-03-30 14:25 UTC, taobun commented on chain/db/db.go
> +	db.Model(&RelatedDataSources{}).AddForeignKey(
Already have this fk?

2020-03-30 14:25 UTC, taobun commented on chain/db/table.go
> +	ID          int64  `gorm:"unique;auto_increment:false"`
Please use this id as primary key

2020-03-30 14:25 UTC, taobun commented on chain/db/table.go
> +	CodeHash    []byte `gorm:"primary_key"`
Just not null

2020-03-30 14:35 UTC, taobun requested changes

2020-03-30 14:35 UTC, taobun commented on chain/db/oracle_script.go
> +	b.tx.First(&tmp, codeHash)
FirstOrCreate?

2020-03-31 04:17 UTC, taobun requested changes

2020-03-31 04:17 UTC, taobun commented on chain/db/oracle_script.go
> +	b.tx.First(&oracleScriptCode, codeHash)
Use FirstOrCreate like create oracle script or declare helper function to do it

2020-03-31 04:17 UTC, taobun commented on chain/db/oracle_script.go
> +	err = b.tx.Save(&OracleScriptCode{
Why save here? you just create this above?

2020-04-01 03:13 UTC, taobun approved these changes

2020-04-01 03:15 UTC, sorawit approved these changes

2020-04-01 03:48 UTC, merged