scan: patch cosmosjs binding to support sending MsgRequest transaction
bandprotocol/bandchain pull request #1069
Opened 2020-03-30 10:52 UTC by tansawit

Fixes: #1038

2020-03-30 10:56 UTC, sorawit requested changes

2020-03-30 10:56 UTC, sorawit commented on scan/src/bindings/StdMsgRequest.re
> +type t = {
Let's create a wrapper function that helps creating `t` from known types (`Address.t`, `int`, etc) so the caller is safe.

2020-03-30 17:02 UTC, sorawit requested changes

2020-03-30 17:02 UTC, sorawit commented on scan/src/bindings/StdMsgRequest.re
> +let create_t =
Use camelcase for function/variable names.

2020-03-30 17:02 UTC, sorawit commented on scan/src/bindings/StdMsgRequest.re
> +          oracleScriptID: string_of_int(oracleScriptID),
Stick to one pattern: `string_of_int(x)` or `x |> string_of_int`

2020-03-30 17:02 UTC, sorawit commented on scan/src/bindings/StdMsgSend.re
> +let create_t = (fromAddress, toAddress, sendAmount, accountNumber, sequence) => {
ditto here.

2020-03-30 17:02 UTC, sorawit commented on scan/src/bindings/StdMsgRequest.re
> +  returnT;
Can't you use return without creating a temporary variable?

2020-03-31 03:53 UTC, sorawit requested changes

2020-03-31 03:53 UTC, sorawit commented on scan/src/bindings/StdMsgRequest.re
> +let createT =
Can't we just name it `create`? What's that `T` for?

2020-03-31 04:24 UTC, taobun requested changes

2020-03-31 04:24 UTC, taobun commented on scan/src/bindings/StdMsgSend.re
> +let createT = (fromAddress, toAddress, sendAmount, accountNumber, sequence) => {
Just name it as `create`

2020-03-31 04:24 UTC, taobun commented on scan/src/bindings/StdMsgRequest.re
> +type send_value_t = {
request_value_t

2020-03-31 04:24 UTC, taobun commented on scan/src/bindings/StdMsgRequest.re
> +          expiration: 20 |> string_of_int,
Can we make it as optional parameter? (~expiration=20)

2020-03-31 04:24 UTC, taobun commented on scan/src/bindings/StdMsgRequest.re
> +          executeGas: 150000 |> string_of_int,
ditto

2020-03-31 04:24 UTC, taobun commented on scan/src/bindings/StdMsgRequest.re
> +      gas: 3000000 |> string_of_int,
gas too

2020-03-31 04:25 UTC, prin-r submitted a review, later dismissed

2020-03-31 07:37 UTC, sorawit approved these changes

2020-03-31 08:08 UTC, evilpeach approved these changes
LGTM

2020-03-31 08:17 UTC, taobun approved these changes

2020-03-31 08:28 UTC, merged