Show data source and oracle descriptions on ui
bandprotocol/bandchain pull request #1070
Opened 2020-03-30 12:09 UTC by prin-r

Fix #1012

2020-03-31 14:10 UTC, evilpeach requested changes

2020-03-31 14:10 UTC, evilpeach commented on scan/src/reusable/InfoHL.re
> +  | Text(string, theme_t)
I think we should make another variant called `Description`. The theme approach makes `Text` complicated.

2020-03-31 14:11 UTC, evilpeach commented on scan/src/reusable/InfoHL.re
> +  | Text(string, theme_t)
Moreover, please fix the conflict.

2020-04-02 08:22 UTC, evilpeach approved these changes

2020-04-02 08:35 UTC, tansawit approved these changes

2020-04-02 08:46 UTC, merged