The program should keep running and server a POST request for anyone to request BAND. The program utilize the library we have for sending transactions.
bandprotocol/bandchain pull request #1079
Opened 2020-03-31 02:16 UTC by Benzbeeb

Fixed #1048

2020-03-31 04:04 UTC, taobun requested changes

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +	queryURI    = getEnv("QUERY_URI", "http://localhost:1317")
Remove this variable

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +	sandboxMode = os.Getenv("SANDBOX_MODE") != ""
ditto

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +var rpcClient *rpc.HTTP
ditto

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +	Result string `json:"result"`
Change to TxHash

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +		Result: result.String(),
TxHash

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +	bandClient, err = bandlib.NewBandStatefulClient(nodeURI, pk, 100, 10, "request band requests")
Band faucet

2020-03-31 04:04 UTC, taobun commented on chain/cmd/requestband/main.go
> +	rpcClient = rpc.NewHTTP(nodeURI, "/websocket")
Remove it

2020-04-01 03:44 UTC, taobun requested changes
Let's add it to docker-compose and varnish

2020-04-02 03:03 UTC, taobun approved these changes

2020-04-02 05:23 UTC, sorawit approved these changes

2020-04-02 06:18 UTC, merged