Update result status after being executed during EndBlock
bandprotocol/bandchain pull request #1084
Opened 2020-03-31 15:38 UTC by Benzbeeb

Fixed #1046

2020-03-31 15:48 UTC, sorawit requested changes

2020-03-31 15:48 UTC, sorawit commented on chain/x/zoracle/internal/types/events.go
> +	EventTypeEndBlock            = "end_block"
EventTypeRequestExecute

2020-04-01 03:38 UTC, taobun requested changes

2020-04-01 03:38 UTC, taobun commented on chain/app/db_app.go
> +		if event.Type == zoracle.EventTypeRequestExecute {
Process event one by one

2020-04-01 05:50 UTC, sorawit requested changes

2020-04-01 05:50 UTC, sorawit commented on chain/x/zoracle/endblock.go
> +	newAttributes := []sdk.Attribute{
don't think we need this local variables.

2020-04-01 05:50 UTC, sorawit commented on chain/x/zoracle/endblock.go
> +func newRequestExecute(requestID RequestID, resolveStatus types.ResolveStatus) sdk.Event {
If we have this function. It should be named `newRequestExecuteEvent`

2020-04-01 05:50 UTC, sorawit commented on chain/x/zoracle/internal/types/request.go
> +type ResolveStatus string
I don't think it's a good idea to save string to store. `uint8` is good as is. If you want event to be string, then create a function that converts enum to string.

2020-04-01 06:55 UTC, sorawit requested changes

2020-04-01 06:55 UTC, sorawit commented on chain/x/zoracle/endblock.go
> +		[]sdk.Attribute{
Why do we need create an array and spread it out?

2020-04-01 06:55 UTC, sorawit commented on chain/x/zoracle/internal/types/request.go
> +		return ""
Let's return unknown.

2020-04-01 06:55 UTC, sorawit commented on chain/x/zoracle/internal/types/request.go
> +		return "Pending"
Here let's just use Open?

2020-04-01 09:43 UTC, taobun requested changes

2020-04-01 09:43 UTC, taobun commented on chain/db/db.go
> +func (b *BandDB) HandleEndBlock(id int64, resolveStatus string) error {
Set result if resolveStatus is "SUCCESS"

2020-04-01 09:43 UTC, taobun commented on chain/db/db.go
> +		Assign(Request{ResolveStatus: resolveStatus}).
Use update instead, it must have request in table

2020-04-01 09:43 UTC, taobun commented on chain/app/db_app.go
> +			app.dbBand.HandleEndBlock(requestID, resolveStatus)
panic if err occured

2020-04-01 09:44 UTC, taobun requested changes

2020-04-01 09:44 UTC, taobun commented on chain/app/db_app.go
> +			app.dbBand.HandleEndBlock(requestID, resolveStatus)
Rename this function to `ResolveRequest`

2020-04-02 03:16 UTC, taobun requested changes

2020-04-02 03:16 UTC, taobun commented on chain/app/db_app.go
> +						break
If you serious about parse requestID should use `panic`, but if you want to ignore this request it should be `continue`

In this case, my opinion is using `panic`

2020-04-02 03:50 UTC, taobun submitted a review, later dismissed

2020-04-02 08:47 UTC, sorawit requested changes

2020-04-02 08:47 UTC, sorawit commented on chain/db/db.go
> +	if resolveStatus == "Success" {
Let's expose `Success` in alias, and use `Success.String()` here.

2020-04-02 10:24 UTC, sorawit approved these changes

2020-04-02 10:24 UTC, taobun approved these changes

2020-04-02 10:24 UTC, merged