scan: Implement subscription hook for validators + wireup
bandprotocol/bandchain pull request #1093
Opened 2020-04-01 13:08 UTC by tansawit

Fixes: #991

2020-04-02 04:28 UTC, evilpeach requested changes

2020-04-02 04:28 UTC, evilpeach commented on scan/.bsb 12.lock
> +84424
remove

2020-04-02 04:28 UTC, evilpeach commented on scan/src/subscriptions/ReportSub.re
> +  // ];
remove?

2020-04-02 04:28 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +    Js.Console.log(validatorSub);
remove

2020-04-02 04:28 UTC, evilpeach commented on scan/src/subscriptions/ValidatorSub.re
> +module Validator = {
I think we don't wrap in Validator.

2020-04-03 03:36 UTC, prin-r commented on scan/src/pages/ValidatorHomePage.re
> +    let bondedValidatorCountSub = ValidatorSub.count();
add TODO

2020-04-03 03:58 UTC, prin-r commented on scan/src/pages/ValidatorIndexPage.re
>      let totalPower =
Create another Sub that return aggregation of voting power

2020-04-03 04:01 UTC, prin-r commented on scan/src/pages/ValidatorIndexPage.re
>      let totalPower =
We can't do that right now, so please add TODO.

2020-04-03 04:12 UTC, prin-r commented on scan/src/subscriptions/ValidatorSub.re
> +    "bandvalconspub1addwnpepq0grwz83v8g4s06fusnq5s4jkzxnhgvx67qr5g7v8tx39ur5m8tk7rg2nxj"
We are not using it right now, please remove this field.

2020-04-03 04:12 UTC, prin-r approved these changes

2020-04-03 04:13 UTC, prin-r requested changes
fix things first

2020-04-03 04:46 UTC, prin-r submitted a review, later dismissed

2020-04-03 07:39 UTC, evilpeach requested changes

2020-04-03 07:39 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +        ~pageSize=5,
use pageSIze

2020-04-03 07:56 UTC, prin-r approved these changes

2020-04-03 07:58 UTC, evilpeach approved these changes

2020-04-03 07:58 UTC, merged