Implement tx cli for MsgAddOracleAddress and MsgRemoveOracleAddress
bandprotocol/bandchain pull request #1098
Opened 2020-04-02 05:31 UTC by Benzbeeb

Fixed #1007

2020-04-02 05:33 UTC, sorawit requested changes

2020-04-02 05:33 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Use:   "add-oracle-address (--validator [validator]) (--reporter [reporter])",
Let's make it positional arguments. It's just two arguments and I think it's the standard.

2020-04-02 06:04 UTC, sorawit requested changes

2020-04-02 06:04 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	flagValidator                = "validator"
Why is this still here?

2020-04-02 09:54 UTC, sorawit approved these changes
looks great.

2020-04-03 03:04 UTC, taobun approved these changes

2020-04-03 03:13 UTC, merged