Implement loading animation for all cards
bandprotocol/bandchain pull request #1131
Opened 2020-04-04 18:27 UTC by prin-r

Fix #1025

2020-04-05 03:14 UTC, tansawit submitted a review, later dismissed

2020-04-05 06:46 UTC, sorawit submitted a review, later dismissed

2020-04-05 06:46 UTC, sorawit commented on scan/src/components/ChainInfoHighlights.re
>      let mockFinance: PriceHook.Price.t = {
I don't think this is needed anymore? Let's have loading state if price is still not loaded.

2020-04-05 06:46 UTC, sorawit commented on scan/src/components/ChainInfoHighlights.re
> +      switch (latestBlock_) {
This is too complicated and error prone. If we write it correct, we should never really need default dummy values.

2020-04-07 03:46 UTC, evilpeach requested changes

2020-04-07 03:46 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +        <div className={Styles.withWidth(170)}>
The div with style should send along with `extraComponent`.  No need to set it here.

2020-04-08 08:53 UTC, evilpeach requested changes

2020-04-08 08:53 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +         }}
IMO, we can put the switch `valueAndExtraComponentSub ` together and then switch on `bgUrl` inside.

2020-04-08 12:36 UTC, evilpeach approved these changes

2020-04-08 12:37 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +         }}
However, I think it's ok for now.

2020-04-09 03:14 UTC, tansawit approved these changes

2020-04-09 03:32 UTC, merged