Write a simple program to periodically update validator set to the destination EVM blockchain
bandprotocol/bandchain pull request #1149
Opened 2020-04-06 16:15 UTC by Benzbeeb

Fixed #1019

2020-04-07 04:19 UTC, taobun requested changes

2020-04-07 04:19 UTC, taobun commented on chain/cmd/bandevmbot/main.go
> +		Use:   "update-validator [rpc-uri] [contract-address] [node-uri] [priv-key] [gas-price] [poll-interval] ",
Change to flag arguments not positional arguments

2020-04-07 04:19 UTC, taobun commented on chain/cmd/bandevmbot/main.go
> +func update_validator(rpcURI string, address string, node string, privateKey string, gasPrice uint64) {
camelCase

2020-04-13 06:24 UTC, sorawit requested changes

2020-04-13 06:24 UTC, sorawit commented on chain/cmd/bandevmbot/main.go
> +	evmClient, _ := ethclient.Dial(rpcURI)
Why do we ignore the second return value?

2020-04-14 06:36 UTC, sorawit approved these changes
looks great

2020-04-14 07:34 UTC, taobun approved these changes

2020-04-16 03:09 UTC, merged