Loading state for tx table front page
bandprotocol/bandchain pull request #1153
Opened 2020-04-07 10:47 UTC by prin-r

Fix #1132

2020-04-07 10:51 UTC, prin-r commented
This PR is waiting for #1025 (Implement loading animation for all cards). However everyone can review anyway.

2020-04-09 10:19 UTC, evilpeach requested changes

2020-04-09 10:19 UTC, evilpeach commented on scan/src/components/LatestTxTable.re
> +
Let's use `Belt.List.make` or `Belt.Array.make`

2020-04-09 10:19 UTC, evilpeach commented on scan/src/components/LatestTxTable.re
> +       ->Belt_Array.mapWithIndex((i, e) => txBodyRender(i, ApolloHooks.Subscription.Data(e)))
Don't use `ApolloHooks.Subscription.Data`. Let's use `Sub.resolve`.

2020-04-09 10:19 UTC, evilpeach commented on scan/src/components/LatestTxTable.re
> +       createNoDataList(10)
Use `Belt.Array.make`.

2020-04-09 10:19 UTC, evilpeach commented on scan/src/components/LatestTxTable.re
> +             <span className=Styles.amount> {totalCount |> Format.iPretty |> React.string} </span>
Let's remove the amount style and use `Text`.

2020-04-10 02:44 UTC, evilpeach requested changes
![image](https://user-images.githubusercontent.com/14128977/78957549-d49ce780-7b0f-11ea-84c6-fdf1db67f99c.png)
The msg in the action column exceeds the table.

2020-04-13 02:11 UTC, evilpeach approved these changes

2020-04-15 06:22 UTC, tansawit approved these changes

2020-04-15 06:22 UTC, merged