scan: Implement UI for oracle script integration tab
bandprotocol/bandchain pull request #1155
Opened 2020-04-07 14:34 UTC by tansawit

Fixes: #1139

2020-04-09 04:07 UTC, prin-r requested changes

2020-04-09 04:07 UTC, prin-r commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +module LanguageIcon = {
A set of languages should dependence on the choice of a target platform.

2020-04-09 04:14 UTC, prin-r requested changes
<img width="1405" alt="Screen Shot 2563-04-09 at 11 09 18" src="https://user-images.githubusercontent.com/12705423/78857259-161b8d00-7a53-11ea-8b15-9cf48e9fa791.png">
Please adjust the logo to be at the center

2020-04-10 03:50 UTC, evilpeach requested changes
Please fix the conflict on `Image.re` as well.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/utils/Route.re
> +  | (["oracle-script", oracleScriptID], "bridgecode") =>
Let's use `bridge`.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/utils/Route.re
> +  | OracleScriptIndexPage(oracleScriptID, OracleScriptBridgeCode) => {j|/oracle-script/$oracleScriptID#bridgecode|j}
use `bridge` here as well.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +    <>
No need to use Fragment here.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +          <Text value="Description" size=Text.Lg color=Colors.gray7 weight=Text.Medium />
Let's use the default font-weight and add letter-spacing by add prop called `spacing={Text.Em(0.03}`.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +        <Text value=description size=Text.Lg />
As I see on design, the font-weight is thin and letter-spacing is 0.03.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +      left(`px(0)),
Instead of using \`px(0) just use \`zero.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +                };
IMO, we should use the variant instead of the string. Let's make a type for target platform and language.

2020-04-10 03:50 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +          <div> <Text value="Language" /> </div>
Please check the design.

2020-04-10 18:02 UTC, sorawit submitted a review, later dismissed

2020-04-10 18:02 UTC, sorawit commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +  | _ => raise(WrongPlatformChoice("Chosen language does not exist"));
typo: platform?

2020-04-10 18:02 UTC, sorawit commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +let getLanguageByPlatform =
languages

2020-04-12 16:50 UTC, evilpeach approved these changes
LGTM

2020-04-12 17:40 UTC, prin-r approved these changes

2020-04-12 17:40 UTC, merged