Add transaction id to transaction table + update necessary hooks
bandprotocol/bandchain pull request #1176
Opened 2020-04-09 14:13 UTC by Benzbeeb

Fixed #1081

2020-04-10 03:09 UTC, taobun requested changes

2020-04-10 03:09 UTC, taobun commented on chain/db/request.go
> +	"github.com/bandprotocol/bandchain/chain/x/oracle/types"
Remove this line

2020-04-10 03:09 UTC, taobun commented on chain/db/request.go
> +	request, err := b.OracleKeeper.GetRequest(b.ctx, types.RequestID(id))
Use `oracle.RequestID`

2020-04-10 03:09 UTC, taobun commented on chain/db/request.go
> +	request, err := b.OracleKeeper.GetRequest(b.ctx, types.RequestID(id))
but we have 2 place to add new request (ibc.go), so in my opinion change this on `AddNewRequest` function instead

2020-04-10 18:05 UTC, sorawit submitted a review, later dismissed
Thank you!

2020-04-12 12:51 UTC, sorawit approved these changes

2020-04-12 14:20 UTC, merged