Implement Subscription and wire up for Delegation on account index page
bandprotocol/bandchain pull request #1180
Opened 2020-04-09 17:09 UTC by tansawit

Fixes: #1136

2020-04-09 17:24 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-04-10 07:25 UTC, sorawit requested changes

2020-04-10 07:25 UTC, sorawit commented on scan/src/subscriptions/DelegationSub.re
> +      amount @bsDecoder(fn: "GraphQLParser.bandAmountOpt")
numberExn

2020-04-10 07:25 UTC, sorawit commented on scan/src/subscriptions/DelegationSub.re
> +      delegatorAddress: delegator_address @bsDecoder(fn: "GraphQLParser.addressOpt")
addressExn

2020-04-10 07:25 UTC, sorawit commented on scan/src/subscriptions/DelegationSub.re
> +    delegations_view(where: {delegator_address: {_eq: $delegator_address}}) @bsRecord  {
offset, limit, orderby

2020-04-10 07:25 UTC, sorawit commented on scan/src/subscriptions/DelegationSub.re
> +  let (result, _) =
offset, limit

2020-04-10 12:13 UTC, prin-r submitted a review, later dismissed

2020-04-10 12:17 UTC, prin-r submitted a review, later dismissed

2020-04-10 14:01 UTC, sorawit submitted a review, later dismissed

2020-04-10 14:40 UTC, evilpeach approved these changes

2020-04-10 16:37 UTC, prin-r approved these changes

2020-04-10 16:43 UTC, merged