Add median and test with average
bandprotocol/bandchain pull request #1189
Opened 2020-04-10 12:12 UTC by taobun

fixed #1114

2020-04-10 18:05 UTC, sorawit requested changes

2020-04-10 18:05 UTC, sorawit commented on owasm/src/ext/mod.rs
> +    let mut vals: Vec<T> = Vec::new();
Let's have a separate function to do this loading for both `load_average` and `load_median`

2020-04-15 07:08 UTC, sorawit approved these changes
OK for now. There must be a way to do it without requiring this much traits, but let's save that for another day.

2020-04-15 10:45 UTC, Benzbeeb approved these changes

2020-04-15 12:39 UTC, merged