Support active and inactive state on validator sub
bandprotocol/bandchain pull request #1192
Opened 2020-04-10 18:46 UTC by prin-r

Fix #1142

2020-04-11 07:50 UTC, sorawit submitted a review, later dismissed

2020-04-11 07:50 UTC, sorawit commented on scan/src/subscriptions/ValidatorSub.re
> -        validators(limit: $limit, offset: $offset) @bsRecord {
While we are here. Let's also add order by tokens desc.

2020-04-11 07:50 UTC, sorawit commented on scan/src/pages/ValidatorHomePage.re
>    <TBody key={rank |> string_of_int}>
Shouldn't key be the validator address? Don't think rank is the right value for key?

2020-04-14 04:17 UTC, evilpeach requested changes

2020-04-14 04:17 UTC, evilpeach commented on scan/src/subscriptions/ValidatorSub.re
> +let getList = (~page=1, ~pageSize=10, ~isActive, ()) => {
Let's remove the default value of page and pageSize.

2020-04-15 08:42 UTC, evilpeach approved these changes
LGTM

2020-04-16 03:14 UTC, tansawit approved these changes

2020-04-16 03:31 UTC, merged