Wireup ibc message page
bandprotocol/bandchain pull request #1193
Opened 2020-04-10 20:03 UTC by prin-r

Fix #1138

2020-04-10 20:04 UTC, prin-r commented
This PR is not complete yet.

2020-04-13 02:23 UTC, evilpeach commented
@sorawit Should #1246 merge before this ticket?

2020-04-13 02:45 UTC, sorawit requested changes

2020-04-13 02:45 UTC, sorawit commented on scan/src/subscriptions/IBCSub.re
> +  chennel: string,
typo?

2020-04-13 02:45 UTC, sorawit commented on scan/src/subscriptions/IBCSub.re
> +type internal_t = {
Let's wrap internal type in its own module.

2020-04-13 12:27 UTC, evilpeach requested changes

2020-04-13 12:27 UTC, evilpeach commented on scan/src/subscriptions/IBCSub.re
> +      packets(limit: $limit, offset: $offset) @bsRecord {
add orderBy block height (DESC)

2020-04-13 12:27 UTC, evilpeach commented on scan/src/subscriptions/IBCSub.re
> +    subscription Requests($limit: Int!, $offset: Int!) {
Rename Requests to Packets

2020-04-13 12:27 UTC, evilpeach commented on scan/src/components/Packet.re
> +      {let calldataRender =
Let's name calldataHeadRender

2020-04-13 12:27 UTC, evilpeach commented on scan/src/components/Packet.re
> +           {let resultRender =
Let's name `resultHeaderRender`

2020-04-13 13:18 UTC, evilpeach requested changes

2020-04-13 13:18 UTC, evilpeach commented on scan/src/subscriptions/IBCSub.re
> +        Js.Console.log(packetType);
remove log

2020-04-13 13:18 UTC, evilpeach commented on scan/src/components/Packet.re
> +           {let resultHeaderRender =
`resultHeadRender`

2020-04-13 14:23 UTC, evilpeach commented on scan/src/components/Packet.re
> +         let outputKVsOpt =
add TODO: support loading state, no data later

2020-04-13 15:37 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-04-13 15:40 UTC, sorawit requested changes

2020-04-13 15:40 UTC, sorawit commented on scan/src/components/Packet.re
> +    let outputKVsOpt =
also here?

2020-04-13 15:40 UTC, sorawit commented on scan/src/subscriptions/IBCSub.re
> +            requestedValidatorCount: packetDetail |> at(["ask_count"], int),
bug?

2020-04-13 15:48 UTC, sorawit approved these changes

2020-04-13 15:50 UTC, evilpeach approved these changes

2020-04-13 15:56 UTC, merged