Implement owasm load_majority function
bandprotocol/bandchain pull request #1245
Opened 2020-04-12 10:49 UTC by Benzbeeb

Fixed #1113

2020-04-15 07:11 UTC, sorawit requested changes

2020-04-15 07:11 UTC, sorawit commented on owasm/src/ext/mod.rs
> +    for idx in 1..len {
Add link or reference to the algo you are using.

2020-04-16 03:45 UTC, taobun requested changes

2020-04-16 03:45 UTC, taobun commented on owasm/src/ext/mod.rs
> +    let mut vec: Vec<T> = Vec::new();
Using load_input

2020-04-19 10:36 UTC, taobun approved these changes

2020-04-19 11:08 UTC, sorawit approved these changes

2020-04-20 03:44 UTC, merged