Remove hard code prepare and execution gas
bandprotocol/bandchain pull request #1249
Opened 2020-04-13 06:59 UTC by Benzbeeb

Fixes #1233

2020-04-13 12:03 UTC, sorawit requested changes

2020-04-13 12:03 UTC, sorawit commented on chain/x/oracle/types/params.go
> +	ExecuteGas                       uint64 `json:"ExecuteGas"`
why don't we follow the same convention and use snake case?

2020-04-15 03:37 UTC, taobun submitted a review, later dismissed

2020-04-15 03:37 UTC, taobun commented
@Benzbeeb Fix conflict?

2020-04-15 08:01 UTC, sorawit approved these changes

2020-04-15 08:04 UTC, taobun approved these changes

2020-04-15 08:04 UTC, merged