scan: add orderBy every getList on Subscription
bandprotocol/bandchain pull request #1250
Opened 2020-04-13 07:08 UTC by tansawit

Fixes: #1215

2020-04-14 04:21 UTC, prin-r submitted a review, later dismissed

2020-04-14 17:24 UTC, evilpeach requested changes
Please check `MultiConfig` on `RequestSub`

2020-04-15 03:13 UTC, evilpeach approved these changes

2020-04-15 05:16 UTC, prin-r approved these changes

2020-04-15 05:34 UTC, merged