Add gold price data source
bandprotocol/bandchain pull request #1254
Opened 2020-04-13 10:23 UTC by Benzbeeb

2020-04-13 12:05 UTC, sorawit submitted a review, later dismissed
Looks great

2020-04-13 16:45 UTC, taobun requested changes

2020-04-13 16:45 UTC, taobun commented on chain/datasources/binance_atom_price.sh
> +#!/bin/sh
Why we need this script? Using old binance script?

2020-04-13 16:45 UTC, taobun commented on owasm/chaintests/gold_price/src/lib.rs
> +    oei::request_external_data(6, 2, input.symbol.as_bytes());
I think we can use existing Binance script and send "ATOM".as_bytes() here instead

2020-04-13 16:45 UTC, taobun commented on owasm/chaintests/gold_price/src/lib.rs
> +    symbol: String,
Don't need it in this case

2020-04-13 16:46 UTC, taobun requested changes

2020-04-13 16:46 UTC, taobun commented on owasm/chaintests/gold_price/src/lib.rs
> +    oei::request_external_data(5, 1, input.symbol.as_bytes());
Help me test if we send empty bytes, it will work correctly

2020-04-13 17:06 UTC, taobun requested changes

2020-04-13 17:06 UTC, taobun commented on chain/app/genesis.go
> +			"Oracle script for getting an average gold price from many sources.",
Many sources LUL

2020-04-13 17:06 UTC, taobun commented on chain/app/genesis.go
> +			"Oracle script for getting an average gold price from many sources.",
Oracle script for getting an average gold price in ATOM

2020-04-14 01:12 UTC, taobun approved these changes

2020-04-14 12:46 UTC, merged