chain: go borsh library to encode struct to bytes
bandprotocol/bandchain pull request #1265
Opened 2020-04-14 08:41 UTC by tansawit

Fixes: #1198

2020-04-16 04:01 UTC, taobun requested changes

2020-04-16 04:01 UTC, taobun commented on chain/borsh/decode.go
> +// DecodeU8 deodes the input bytes and returns the corresponding
deodes

2020-04-16 04:01 UTC, taobun commented on chain/borsh/decode.go
> +func (decoder *BorshDecoder) DecodeSigned8() (int8, error) {
DecodeI8

2020-04-16 04:01 UTC, taobun commented on chain/borsh/decode.go
> +	unsigned, _ := decoder.DecodeU8()
Why ignore error?

2020-04-16 04:01 UTC, taobun commented on chain/borsh/decode.go
> +		return []byte{}, err
return nil, err

2020-04-21 03:48 UTC, taobun requested changes

2020-04-21 03:48 UTC, taobun commented on chain/borsh/decode_test.go
> +	fmt.Println(len(decoder.data))
Remove this

2020-04-21 03:48 UTC, taobun commented on chain/borsh/decode_test.go
> +		t.Errorf(`Incorrect result for Finished bool: expected "%t" got "%t"`, false, decodeFinished)
Our code base use [require](https://godoc.org/github.com/stretchr/testify/require) for testing

2020-04-21 03:48 UTC, taobun commented on chain/borsh/decode_test.go
> +	var expectedU8 uint8 = 112
expectedU8 := uint8(112)

2020-04-21 03:48 UTC, taobun commented on chain/borsh/decode_test.go
> +	if err != nil {
If we use `require`, it will just require.NotNil(t, err)

2020-04-21 03:48 UTC, taobun commented on chain/borsh/encode.go
> +	encoder.data = append(encoder.data, bytes...)
We can write `encoder.data = append(encoder.data, value)`

2020-04-21 12:41 UTC, taobun requested changes

2020-04-21 12:41 UTC, taobun commented on chain/borsh/decode_test.go
> +	require.Equal(t, decodeFinished, false, `Incorrect result for Finished boolean: expected "false"`)
require.False

2020-04-21 12:41 UTC, sorawit requested changes

2020-04-21 12:41 UTC, sorawit commented on chain/borsh/encode.go
> +func (encoder *BorshEncoder) EncodeU64(value uint64) {
an

2020-04-21 13:00 UTC, sorawit approved these changes
Looks good

2020-04-22 03:04 UTC, taobun approved these changes

2020-04-22 03:36 UTC, merged