Loading animation on latest blocks
bandprotocol/bandchain pull request #1266
Opened 2020-04-14 09:24 UTC by prin-r

Fix #1222

2020-04-14 12:28 UTC, tansawit submitted a review, later dismissed

2020-04-14 17:33 UTC, evilpeach requested changes

2020-04-14 17:33 UTC, evilpeach commented on scan/src/components/LatestBlocks.re
> +           <span className=Styles.amount> {blocksCount |> Format.iPretty |> React.string} </span>;
Use `Text` instead of `span`

2020-04-15 07:12 UTC, evilpeach approved these changes

2020-04-15 07:28 UTC, tansawit approved these changes

2020-04-15 07:41 UTC, merged