Scan: Binding ledger-cosmos-js
bandprotocol/bandchain pull request #1273
Opened 2020-04-15 03:55 UTC by evilpeach

Fixes #1203

2020-04-15 06:03 UTC, sorawit requested changes

2020-04-15 06:03 UTC, sorawit commented on scan/src/bindings/Ledger.re
> +       Js.Console.log(response.bech32_address);
Why do we log?

2020-04-18 06:49 UTC, sorawit requested changes

2020-04-18 06:49 UTC, sorawit commented on scan/src/wallet/Wallet.re
> +  let bandChain = BandWeb3.network(rpcUrl, "bandchain");
I think we can put arbitrary url and chain id here. Reading https://github.com/cosmostation/cosmosjs/blob/master/src/index.js, I don't think it requires url or chain id for getting address or signing.

2020-04-18 06:49 UTC, sorawit commented on scan/src/wallet/Wallet.re
> +let createFromLedger = path => {
I think this should be a promise that errors if a ledger is not connected?

2020-04-22 01:53 UTC, evilpeach commented
@sorawit Currently, there are snake case variables on the binding. Is there a way to handle this properly instead of creating `raw_response_t`(contains snake case) and `response_t` (camel case).

2020-04-22 04:42 UTC, sorawit approved these changes

2020-04-22 07:12 UTC, tansawit approved these changes

2020-04-22 07:12 UTC, merged