Implement ibc tx index page ui and wire up
bandprotocol/bandchain pull request #1274
Opened 2020-04-15 05:49 UTC by prin-r

Fix #1209

2020-04-16 03:36 UTC, evilpeach requested changes

2020-04-16 03:36 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +      timeoutHeight: ID.Block.t,
It should be int.

2020-04-16 03:36 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +          timeoutHeight: json |> at(["packet", "timeout_height"], ID.Block.fromJson),
decode to int

2020-04-16 03:36 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +          timeoutHeight: ID.Block.ID(999999),
int too

2020-04-16 03:36 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +          timeoutHeight: json |> at(["packet", "timeout_height"], ID.Block.fromJson),
decode to int as well

2020-04-18 12:22 UTC, evilpeach approved these changes

2020-04-21 03:11 UTC, tansawit approved these changes

2020-04-21 11:46 UTC, merged