scan: implement reward sub and wire up
bandprotocol/bandchain pull request #1278
Opened 2020-04-16 03:01 UTC by tansawit

Fixes: #1217

2020-04-16 03:47 UTC, evilpeach requested changes
add reward in `PieChart`

2020-04-16 03:47 UTC, evilpeach commented on scan/src/subscriptions/DelegationSub.re
> +  Js.Console.log(result);
remove log

2020-04-16 03:47 UTC, evilpeach commented on scan/src/subscriptions/DelegationSub.re
> +  Js.Console.log(result);
remove log too

2020-04-17 03:22 UTC, prin-r submitted a review, later dismissed

2020-04-17 06:46 UTC, evilpeach requested changes

2020-04-17 06:46 UTC, evilpeach commented on scan/src/subscriptions/DelegationSub.re
> +
Why don't use a single subscription? 
Like this
```
let delegatorInfoSub = result
    |> Sub.map(_, a =>
         (
           (a##delegations_view_aggregate##aggregate |> Belt_Option.getExn)##sum
           |> Belt_Option.getExn
         )

let%Sub delegatorInfo = delegatorInfoSub;
// And then return
{amount: delegatorInfo##amount, reward: delegatorInfo##reward} |> Sub.resolve;
```

2020-04-17 08:06 UTC, evilpeach approved these changes

2020-04-17 08:08 UTC, prin-r approved these changes

2020-04-17 08:08 UTC, merged