Store only result hash in storage
bandprotocol/bandchain pull request #1282
Opened 2020-04-16 07:15 UTC by Benzbeeb

- [x] Hash all information ```H(H(reqPacket)||H(resPacket))``` and store this value in storage instead

 

- [ ] Emit result detail as an event.

2020-04-16 08:39 UTC, taobun requested changes

2020-04-16 08:39 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +		string(request.Calldata), request.SufficientValidatorCount,
hex.EncodeToString(request.Calldata)

2020-04-16 08:39 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +		return
Choose one

2020-04-16 08:39 UTC, taobun commented on chain/x/oracle/keeper/result.go
> +	if uint64(len([]byte(responsePacket.Result))) > k.GetParam(ctx, types.KeyMaxResultSize) {
Seem weird

2020-04-16 15:02 UTC, taobun requested changes

2020-04-16 15:02 UTC, taobun commented on chain/db/db.go
> +func (b *BandDB) ResolveRequest(kvMap map[string]string) error {
Let's move this function to `endblock.go` (this file is too big)

2020-04-16 15:02 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +func (k Keeper) handleResolveRequest(
Rename to resolveRequest

2020-04-16 15:02 UTC, taobun commented on chain/db/db.go
>  	if resolveStatus == 1 {
Let's add all resolve status to alias and compare with meaningful status

2020-04-16 15:02 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +				sdk.NewAttribute(types.AttributeKeyResolveStatus, fmt.Sprintf("%d", resolveStatus)),
It will emit resolve completed without result?

2020-04-16 15:02 UTC, taobun commented on chain/x/oracle/keeper/result.go
> +			len([]byte(responsePacket.Result)), k.GetParam(ctx, types.KeyMaxResultSize),
You compare with length of result?

2020-04-16 15:02 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +	k.handleResolveRequest(ctx, reqID, resolveStatus, result)
What does this function actually do?

2020-04-16 15:02 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +	resPacketData := types.NewOracleResponsePacketData(
It seems to create this packet 2 times for no reason.

2020-04-20 03:09 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +func (k Keeper) handleResolveRequest(
Why resolve this comment without doing anything?

2020-04-20 09:28 UTC, sorawit requested changes

2020-04-20 09:28 UTC, sorawit commented on chain/x/oracle/keeper/request.go
> +	request, err := k.GetRequest(ctx, reqID)
MustGetRequest

2020-04-20 10:24 UTC, taobun requested changes

2020-04-20 10:24 UTC, taobun commented on chain/db/table.go
> +	ExpirationTime           int64  `sql:"default:null"`
ExpirationHeight

2020-04-20 13:10 UTC, taobun requested changes

2020-04-20 13:10 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +			sdk.NewAttribute(types.AttributrKeyExpirationHeight, fmt.Sprintf("%d", 10)), // TODO: REMOVE THIS
currentBlock + 10

2020-04-22 02:35 UTC, sorawit submitted a review, later dismissed

2020-04-22 02:37 UTC, taobun submitted a review, later dismissed

2020-04-22 03:08 UTC, taobun approved these changes

2020-04-22 03:09 UTC, sorawit approved these changes

2020-04-22 03:10 UTC, merged