Implement GetBlockHeaderMerkleParts and test
bandprotocol/bandchain pull request #1360
Opened 2020-04-20 04:12 UTC by taobun

fixed #1323

2020-04-20 07:12 UTC, sorawit requested changes

2020-04-20 07:12 UTC, sorawit commented on chain/go.sum
> +github.com/Azure/azure-pipeline-go v0.2.1/go.mod h1:UGSo8XybXnIGZ3epmeBw7Jdz+HiUVpqIlpz/HKHylF4=
Did you make sure to run go mod tidy?

2020-04-20 07:12 UTC, sorawit commented on chain/client/proof.go
>  // TODO: Revive this! It's commented because we upgrade to Cosmos 0.38.*.
Let's remove the TODO if this is done?

2020-04-20 07:12 UTC, sorawit commented on chain/client/proof.go
> +func MakeOtherStoresMerkleHash(mspo rootmulti.MultiStoreProofOp) (tmbytes.HexBytes, tmbytes.HexBytes, tmbytes.HexBytes) {
Can we break this down into smaller, more understandable chunks that we can test separately?

2020-04-20 07:12 UTC, sorawit commented on chain/client/proof.go
> +		if si.Name == "oracle" {
Can we take this string from some defined variable? `oracle.ModuleName`?

2020-04-20 07:51 UTC, taobun commented on chain/go.sum
> +github.com/Azure/azure-pipeline-go v0.2.1/go.mod h1:UGSo8XybXnIGZ3epmeBw7Jdz+HiUVpqIlpz/HKHylF4=
yep

2020-04-20 09:24 UTC, sorawit requested changes

2020-04-20 09:24 UTC, sorawit commented on chain/client/proof.go
> +type BlockHeaderMerkleParts struct {
Let's move this into its own file

2020-04-20 10:20 UTC, sorawit approved these changes

2020-04-21 12:32 UTC, tansawit approved these changes

2020-04-21 13:27 UTC, merged