scan: generate calldata struct and encode function in go
bandprotocol/bandchain pull request #1363
Opened 2020-04-20 08:16 UTC by tansawit

Fixes: #1290

2020-04-21 04:08 UTC, taobun requested changes

2020-04-21 04:08 UTC, taobun commented on scan/src/bindings/Borsh.re
> +
Add import from our library and add at decode too

2020-04-23 05:34 UTC, taobun requested changes

2020-04-23 05:34 UTC, taobun commented on scan/__tests__/Borsh_test.re
> +	return encoder.data
encode.GetEncodedData

2020-04-23 05:34 UTC, taobun commented on scan/__tests__/Borsh_test.re
> +	return encoder.data
ditto

2020-04-23 05:34 UTC, taobun commented on scan/src/bindings/Borsh.re
> +\treturn encoder.data
root clause

2020-04-28 04:42 UTC, sorawit commented
@tansawit @taobun @evilpeach Let's have this merged today

2020-04-28 12:06 UTC, evilpeach approved these changes

2020-04-29 04:09 UTC, taobun approved these changes

2020-04-29 04:09 UTC, merged