scan: wire up bridge code tab
bandprotocol/bandchain pull request #1364
Opened 2020-04-20 08:19 UTC by tansawit

Fixes: #1302

2020-04-21 03:37 UTC, evilpeach requested changes

2020-04-21 03:37 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +};
Let's return `codeOpt`, then handle option case on the render.
If code is available, you render it the same way.
If not, you just render the message "Code is not verified."

2020-04-21 03:37 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +       code->renderCode}
Handle `codeOpt` here.

2020-04-22 04:43 UTC, evilpeach requested changes

2020-04-22 04:43 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptBridgeCode.re
> +  codeOpt;
Just return it, no need to declare `codeOpt`.

2020-04-22 15:26 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-04-22 16:10 UTC, evilpeach approved these changes

2020-04-22 16:50 UTC, prin-r approved these changes

2020-04-22 16:50 UTC, merged