Implement TotalSupply Cacher
bandprotocol/bandchain pull request #1366
Opened 2020-04-20 09:09 UTC by taobun

fixed #1300

2020-04-20 09:33 UTC, sorawit requested changes

2020-04-20 09:33 UTC, sorawit commented on chain/db/metadata.go
> +		return sdk.Coins{}, err
nit: nil

2020-04-21 03:29 UTC, sorawit approved these changes

2020-04-23 03:00 UTC, Benzbeeb approved these changes

2020-04-23 07:22 UTC, merged