chain: Implement REST endpoint to get packets from req id
bandprotocol/bandchain pull request #1379
Opened 2020-04-22 06:40 UTC by sorawit

2020-04-22 17:10 UTC, taobun approved these changes

2020-04-22 17:16 UTC, taobun requested changes

2020-04-22 17:16 UTC, taobun commented on chain/client/result.go
> +		resp, err := cliCtx.Client.ABCIQueryWithOptions(
handle error?

2020-04-24 07:56 UTC, sorawit commented
Not necessary anymore.

2020-04-24 07:56 UTC, closed without merging