The new bridge contract setup
bandprotocol/bandchain pull request #1385
Opened 2020-04-22 09:06 UTC by taobun

fixed #1327

2020-04-22 09:23 UTC, sorawit requested changes

2020-04-22 09:23 UTC, sorawit commented on bridges/evm/contracts/IBridge.sol
>      struct VerifyOracleDataResult {
I don't think this is needed anymore? Why can't `relayAndVerify` returns `(RequestPacket memory, ResponsePacket memory)`?

2020-04-22 09:23 UTC, sorawit commented on bridges/evm/contracts/IBridgeV2.sol
> +    function requestOracle(
Can this just accept `RequestPacket` as argument?

2020-04-24 06:14 UTC, sorawit approved these changes
looks good

2020-04-24 07:20 UTC, Benzbeeb approved these changes

2020-04-24 07:57 UTC, merged