Make `MsgRequestData` acts like a request packet is relayed, not the other around
bandprotocol/bandchain pull request #1386
Opened 2020-04-22 10:19 UTC by Benzbeeb

Fixed #1236

2020-04-22 13:51 UTC, sorawit requested changes

2020-04-22 13:51 UTC, sorawit commented on chain/x/oracle/types/request.go
> +func NewRequestWithRequstIBC(
typo

2020-04-23 03:50 UTC, sorawit approved these changes
Looks great

2020-04-23 06:28 UTC, taobun approved these changes

2020-04-23 06:53 UTC, merged