Make sure block relay proof can verify correct signature
bandprotocol/bandchain pull request #1396
Opened 2020-04-23 08:24 UTC by taobun

fixed #1326

2020-04-23 08:25 UTC, taobun commented on chain/client/proof/signature.go
> +		lr := strings.Split(hex.EncodeToString(msg), hex.EncodeToString(info.Commit.BlockID.Hash))
It's the same value but doesn't need to re-calculate.

2020-04-24 06:26 UTC, Benzbeeb requested changes

2020-04-24 06:26 UTC, Benzbeeb commented on chain/client/proof/signature.go
> +		if vote.Signature == nil {
if vote.Absent() {
	continue // OK, some signatures can be absent.
}

2020-04-24 07:19 UTC, Benzbeeb approved these changes

2020-04-24 07:59 UTC, sorawit approved these changes

2020-04-24 08:32 UTC, merged