Modify verify code with new proof
bandprotocol/bandchain pull request #1398
Opened 2020-04-23 12:49 UTC by Benzbeeb

- [x ]  block header part

- [ ]  app hash part

- [ ] result part

2020-04-24 06:21 UTC, taobun submitted a review, later dismissed

2020-04-24 08:33 UTC, sorawit requested changes

2020-04-24 08:33 UTC, sorawit commented on bridges/evm/contracts/BlockHeaderMerkleParts.sol
> +        bytes32 lastBlockIDAndOther; // [2B]
Please update the comment to reflect the change

2020-04-24 09:36 UTC, sorawit requested changes

2020-04-24 09:36 UTC, sorawit commented on bridges/evm/contracts/BlockHeaderMerkleParts.sol
> +            Utils.merkleInnerHash( // [Block Header]
BlockHeader

2020-04-24 09:36 UTC, sorawit commented on bridges/evm/contracts/mocks/BlockHeaderMerklePartsMock.sol
> +            BlockHeaderMerkleParts.getBlockHeader(
move it up one line

2020-04-27 03:54 UTC, taobun requested changes

2020-04-27 03:54 UTC, taobun commented on bridges/evm/contracts/BlockHeaderMerkleParts.sol
>  /// In Tendermint, a block header hash is the Merkle hash of a binary tree with 16 leaf nodes.
14, [A] app_hash

2020-04-28 03:10 UTC, taobun approved these changes

2020-04-28 06:41 UTC, sorawit approved these changes
looks good

2020-04-28 07:19 UTC, merged