Implement multi-store proof solidity library
bandprotocol/bandchain pull request #1434
Opened 2020-04-24 11:25 UTC by Benzbeeb

Fixed #1403

2020-04-26 07:18 UTC, taobun requested changes

2020-04-26 07:18 UTC, taobun commented on bridges/evm/contracts/MultiStore.sol
> +// [0] - acc     [1] - bank      [2] - capbility  [3] - distribution  [4] - evidence
capability

2020-04-26 07:18 UTC, taobun commented on bridges/evm/contracts/MultiStore.sol
> +                                    hex"066f7261636c6520", // oracle prefix
// oracle prefix (uint8(6) + "oracle" + uint8(32))

2020-04-29 04:18 UTC, sorawit requested changes

2020-04-29 04:18 UTC, sorawit commented on bridges/evm/contracts/MultiStore.sol
> +// Merkle hash on muliple stores. Luckily, we only care about "oracle" tree and all other
This is not true anymore. We are not that lucky. Please read comment before copy-pasting

2020-04-29 08:55 UTC, sorawit submitted a review, later dismissed

2020-04-29 09:20 UTC, taobun requested changes

2020-04-29 09:20 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +          "0x2B14E5AB19A88F23B3F6C694659374DF21E21935A7C0B8565C4E7B43AAB3BB43", // accToMainStoresMerkleHash
change all variable name

2020-04-29 09:20 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> -          ["0x652D89a66Eb4eA55366c45b1f9ACfc8e2179E1c5", 100],
Why remove this validator?

2020-04-29 09:20 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +          [
Invalid signature not missing signatures

2020-04-29 09:20 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +        [["0x88e1cd00710495EEB93D4f522d16bC8B87Cb00FE", 300]],
This address is a missing signature?

2020-04-29 10:05 UTC, Benzbeeb commented on bridges/evm/test/Bridge.test.js
> +        [["0x88e1cd00710495EEB93D4f522d16bC8B87Cb00FE", 300]],
ya

2020-04-29 10:15 UTC, taobun requested changes

2020-04-29 10:15 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +          "0xAA66B682A3FE96C372A095A43F2E73B33E89D835DB3BBF2496546328A7BD4961" // stakingToUpgradeStoresMerkleHash
StakingAndUpgradeStoresMerkleHash

2020-04-29 10:38 UTC, taobun requested changes

2020-04-29 10:38 UTC, taobun commented on bridges/evm/contracts/MultiStore.sol
> +        bytes32 StakingAndUpgradeStoresMerkleHash; // [I10]
camel Pls

2020-04-29 10:38 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +          "0xAA66B682A3FE96C372A095A43F2E73B33E89D835DB3BBF2496546328A7BD4961" // StakingAndUpgradeStoresMerkleHash
ditto

2020-04-29 10:38 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +              "0x62A900783D67A397A0CE36C82108122B97ACF88034CA917209937E2FF29EDB1C", // r
Please comment on what signature is wrong

2020-04-29 11:35 UTC, taobun submitted a review, later dismissed

2020-04-29 11:37 UTC, taobun approved these changes

2020-04-29 12:05 UTC, sorawit approved these changes

2020-04-29 12:18 UTC, merged