Modify verifyData receives packets instead of result data
bandprotocol/bandchain pull request #1450
Opened 2020-04-27 12:06 UTC by taobun

fixed #1405

2020-04-28 04:50 UTC, sorawit requested changes

2020-04-28 04:50 UTC, sorawit commented on bridges/evm/contracts/Bridge.sol
> +    /// @param _responsePacket The response packet of this request contain metadata of result.
Let's remove "contain...." part. Just say The request packet is this request, The response packet of this request.

2020-04-28 04:50 UTC, sorawit commented on bridges/evm/contracts/Packets.sol
> +                Utils.encodeVarintUnsigned(bytes(_self.clientId).length),
Why don't we use `getEncodeLength`?

2020-04-28 04:50 UTC, sorawit commented on bridges/evm/contracts/Packets.sol
> +                hex"79b5957c",
Explain it

2020-04-28 04:58 UTC, sorawit requested changes

2020-04-28 04:58 UTC, sorawit commented on bridges/evm/contracts/Packets.sol
> +                Utils.encodeVarintUnsigned(bytes(_self.params).length),
and here?

2020-04-28 10:23 UTC, sorawit approved these changes

2020-04-29 02:53 UTC, Benzbeeb approved these changes

2020-04-29 10:38 UTC, merged