chain/bandoracled2: initial hacky implementation
bandprotocol/bandchain pull request #1451
Opened 2020-04-27 12:55 UTC by sorawit

Initial hacky version of bandoracled. Improvements over v1
- Read raw data requests from events
- Use subscribe to get new tx. Not polling.

2020-05-01 08:12 UTC, taobun requested changes

2020-05-01 08:12 UTC, taobun commented on chain/cmd/bandoracled2/execute.go
> +	out, err := auth.NewTxBuilder(
Add TODO config gas limit and gas price

2020-05-01 08:12 UTC, taobun commented on chain/cmd/bandoracled2/execute.go
> +	fmt.Println("EZ", res)
Remove or log tx hash instead

2020-05-01 08:12 UTC, taobun commented on chain/cmd/bandoracled2/execute.go
> +		fmt.Println("ERR1", err)
Use logger

2020-05-01 08:12 UTC, taobun commented on chain/cmd/bandoracled2/handler.go
> +		dataSourceID, err := strconv.Atoi(dataSourceIDs[idx])
TODO: Make all of this to function and use go routine.

2020-05-05 13:24 UTC, taobun approved these changes

2020-05-06 03:03 UTC, Benzbeeb approved these changes

2020-05-06 03:23 UTC, merged