Re-implement band-consumer app in this repo
bandprotocol/bandchain pull request #1455
Opened 2020-04-28 03:56 UTC by Benzbeeb

Fixed #1407

2020-05-01 04:20 UTC, taobun requested changes

2020-05-01 04:20 UTC, taobun commented on band-consumer/Dockerfile
> +# Simple usage with a mounted data directory:
This is a good file to make an image for daemon and client. Just change gaiad -> bcd

2020-05-01 04:20 UTC, taobun commented on band-consumer/app/app_test.go
> +// // // ensure that black listed addresses are properly set in bank keeper
What?

2020-05-03 08:08 UTC, taobun requested changes
Can we also clean up some code at `chain/handler.go` follow how we handle packet in new cosmos-sdk-version

2020-05-03 08:08 UTC, taobun commented on band-consumer/app/app.go
> +	scopedIBCKeeper  capability.ScopedKeeper
If you want to keep scopedIBCKeeper, please keep scopedConsumingKeeper too

2020-05-03 08:08 UTC, taobun commented on band-consumer/app/app.go
> +		transfer.NewAppModule(app.transferKeeper),
transferModule

2020-05-03 08:08 UTC, taobun commented on band-consumer/app/app.go
> +		consuming.NewAppModule(app.consumingKeeper),
consumingModule

2020-05-03 08:08 UTC, taobun commented on chain/x/oracle/types/key.go
> +	PortKey  = ModuleName
Sorry for my hacky work

This is a [reference](https://github.com/cosmos/cosmos-sdk/blob/master/x/ibc/20-transfer/types/keys.go) for PortKey and PortID

2020-05-03 08:08 UTC, taobun commented on chain/x/oracle/module.go
> +	// TODO: escrow
Remove this todo not relevant to our module.

2020-05-03 08:08 UTC, taobun commented on chain/x/oracle/module.go
> +	// TODO: escrow
ditto

2020-05-03 08:08 UTC, taobun commented on chain/x/oracle/keeper/keeper.go
> +// TODO: Hack for use
// BindPort defines a wrapper function for the ort Keeper's function in
// order to expose it to module's InitGenesis function

2020-05-03 08:08 UTC, taobun commented on chain/x/oracle/genesis.go
> +	err := k.BindPort(ctx, types.PortKey)
After we changed `key.go` Use PortID instead of PortKey

2020-05-03 08:08 UTC, taobun commented on band-consumer/x/consuming/types/msgs.go
> +const RouterKey = ModuleName
Can you move it to `key.go`

2020-05-03 08:08 UTC, taobun commented on band-consumer/x/consuming/types/key.go
> +const (
Like oracle module please look at https://github.com/cosmos/cosmos-sdk/blob/master/x/ibc/20-transfer/types/keys.go as reference

2020-05-03 08:08 UTC, taobun commented on band-consumer/x/consuming/genesis.go
> +	err := k.BindPort(ctx, "consuming")
Use PortID instead

2020-05-03 08:08 UTC, taobun commented on band-consumer/x/consuming/handler.go
> +		case channeltypes.MsgPacket:
I think we can remove this case because it will be handled at module level

2020-05-03 08:08 UTC, taobun commented on band-consumer/x/consuming/keeper/keeper.go
> +// TODO: Hack for use
Use same comment at oracle BindPort

2020-05-15 08:37 UTC, sorawit approved these changes

2020-05-15 08:37 UTC, taobun approved these changes

2020-05-15 08:37 UTC, taobun commented on band-consumer/x/consuming/types/key.go
> +	// ModuleName defines the IBC transfer name
transfer???

2020-05-15 08:37 UTC, taobun commented on band-consumer/x/consuming/types/msgs.go
> +func (msg MsgRequestData) Type() string { return "consuming" }
request

2020-05-16 16:51 UTC, merged