scan: implement ui & wireup failed tx on tx index page
bandprotocol/bandchain pull request #1456
Opened 2020-04-28 05:31 UTC by tansawit

Fixes: #1322

2020-05-01 12:11 UTC, tansawit commented
I think we should wait until most message types are supported on scan and then restructure how we generally handle success/fail messages in this PR

2020-05-08 04:10 UTC, evilpeach requested changes

2020-05-08 04:10 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +  </Col>;
Duplicated?

2020-05-08 06:54 UTC, evilpeach requested changes
This doesn't match the design.
![image](https://user-images.githubusercontent.com/14128977/81379415-4712de80-9133-11ea-882f-70b5622fde8a.png)

2020-05-08 07:59 UTC, evilpeach approved these changes

2020-05-08 08:36 UTC, prin-r approved these changes

2020-05-08 08:36 UTC, merged