Scan: implement send delegate msg
bandprotocol/bandchain pull request #1460
Opened 2020-04-29 10:00 UTC by evilpeach

Fixes #1424

2020-04-29 10:31 UTC, tansawit commented on scan/src/components/modal/submitTx/DelegateMsg.re
> +      setInputData=setAmount
Change amount unit from uband to band

2020-04-29 11:08 UTC, tansawit requested changes

2020-04-29 11:08 UTC, tansawit commented on scan/src/components/modal/submitTx/SubmitTxModal.re
> +      // TODO: add gas, fee, memo when create tx later
Can we remove this comment now that we have those fields?

2020-04-29 11:08 UTC, tansawit commented on scan/src/components/modal/submitTx/DelegateMsg.re
> +    />
Change unit from uband to band

2020-04-29 12:48 UTC, evilpeach commented on scan/src/components/modal/submitTx/DelegateMsg.re
> +    />
I just change it to `uband` for now.

2020-04-30 02:17 UTC, sorawit requested changes

2020-04-30 02:17 UTC, sorawit commented on scan/src/components/modal/submitTx/DelegateMsg.re
> +  let (validator, setValidator) = React.useState(_ => EnhanceTxInput.{text: "", value: None});
Why dont we create `EnhanceTxInput.empty = {text: "", value: None}` so we can reuse?

2020-04-30 02:17 UTC, sorawit commented on scan/src/components/modal/submitTx/SubmitTxModal.re
> +        parse={newVal => {newVal->Js.String.length <= 20 ? Some(newVal) : None}}
Let's set maximum at 32.

2020-04-30 03:11 UTC, sorawit approved these changes

2020-04-30 03:20 UTC, tansawit approved these changes

2020-04-30 03:20 UTC, merged