scan: support deposit and submit proposal msgs
bandprotocol/bandchain pull request #1468
Opened 2020-04-30 13:40 UTC by tansawit

Fixes: #1310, #1311

2020-05-01 05:06 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-05-04 09:16 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-05-05 02:30 UTC, evilpeach requested changes

2020-05-05 02:30 UTC, evilpeach commented on scan/src/components/msgs/Msg.re
> +            amount->Belt_List.get(0)->Belt_Option.getWithDefault(Coin.newCoin("uband", 0.0)).
Why don't use helper function in `Coin.re`

2020-05-06 06:32 UTC, evilpeach approved these changes

2020-05-06 07:05 UTC, prin-r approved these changes

2020-05-06 07:05 UTC, merged