Scan: support python on data soruce script and unit test
bandprotocol/bandchain pull request #1484
Opened 2020-05-02 12:16 UTC by evilpeach

Fixes #1373

2020-05-04 13:24 UTC, sorawit requested changes

2020-05-04 13:24 UTC, sorawit commented on scan/src/utils/ExecutableParser.re
> +  switch (rawResult->Belt.Array.get(1)) {
Why don't you use `let%Opt`?

2020-05-05 03:52 UTC, sorawit approved these changes

2020-05-06 13:54 UTC, Benzbeeb approved these changes

2020-05-06 15:09 UTC, merged