Scan: disable connect with ledger btn while loading
bandprotocol/bandchain pull request #1502
Opened 2020-05-04 04:11 UTC by evilpeach

Fixes #1486

2020-05-04 04:36 UTC, prin-r requested changes

2020-05-04 04:36 UTC, prin-r commented on scan/src/components/ConnectWithLedger.re
> +      {result == Loading
There are two duplicate of "result == Loading"
Should it be reduced to just one?

2020-05-06 04:41 UTC, tansawit approved these changes

2020-05-06 06:24 UTC, prin-r approved these changes

2020-05-06 06:24 UTC, merged