scan: support vote msg
bandprotocol/bandchain pull request #1503
Opened 2020-05-04 04:35 UTC by tansawit

Fixes: #1312

2020-05-04 09:21 UTC, evilpeach requested changes
Please fix spacing on tx table on the account index page.

![image](https://user-images.githubusercontent.com/14128977/80952089-4d4b4700-8e23-11ea-8e7f-fbe8675bb90e.png)

2020-05-05 08:53 UTC, evilpeach submitted a review, later dismissed

2020-05-06 12:01 UTC, evilpeach approved these changes

2020-05-06 13:19 UTC, prin-r approved these changes

2020-05-06 13:19 UTC, merged