scan: support set withdraw address msgs
bandprotocol/bandchain pull request #1504
Opened 2020-05-04 04:45 UTC by tansawit

Fixes: #1315

2020-05-04 09:28 UTC, evilpeach requested changes

2020-05-04 09:28 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +      <Text value="DELEGATOR ADDRESS" size=Text.Sm weight=Text.Thin spacing={Text.Em(0.06)} />
This text isn't aligned to address. Let's add `line-height` around 16px.

2020-05-04 09:28 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +      <Text value="WITHDRAW ADDRESS" size=Text.Sm weight=Text.Thin spacing={Text.Em(0.06)} />
here as well

2020-05-05 04:20 UTC, prin-r approved these changes

2020-05-05 05:50 UTC, evilpeach approved these changes

2020-05-05 13:15 UTC, merged