scan: implement and wireup redelegate/withdraw reward msgs
bandprotocol/bandchain pull request #1508
Opened 2020-05-04 07:00 UTC by tansawit

Fixes: #1426, #1428

2020-05-05 04:05 UTC, evilpeach requested changes
The space between the button and the last field is too close. Let's decrease `padding-bottom` of modal's container.

2020-05-05 04:05 UTC, evilpeach commented on scan/src/components/modal/submitTx/RedelegateMsg.re
> +    (dstValidator, amount),
Let's use `React.useEffect3` for adding `srcValidator` as dependency.

2020-05-05 04:05 UTC, evilpeach commented on scan/src/components/modal/submitTx/WithdrawRewardMsg.re
> +    (validator, 0),
Let's use `React.useEffect1` for one dependency.

2020-05-05 06:48 UTC, evilpeach requested changes

2020-05-05 06:48 UTC, evilpeach commented on scan/src/components/modal/submitTx/WithdrawRewardMsg.re
> +    validator |> Belt.Array.make(1, _),
Why don't use `[| validator |]`

2020-05-05 12:44 UTC, evilpeach approved these changes
LGTM

2020-05-06 08:17 UTC, prin-r approved these changes

2020-05-06 08:24 UTC, merged