chain: Refactor SendOracleResponse out and improve request ibc flow
bandprotocol/bandchain pull request #1515
Opened 2020-05-05 03:57 UTC by sorawit

- Make SendOracleResponse not depend on request keeper at all. It just sends packets.
- Make sure expired requests get sent back to requester.
- Use error as result for failed requests.
- Merge NewRequest function into one.

2020-05-05 04:49 UTC, taobun requested changes

2020-05-05 04:49 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +func (k Keeper) ResolveRequest(
Can you add a comment to make this function more understandable?

2020-05-05 04:49 UTC, taobun commented on chain/x/oracle/endblock.go
> +		res = k.ResolveRequest(ctx, reqID, types.Failure, []byte(err.Error()))
Error has been used?

2020-05-05 13:53 UTC, taobun approved these changes

2020-05-05 13:55 UTC, sorawit commented on chain/x/oracle/endblock.go
> +		res = k.ResolveRequest(ctx, reqID, types.Failure, []byte(err.Error()))
Actually error should not be part of the consensus. I do want to allow Owasm to emit errors somehow though, but will save that for other diffs.

2020-05-05 13:55 UTC, sorawit commented on chain/x/oracle/keeper/request.go
> +func (k Keeper) ResolveRequest(
Yes can do.

2020-05-06 02:18 UTC, Benzbeeb approved these changes

2020-05-06 02:57 UTC, merged