chain: Reassign error codes to be incremental
bandprotocol/bandchain pull request #1522
Opened 2020-05-05 08:20 UTC by sorawit

2020-05-05 13:57 UTC, taobun requested changes

2020-05-05 13:57 UTC, taobun commented on chain/x/oracle/types/error.go
> +	ErrInvalidBasicMsg          = sdkerrors.Register(ModuleName, 1, "InvalidBasicMsg")
Change description

2020-05-07 02:58 UTC, taobun approved these changes

2020-05-07 03:43 UTC, Benzbeeb approved these changes

2020-05-07 05:55 UTC, merged