scan: support multisend msg
bandprotocol/bandchain pull request #1530
Opened 2020-05-06 04:34 UTC by tansawit

Fixes: #1306

2020-05-06 13:26 UTC, evilpeach requested changes

2020-05-06 13:26 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +        spacing={Text.Em([@reason.preserve_braces] 0.06)}
Why use `@reason.preserve_braces`?

2020-05-07 03:08 UTC, evilpeach approved these changes

2020-05-07 03:56 UTC, prin-r approved these changes

2020-05-07 03:57 UTC, prin-r requested changes
-

2020-05-07 04:04 UTC, evilpeach requested changes

2020-05-07 04:04 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +         <div>
add key

2020-05-07 04:04 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +         <div>
add key

2020-05-07 04:05 UTC, sorawit submitted a review, later dismissed

2020-05-07 04:05 UTC, sorawit commented on scan/src/components/TxIndexPageTable.re
> +      <Text value="NUMBER OF MESSAGES" size=Text.Sm weight=Text.Thin spacing={Text.Em(0.06)} />
Remove this thing

2020-05-07 04:05 UTC, sorawit commented on scan/src/components/msgs/Msg.re
> +    let firstTx = inputs |> Belt_List.get(_, 0) |> Belt_Option.getExn;
Use BeltList's getExn

2020-05-07 04:05 UTC, sorawit commented on scan/src/subscriptions/TxSub.re
> +      let firstTx = tx.inputs |> Belt_List.get(_, 0) |> Belt_Option.getExn;
Use BeltList's getExn

2020-05-07 06:54 UTC, evilpeach approved these changes

2020-05-07 09:49 UTC, prin-r approved these changes

2020-05-07 09:59 UTC, merged