Implement Msg parsing in TxHook
bandprotocol/bandchain pull request #157
Opened 2020-01-09 07:52 UTC by taobun

fixed #149

2020-01-09 08:05 UTC, sorawit requested changes

2020-01-09 08:05 UTC, sorawit commented on scan/src/App.re
> +    style([
Don't change this. Update line length to 100.

2020-01-09 08:05 UTC, sorawit commented on scan/src/rpc/TxHook.re
> +      amount: string,
Should be float. See `ValidatorHook.Validator.t`

2020-01-09 08:05 UTC, sorawit commented on scan/src/rpc/TxHook.re
> +      code: string,
codeHash?

2020-01-09 08:05 UTC, sorawit commented on scan/src/rpc/TxHook.re
> +        code: json |> field("Code", string),
Changed in #144?

2020-01-09 08:06 UTC, sorawit commented on scan/src/rpc/TxHook.re
> +      code: string,
Actually it's code. Nevermind.

2020-01-09 08:16 UTC, taobun commented on scan/src/rpc/TxHook.re
> +      code: string,
code si kub

2020-01-09 10:22 UTC, sorawit reviewed
@evilpeach

2020-01-09 11:16 UTC, sorawit requested changes

2020-01-09 11:16 UTC, sorawit commented on chain/cmd/request/main.go
> +	to, _ := sdk.AccAddressFromBech32("band13zmknvkq2sj920spz90g4r9zjan8g584x8qalj")
Remove this?

2020-01-10 04:07 UTC, taobun commented on chain/cmd/request/main.go
> +	to, _ := sdk.AccAddressFromBech32("band13zmknvkq2sj920spz90g4r9zjan8g584x8qalj")
It's example code, commented already

2020-01-10 04:09 UTC, evilpeach approved these changes
LGTM

2020-01-10 04:21 UTC, sorawit approved these changes

2020-01-10 04:24 UTC, merged