chain: Reduce number of module parameters by hardcoding sizing numbers
bandprotocol/bandchain pull request #1575
Opened 2020-05-10 08:28 UTC by sorawit

2020-05-11 09:49 UTC, taobun requested changes

2020-05-11 09:49 UTC, taobun commented on chain/x/oracle/keeper/raw_request.go
> +	// if err := k.EnsureLength(ctx, types.KeyMaxCalldataSize, len(data.Calldata)); err != nil {
Comment or deleted?

2020-05-12 04:55 UTC, sorawit commented on chain/x/oracle/keeper/raw_request.go
> +	// if err := k.EnsureLength(ctx, types.KeyMaxCalldataSize, len(data.Calldata)); err != nil {
Added comment!

2020-05-12 08:29 UTC, Benzbeeb submitted a review, later dismissed

2020-05-12 09:37 UTC, taobun requested changes

2020-05-12 09:37 UTC, taobun commented on chain/x/oracle/types/limits.go
> +	MaxSchemaLength      = 128
128 is too low 500 I think enough

2020-05-12 09:37 UTC, taobun commented on chain/x/oracle/types/params.go
>  	DefaultDescriptionLength = uint64(4096)
Delete this

2020-05-13 08:15 UTC, taobun submitted a review, later dismissed

2020-05-13 08:53 UTC, merged