1241 simple report uptime keeper
bandprotocol/bandchain pull request #1581
Opened 2020-05-12 01:54 UTC by taobun

fixed #1241

2020-05-12 04:52 UTC, sorawit requested changes

2020-05-12 04:52 UTC, sorawit commented on chain/x/oracle/types/params.go
> +	// Reported window size is 100
Change comment

2020-05-12 04:52 UTC, sorawit commented on chain/x/oracle/keeper/hooks.go
> +func (k Keeper) AfterValidatorBonded(ctx sdk.Context, _ sdk.ConsAddress, address sdk.ValAddress) {
Should we remove the second argument?

2020-05-12 04:52 UTC, sorawit commented on chain/x/oracle/keeper/hooks.go
> +func (h Hooks) AfterValidatorBonded(ctx sdk.Context, consAddr sdk.ConsAddress, valAddr sdk.ValAddress) {
Can we make the second argument `_`?

2020-05-14 03:12 UTC, sorawit requested changes

2020-05-14 03:12 UTC, sorawit commented on chain/x/oracle/keeper/hooks.go
> +func (k Keeper) AfterValidatorBonded(ctx sdk.Context, address sdk.ValAddress) {
Do we need this hook? Can we just create `ReportInfo` on demand? That way code becomes simpler.

2020-05-14 10:44 UTC, sorawit requested changes

2020-05-14 10:44 UTC, sorawit commented on chain/app/app.go
> +		stakingKeeper,
So I believe these changes are not necessary any more?

2020-05-14 15:32 UTC, sorawit requested changes

2020-05-14 15:32 UTC, sorawit commented on chain/x/oracle/genesis.go
> +		ReportInfos:   reportInfos,
Why is this on genesis state?

2020-05-14 15:32 UTC, sorawit commented on chain/x/oracle/keeper/infractions.go
> +	if err != nil {
While it's true that here we know that the only possible error is not found, assuming `err != nil` will always be that way is antipattern. We should use `k.HasValidatorReportInfo` in my opinion. Or make `GetValidatorReportInfoWithDefault` function that returns empty report info if not exist

2020-05-15 03:11 UTC, Benzbeeb requested changes

2020-05-15 03:11 UTC, Benzbeeb commented on chain/db/abci.go
> +
remove newline please

2020-05-15 03:11 UTC, Benzbeeb commented on chain/db/abci.go
> +
ditto

2020-05-16 14:14 UTC, sorawit requested changes

2020-05-16 14:14 UTC, sorawit commented on chain/x/oracle/keeper/report.go
> +	for ; iterator.Valid(); iterator.Next() {
Should we use `k.GetReports` here?

2020-05-16 17:10 UTC, sorawit approved these changes

2020-05-17 14:12 UTC, Benzbeeb approved these changes

2020-05-17 16:46 UTC, merged