chain/test: Add unit tests for filecache
bandprotocol/bandchain pull request #1591
Opened 2020-05-13 10:03 UTC by sorawit

2020-05-13 10:09 UTC, taobun requested changes

2020-05-13 10:09 UTC, taobun commented on chain/pkg/filecache/filecache_test.go
> +	filename := "b20727a9b7cc4198d8785b0ef1fa4c774eb9a360e1563dd4f095ddc7af02bd56" // Correct
Incorrect

2020-05-13 12:20 UTC, taobun approved these changes
Thanks for test!

2020-05-14 15:25 UTC, sorawit commented
@Benzbeeb please review

2020-05-15 03:26 UTC, Benzbeeb approved these changes

2020-05-15 06:13 UTC, merged