Scan: patch to support snake case, uptime
bandprotocol/bandchain pull request #1595
Opened 2020-05-13 16:53 UTC by evilpeach

Fixes #1554 Fixes #1555

2020-05-14 05:15 UTC, taobun requested changes

2020-05-14 05:15 UTC, taobun commented on scan/src/subscriptions/DataSourceSub.re
> +    name
indent?

2020-05-14 05:15 UTC, taobun commented on scan/src/subscriptions/TxSub.re
>        oracleScriptID: ID.OracleScript.t,
EditDataSource seem not to be fixed

2020-05-14 05:15 UTC, taobun commented on scan/src/wallet/TxCreator.re
> +  account_number: int,
Why does this field need to change?

2020-05-15 03:27 UTC, taobun requested changes

2020-05-15 03:27 UTC, taobun commented on scan/src/subscriptions/TxSub.re
> +        id: json |> field("oracle_script_id", ID.OracleScript.fromJson),
line 148 too

2020-05-15 04:10 UTC, taobun approved these changes

2020-05-15 05:22 UTC, tansawit approved these changes

2020-05-15 05:23 UTC, merged