chain: Implement do-not-modify for basic strings
bandprotocol/bandchain pull request #1598
Opened 2020-05-14 05:54 UTC by sorawit

2020-05-15 03:17 UTC, Benzbeeb submitted a review, later dismissed

2020-05-15 03:35 UTC, taobun requested changes

2020-05-15 03:35 UTC, taobun commented on chain/x/oracle/keeper/data_source_test.go
> +	id, err := k.AddDataSource(ctx, types.NewDataSource(
Why don't write `k.AddDataSource(ctx, dataSource1)`?

2020-05-15 03:35 UTC, taobun commented on chain/x/oracle/keeper/data_source_test.go
> +	err = k.EditDataSource(ctx, id, types.NewDataSource(
ditto

2020-05-15 03:35 UTC, taobun commented on chain/x/oracle/keeper/oracle_script_test.go
> +	id, err := k.AddOracleScript(ctx, types.NewOracleScript(
ditto

2020-05-15 03:35 UTC, taobun commented on chain/x/oracle/keeper/oracle_script_test.go
> +	err = k.EditOracleScript(ctx, id, types.NewOracleScript(
ditto

2020-05-17 10:26 UTC, taobun submitted a review, later dismissed

2020-05-17 13:02 UTC, merged