Implement get candidate size in bandrng
bandprotocol/bandchain pull request #1601
Opened 2020-05-14 08:19 UTC by Benzbeeb

2020-05-14 12:51 UTC, sorawit requested changes

2020-05-14 12:51 UTC, sorawit commented on chain/pkg/bandrng/sampling.go
> +	if totalRound <= 0 {
Let's remove this condition.

2020-05-14 12:51 UTC, sorawit commented on chain/pkg/bandrng/sampling.go
> +	if totalRound == 1 {
Change this condition to `currentRound == 0` for extra safety.

2020-05-14 12:51 UTC, sorawit commented on chain/pkg/bandrng/sampling_test.go
> +	for currentRound := 0; currentRound < totalRound; currentRound++ {
Let's spread this into multiple lines

2020-05-15 04:34 UTC, taobun requested changes

2020-05-15 04:34 UTC, taobun commented on chain/pkg/bandrng/sampling.go
> +		}
No need to check condition because `append(ws[:luckyNumber], ws[luckyNumber+1:]...)` equal to `ws[1:]` in case luckyNumber = 0.

2020-05-15 04:34 UTC, taobun commented on chain/pkg/bandrng/sampling.go
> +	ws := weights
use deep copy

2020-05-15 04:34 UTC, taobun commented on chain/pkg/bandrng/sampling_test.go
> +func TestChoosK(t *testing.T) {
ChooseK

2020-05-18 11:42 UTC, sorawit requested changes

2020-05-18 11:42 UTC, sorawit commented on chain/pkg/bandrng/sampling.go
> +	availableIndex := make([]int, len(weights))
weightValues
weightIndexes

2020-05-20 03:13 UTC, sorawit approved these changes

2020-05-20 12:16 UTC, taobun approved these changes

2020-05-20 12:32 UTC, merged