Implement show more tx msg
bandprotocol/bandchain pull request #1623
Opened 2020-05-15 09:03 UTC by tansawit

Fixes: #1557

2020-05-18 06:03 UTC, prin-r commented on scan/src/components/TxMessages.re
> +  // ReactDOMRe._getElementById("messageWrapper") |> Belt.Option.getExn;
please remove unused comment

2020-05-26 03:38 UTC, prin-r commented on scan/src/components/TxMessages.re
> +    <div id=divID className={Styles.msgContainer(overflowed)}>
please try useRef
https://reactjs.org/docs/hooks-reference.html#useref

2020-05-26 03:38 UTC, evilpeach requested changes

2020-05-26 03:38 UTC, evilpeach commented on scan/src/components/TxMessages.re
> +      alignItems(`center),
duplicated

2020-05-26 03:38 UTC, evilpeach commented on scan/src/components/TxMessages.re
> +         : <div> <Text value={"Error: " ++ rawLog} code=true size=Text.Sm breakAll=true /> </div>}
Remove unused `<div>`

2020-05-26 04:19 UTC, prin-r approved these changes

2020-05-26 04:25 UTC, evilpeach approved these changes

2020-05-26 04:25 UTC, merged