chain: Rename {Add/Remove}OracleAddress to {Add/Remove}Reporter
bandprotocol/bandchain pull request #1629
Opened 2020-05-16 03:27 UTC by sorawit

2020-05-17 12:17 UTC, Benzbeeb submitted a review, later dismissed

2020-05-17 16:41 UTC, taobun requested changes

2020-05-17 16:41 UTC, taobun commented on chain/x/oracle/client/cli/tx.go
> +// GetCmdAddReporter implements the adding of oracle address command handler.
reporter address?

2020-05-17 16:41 UTC, taobun commented on chain/x/oracle/client/cli/tx.go
> +// GetCmdRemoveReporter implements the Removing of oracle address command handler.
ditto

2020-05-18 02:10 UTC, sorawit commented on chain/x/oracle/client/cli/tx.go
> +// GetCmdAddReporter implements the adding of oracle address command handler.
I think naming it AddReporter is OK.

2020-05-19 03:50 UTC, taobun approved these changes

2020-05-19 03:51 UTC, merged