Using zipped file in create/edit data source and oracle script message
bandprotocol/bandchain pull request #1661
Opened 2020-05-18 07:16 UTC by Benzbeeb

Fixed #1525

2020-05-18 11:38 UTC, sorawit requested changes

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +func IsGzip(src []byte) bool {
Add comment.

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +// uncompress returns gzip uncompressed content or given src when not gzip.
update comment to match function name. Also the comment is not accurate.

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +	uncompressFile, err := ioutil.ReadAll(io.LimitReader(zr, maxSize+1))
uncompressed

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +		return nil, errors.New("uncompress file exeed maxsize")
typo

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +package oracle
This is not correct

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip_test.go
> +	require.NotNil(t, err)
require.Error

2020-05-18 11:38 UTC, sorawit commented on chain/pkg/gzip/gzip_test.go
> +	require.Nil(t, err)
require.NotError

2020-05-18 11:38 UTC, sorawit commented on chain/x/oracle/handler.go
> +	var executable []byte
I think we can just modify m.Executable directly.

2020-05-18 11:38 UTC, sorawit commented on chain/x/oracle/handler.go
> +			return nil, err
Please wrap the error with our custom error code

2020-05-19 02:23 UTC, Benzbeeb commented on chain/pkg/gzip/gzip_test.go
> +	require.Nil(t, err)
require don't have NotError

2020-05-19 02:35 UTC, Benzbeeb commented on chain/pkg/gzip/gzip_test.go
> +	require.Nil(t, err)
require doesn't have NotError

2020-05-19 03:45 UTC, sorawit requested changes

2020-05-19 03:45 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +// Uncompress returns gzip uncompressed.
Uncompress returns uncompressed gzip, or error if input is not gzipped or too large.

2020-05-19 03:45 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +func IsGzipped(src []byte) bool {
if the input is gzipped. (remove file)

2020-05-19 03:45 UTC, sorawit commented on chain/x/oracle/handler.go
> +		executable, err := gzip.Uncompress(m.Executable, types.MaxExecutableSize)
Declare a new error code

2020-05-19 03:45 UTC, taobun requested changes

2020-05-19 03:45 UTC, taobun commented on chain/pkg/gzip/gzip.go
> +		return uncompressed, errors.New("uncompressed file exceed maxSize")
Why not return nil?

2020-05-19 03:47 UTC, sorawit requested changes

2020-05-19 03:47 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +		return uncompressed, errors.New("uncompressed file exceed maxSize")
fmt.Errorf("Uncompressed file exceeds max size of %d", maxSize)

2020-05-21 03:05 UTC, sorawit submitted a review, later dismissed

2020-05-21 03:44 UTC, taobun requested changes

2020-05-21 03:44 UTC, taobun commented on chain/pkg/gzip/gzip.go
> +// IsGzip returns true if the input is gzipped. (remove file)
IsGzipped

2020-05-22 05:52 UTC, taobun submitted a review, later dismissed

2020-05-22 09:28 UTC, sorawit requested changes

2020-05-22 09:28 UTC, sorawit commented on chain/x/oracle/handler_test.go
> +func mockDataSourceWithGzipExcuteble(ctx sdk.Context, keeper Keeper) (*sdk.Result, error) {
Typo

2020-05-25 05:59 UTC, taobun submitted a review, later dismissed

2020-05-25 06:25 UTC, sorawit requested changes

2020-05-25 06:25 UTC, sorawit commented on chain/pkg/gzip/gzip.go
> +// IsGzipped returns true if the input is gzipped. (remove file)
Please fix comment

2020-05-25 06:25 UTC, sorawit commented on chain/x/oracle/handler.go
> +			return nil, err
Please wrap error here and all places below.

2020-05-25 07:13 UTC, sorawit requested changes

2020-05-25 07:13 UTC, sorawit commented on chain/x/oracle/handler.go
> +			return nil, sdkerrors.Wrapf(types.ErrUncompressionFailed, "file: %x", m.Executable)
Don't show the whole executable. Just show `err.Error()`

2020-05-25 12:10 UTC, sorawit approved these changes

2020-05-26 03:36 UTC, taobun approved these changes

2020-05-26 03:38 UTC, merged