scan: remove showing [do-not-modify]
bandprotocol/bandchain pull request #1662
Opened 2020-05-18 07:42 UTC by tansawit

Fixes: #1611

2020-05-29 09:24 UTC, evilpeach commented
@tansawit No need to make an address to option.

2020-06-05 02:12 UTC, evilpeach requested changes
It would be nice to make a helper function like
```
let checkDoNotModify = (x) => x == "[do-not-modify]"
```

2020-06-05 08:29 UTC, evilpeach submitted a review, later dismissed

2020-06-05 08:32 UTC, prin-r commented on scan/src/components/TxIndexPageTable.re
> +    // // </div>
Please remove comments
If you want to leave comments, please add reason with todo

2020-06-05 08:32 UTC, prin-r commented on scan/src/components/TxIndexPageTable.re
> +    // </div>
Please remove comments
If you want to leave comments, please add reason with todo

2020-06-05 08:36 UTC, evilpeach approved these changes

2020-06-05 08:36 UTC, prin-r approved these changes

2020-06-05 08:36 UTC, merged