oracled2: Ignore request not related to its validator
bandprotocol/bandchain pull request #1679
Opened 2020-05-19 13:12 UTC by perimeko

2020-05-19 13:15 UTC, sorawit requested changes

2020-05-19 13:15 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
>  	l.Info(":delivery_truck: Processing incoming request event")
Let's move this log to after the condition

2020-05-19 13:15 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +		return
Let's have a debug log here. Choose your own emoji!

2020-05-19 13:27 UTC, sorawit requested changes

2020-05-19 13:27 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +	validatorAddr := GetEventValues(log, otypes.EventTypeRequest, otypes.AttributeKeyValidator)
Let's name this `validators`

2020-05-19 13:27 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +	isFoundValidator := false
let's name thsi `hasMe`

2020-05-19 13:33 UTC, sorawit submitted a review, later dismissed
Looks great!

2020-05-20 03:22 UTC, taobun requested changes

2020-05-20 03:22 UTC, taobun commented on chain/cmd/bandoracled2/handler.go
> +			hasMe = true
Can break after found

2020-05-21 02:37 UTC, Benzbeeb approved these changes

2020-05-21 03:50 UTC, taobun approved these changes

2020-05-21 11:40 UTC, merged