oracled2: Gas prices configurable
bandprotocol/bandchain pull request #1681
Opened 2020-05-20 05:08 UTC by perimeko

2020-05-20 05:13 UTC, sorawit requested changes

2020-05-20 05:13 UTC, sorawit commented on chain/cmd/bandoracled2/run.go
> +	cmd.Flags().String(flags.FlagGasPrices, "", "gas prices")
gas prices for report transaction

2020-05-20 05:13 UTC, sorawit commented on chain/cmd/bandoracled2/run.go
> +			c.gasPrices = sdk.NewDecCoins(gasPrice)
Can we just use `sdk.ParseDecCoins(cfg.GasPrices)` directly?

2020-05-20 06:18 UTC, sorawit approved these changes

2020-05-21 02:36 UTC, Benzbeeb approved these changes

2020-05-21 03:36 UTC, taobun approved these changes

2020-05-21 05:53 UTC, merged