oracled2: use EnrichWithGas to estimate gas
bandprotocol/bandchain pull request #1684
Opened 2020-05-20 07:15 UTC by sorawit

2020-05-20 10:35 UTC, perimeko requested changes

2020-05-20 10:35 UTC, perimeko commented on chain/cmd/bandoracled2/execute.go
>  		1000000, 1, false, cfg.ChainID, "", sdk.NewCoins(), sdk.NewDecCoins(),
Can we set starting gas to zero?

2020-05-21 03:28 UTC, taobun submitted a review, later dismissed

2020-05-21 05:53 UTC, perimeko submitted a review, later dismissed

2020-05-21 11:47 UTC, merged