oracled2: Handle ibc packet
bandprotocol/bandchain pull request #1686
Opened 2020-05-20 13:28 UTC by perimeko

2020-05-20 15:13 UTC, sorawit requested changes

2020-05-20 15:13 UTC, sorawit commented on chain/x/oracle/types/events.go
> +	EventTypeMessage            = "message"
Let's not define new variables. Search for it in cosmos-sdk repo. For example:

```
➜  cosmos-sdk git:(master) ✗ git grep '= \"message\"' | cat
types/events.go:	EventTypeMessage = "message"
```

2020-05-20 15:13 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +			if err != nil {
If err not nil, that means it's not an oracle packet, which is totally ok. I think we should debug log that we skip non-request packet.

2020-05-20 15:13 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
>  			l.Debug(":ghost: Skipping non-request message type: %s", messageType)
We should update this log to skipping non-{request/packet} message type

2020-05-21 03:28 UTC, taobun requested changes

2020-05-21 03:28 UTC, taobun commented on chain/x/oracle/types/events.go
> +	MessageTypeOraclePacket = "ics04/opaque"
I think we don't need to declare these variable

2020-05-21 05:54 UTC, sorawit requested changes

2020-05-21 05:54 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +		if messageType == otypes.EventTypeRequest {
This should be matched again (MsgRequestData{}).Type

2020-05-21 05:54 UTC, sorawit commented on chain/cmd/bandoracled2/handler.go
> +				l.Debug(":ghost: Skipping non-request packet type: %s", messageType)
I don't think we need %s, messageType here. because it will always be ics/opaque

2020-05-21 05:54 UTC, sorawit commented on chain/x/oracle/types/events.go
> +	AttributeKeyAction         = "action"
Doesn't look right

2020-05-21 13:08 UTC, sorawit approved these changes

2020-05-22 05:51 UTC, taobun approved these changes

2020-05-22 08:02 UTC, merged