Log level
bandprotocol/bandchain pull request #1689
Opened 2020-05-21 08:36 UTC by perimeko

Fixed#1680

2020-05-21 10:24 UTC, sorawit requested changes

2020-05-21 10:24 UTC, sorawit commented on chain/cmd/bandoracled2/run.go
> +			logLevel := cfg.LogLevel
why do we need this temporary variable?

2020-05-22 05:41 UTC, sorawit approved these changes

2020-05-22 06:22 UTC, taobun approved these changes

2020-05-22 07:14 UTC, merged