Keeper to store and get code from file
bandprotocol/bandchain pull request #1704
Opened 2020-05-21 13:48 UTC by Benzbeeb

Fixed #1527

2020-05-21 13:53 UTC, sorawit approved these changes
lgtm

2020-05-21 14:30 UTC, sorawit requested changes
Test is failing. Please fix.

2020-05-22 09:31 UTC, sorawit approved these changes

2020-05-22 09:38 UTC, taobun approved these changes

2020-05-22 09:38 UTC, merged