Integrate sampling validator
bandprotocol/bandchain pull request #1707
Opened 2020-05-22 06:37 UTC by Benzbeeb

Fixed #1706

2020-05-22 07:25 UTC, taobun requested changes

2020-05-22 07:25 UTC, taobun commented on chain/x/oracle/keeper/request.go
> +	blockHash := ctx.BlockHeader().DataHash
Don't use data hash

2020-05-22 07:25 UTC, taobun commented on chain/x/oracle/keeper/request_test.go
> +	_, ctx, k := createTestInput()
Can you test by set block header of context after random will get validator different

2020-05-22 10:11 UTC, sorawit requested changes

2020-05-22 10:11 UTC, sorawit commented on chain/x/oracle/keeper/request.go
> +	seed := fmt.Sprintf("%x%d%d", ctx.BlockHeader().LastBlockId.Hash, ctx.BlockHeader().Time.Nanosecond(), nextReqID)
Add a separator. Let's do `:`

2020-05-25 05:05 UTC, sorawit approved these changes

2020-05-25 05:57 UTC, taobun approved these changes

2020-05-25 05:57 UTC, merged