oracled2: Allow user to configure external executor endpoint
bandprotocol/bandchain pull request #1709
Opened 2020-05-22 08:01 UTC by perimeko

Fixed #1687

2020-05-25 04:27 UTC, sorawit requested changes

2020-05-25 04:27 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
>  		exec, timeout, arg,
nit: Let's pack all these into online now that the arguments are quite short.

2020-05-25 04:27 UTC, sorawit commented on chain/cmd/bandoracled2/run.go
> +			c.executor, err = NewExecutor(executorName, executorURL)
This assumes that all executor strings always have two parts: the name and the URL, which is likely not always the case. I think we can just have `NewExecutor` function just takes `cfg.Executor` directly.

2020-05-25 04:27 UTC, sorawit commented on chain/cmd/bandoracled2/run.go
> +	cmd.Flags().String(flagExecutor, "lambda:https://dmptasv4j8.execute-api.ap-southeast-1.amazonaws.com/bash-execute", "executor")
Please have a more descriptive description.

2020-05-25 06:01 UTC, sorawit requested changes

2020-05-25 06:01 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +func NewExecutor(executer string) (executor, error) {
typo: executor.

2020-05-25 06:01 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +func ParseExecutor(executorStr string) (name string, url string, err error) {
This function can now be private (lowercase) now that it's not intended to be used outside.

2020-05-25 06:01 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +// ParseExecutor returns parsed executor string
parseExecutor splits the executor string in the form of "name:url" into parts.

2020-05-25 07:29 UTC, sorawit requested changes

2020-05-25 07:29 UTC, sorawit commented on chain/cmd/bandoracled2/main.go
> +	Executor  string `mapstructure:"executor"`   // Executer name and Executor URL (example: "Executor name:URL")
typo

2020-05-25 07:29 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +// NewExecutor returns executor by name and executer URL
typo.

2020-05-25 07:56 UTC, sorawit approved these changes

2020-05-26 03:42 UTC, taobun approved these changes

2020-05-26 03:43 UTC, merged