Simapp for common test
bandprotocol/bandchain pull request #1740
Opened 2020-05-24 07:54 UTC by taobun

fixed #1357

2020-05-25 04:21 UTC, sorawit requested changes

2020-05-25 04:21 UTC, sorawit commented on chain/simapp/app.go
> +	// Funds all the seed Accounts with 1000000uband initially.
This doesn't seem accurate anymore?

2020-05-25 04:21 UTC, sorawit commented on chain/simapp/app.go
> +	// ctx := app.BaseApp.NewContext(false, abci.Header{})
Let's remove this line if it's not used anymore.

2020-05-25 04:21 UTC, sorawit commented on chain/x/oracle/keeper/common_test.go
> +		sdk.AccAddress([]byte("owner")),
Let's not use this fake address. It will likely cause problems down the line.

2020-05-25 04:21 UTC, sorawit commented on chain/x/oracle/keeper/common_test.go
> +		sdk.AccAddress([]byte("owner")),
ditto

2020-05-25 09:04 UTC, Benzbeeb approved these changes

2020-05-26 03:08 UTC, sorawit approved these changes

2020-05-26 03:08 UTC, merged