Revisit exec env types test
bandprotocol/bandchain pull request #1756
Opened 2020-05-26 03:22 UTC by Benzbeeb

Fixed #1694

2020-05-26 03:24 UTC, sorawit requested changes

2020-05-26 03:24 UTC, sorawit commented on chain/x/oracle/types/exec_env_test.go
> +	validatorAddress1 := sdk.ValAddress([]byte("val1"))
Don't use arbitrary val address like this. Please use valid 20 bytes.

2020-05-26 03:24 UTC, sorawit commented on chain/x/oracle/types/exec_env_test.go
> +	ibcInfo := types.IBCInfo{SourcePort: "source_port", SourceChannel: "source_channel"}
NewIBCInfo

2020-05-26 03:24 UTC, sorawit commented on chain/x/oracle/types/exec_env_test.go
> +	require.Equal(t, []byte(sdk.ValAddress([]byte("val1"))), valAddrs)
ditto

2020-05-26 03:26 UTC, sorawit requested changes

2020-05-26 03:26 UTC, sorawit commented on chain/x/oracle/types/exec_env_test.go
> +	cleintID := "beeb"
typo

2020-05-29 05:00 UTC, taobun requested changes

2020-05-29 05:00 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +func MockPreparedExecEnv() *types.ExecEnv {
mockPreparedExecEnv

2020-05-29 05:00 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +func MockExecEnv() *types.ExecEnv {
Rename to mockExecutionEnv

2020-05-29 05:00 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +
Add mockFreshEnv using to prepare test

2020-05-29 13:19 UTC, taobun requested changes

2020-05-29 13:19 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +
For test RequestExternalData functions

2020-05-30 16:08 UTC, sorawit submitted a review, later dismissed

2020-06-02 01:50 UTC, taobun requested changes

2020-06-02 01:50 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +package types_test
I think we can use package types

2020-06-02 01:50 UTC, taobun commented on chain/x/oracle/types/exec_env_test.go
> +
Remove endline and bring our import to bottom.

2020-06-16 07:51 UTC, Benzbeeb commented
I’m closing this pull request because of outdated code. Now we have go-owasm.([link](https://github.com/bandprotocol/bandchain/pull/1858))

2020-06-16 07:51 UTC, closed without merging