oracled2: Bandchain script
bandprotocol/bandchain pull request #1757
Opened 2020-05-26 04:06 UTC by perimeko

fixed 1688

2020-05-26 09:53 UTC, taobun requested changes

2020-05-26 09:53 UTC, taobun commented on chain/scripts/start_bandd.sh
> +go test ./...
I think these codes are not a part of a deployment.

2020-05-26 09:53 UTC, taobun commented on chain/scripts/start_bandd.sh
> +    | bandcli keys add validator --recover --keyring-backend test  --coin-type 494
Remove coin-type

2020-05-26 09:53 UTC, taobun commented on chain/scripts/start_bandd.sh
> +    | bandcli keys add requester --recover --keyring-backend test  --coin-type 494
ditto

2020-05-27 04:26 UTC, taobun approved these changes

2020-05-27 04:26 UTC, taobun commented on chain/cmd/bandoracled2/README.md
> +cd cd ../../../chain
cd

2020-05-27 04:27 UTC, taobun requested changes

2020-05-27 04:27 UTC, taobun commented on chain/scripts/start_bandd.sh
> +go test ./...
Remove this

2020-05-27 05:00 UTC, taobun approved these changes

2020-05-27 06:59 UTC, sorawit approved these changes

2020-05-27 07:12 UTC, merged