Handler test for MsgCreate/Edit DataSource
bandprotocol/bandchain pull request #1768
Opened 2020-05-26 11:48 UTC by Benzbeeb

Fixed #1696

2020-05-26 13:58 UTC, sorawit requested changes

2020-05-26 13:58 UTC, sorawit commented on chain/x/oracle/handler_test.go
>  // func TestEditDataSourceByNotOwner(t *testing.T) {
Let's remove this code

2020-05-26 13:58 UTC, sorawit commented on chain/x/oracle/handler_test.go
>  // func mockOracleScript(ctx sdk.Context, keeper Keeper) (*sdk.Result, error) {
Let's remove it not used

2020-05-26 14:04 UTC, sorawit submitted a review, later dismissed

2020-05-26 14:04 UTC, Benzbeeb commented on chain/x/oracle/handler_test.go
>  // func mockOracleScript(ctx sdk.Context, keeper Keeper) (*sdk.Result, error) {
Will remove in #1712

2020-05-27 03:49 UTC, taobun requested changes

2020-05-27 03:49 UTC, taobun commented on chain/x/oracle/handler_test.go
> +func deleteFile(data []byte) {
Move to common_test

2020-05-27 09:50 UTC, merged