Add obi.js (LE version)
bandprotocol/bandchain pull request #1772
Opened 2020-05-26 13:01 UTC by smiled0g

2020-05-26 13:15 UTC, smiled0g commented
@sorawit Added BE to choose from under `ObiInteger`

2020-05-29 09:04 UTC, tansawit requested changes

2020-05-29 09:04 UTC, tansawit commented on obi/obi.js/index.js
> +  }
should this now be `encodeBE` + remove TODO?

2020-05-29 09:04 UTC, tansawit commented on obi/obi.js/index.js
> +  }
ditto

2020-05-29 09:04 UTC, tansawit commented on obi/obi.js/index.js
> +  }
simplify this to
```js
encodeBE(value) {
	return encodeLE(value).reverse()
}
```

2020-05-29 09:04 UTC, tansawit commented on obi/obi.js/test.js
> +  )
This test case will need to be updated when switching number encoding to Big Endian

2020-05-29 09:04 UTC, tansawit commented on obi/obi.js/test.js
> +})()
update this test case as well

2020-05-31 09:01 UTC, tansawit commented on obi/obi.js/package.json
>    }
Should we remove `prettier` as the library doesn't need it?

2020-06-01 04:39 UTC, tansawit approved these changes

2020-06-04 13:20 UTC, evilpeach approved these changes

2020-06-04 13:23 UTC, merged