chain: hotfix request count key
bandprotocol/bandchain pull request #1774
Opened 2020-05-27 03:59 UTC by sorawit

2020-05-27 13:23 UTC, taobun requested changes

2020-05-27 13:23 UTC, taobun commented on chain/x/oracle/genesis.go
> +	k.SetParam(ctx, types.KeyMaxDataSourceCount, data.Params.MaxDataSourceCount)
We can use same data sources for different raw requests.

2020-05-27 13:26 UTC, sorawit commented on chain/x/oracle/genesis.go
> +	k.SetParam(ctx, types.KeyMaxDataSourceCount, data.Params.MaxDataSourceCount)
Change the name back. Thanks!

2020-05-29 02:13 UTC, sorawit commented
@taobun @Benzbeeb Please get this in

2020-05-29 04:36 UTC, Benzbeeb approved these changes

2020-05-29 06:32 UTC, taobun approved these changes

2020-05-29 06:32 UTC, merged