Request keeper test 100%!!
bandprotocol/bandchain pull request #1776
Opened 2020-05-27 07:19 UTC by Benzbeeb

Fixed #1712

2020-05-29 02:25 UTC, sorawit requested changes

2020-05-29 02:25 UTC, sorawit commented on chain/x/oracle/keeper/request_test.go
> +	_, ctx, k := createTestInput()
Please comment explain the test situation.

2020-05-29 09:23 UTC, sorawit requested changes

2020-05-29 09:23 UTC, sorawit commented on chain/x/oracle/keeper/request_test.go
> +func TestProcessExpiredRequestsNoRequestInStore(t *testing.T) {
Please iterate through store and check if the number of elements are the same

2020-06-02 11:20 UTC, taobun requested changes

2020-06-02 11:20 UTC, taobun commented on chain/x/oracle/keeper/request_test.go
> +	k.AddReport(ctx, id2, rep)
Test expired request

2020-06-02 13:08 UTC, taobun requested changes

2020-06-02 13:08 UTC, taobun commented on chain/x/oracle/keeper/request_test.go
> +	require.Equal(t, clientID, res.ClientID)
Combine in 1 packet.

2020-06-02 13:08 UTC, taobun commented on chain/x/oracle/keeper/request_test.go
> +
Get result of expired request it must have result in store.

2020-06-04 03:25 UTC, taobun requested changes

2020-06-04 03:25 UTC, taobun commented on chain/x/oracle/keeper/request_test.go
> +	res, err := k.GetResult(ctx, id1)
Can add comment to explain what you tested

2020-06-16 07:51 UTC, Benzbeeb commented
I’m closing this pull request because of outdated code. Now we have go-owasm.([link](https://github.com/bandprotocol/bandchain/pull/1858))

2020-06-16 07:51 UTC, closed without merging