chain/querier: Refactor querier codebase
bandprotocol/bandchain pull request #1784
Opened 2020-05-27 12:41 UTC by sorawit

2020-05-27 16:03 UTC, taobun requested changes

2020-05-27 16:03 UTC, taobun commented on chain/x/oracle/client/cli/query.go
> +// GetCmdDataSource implements the query data source command.
What input of this cli id or hash? We can explain or show an example in long description.
(https://github.com/cosmos/cosmos-sdk/blob/master/x/staking/client/cli/tx.go)

2020-05-27 16:03 UTC, taobun commented on chain/x/oracle/types/querier.go
> +	QueryDataSources   = "data_sources"
We want to query single data source?

2020-05-27 16:03 UTC, taobun commented on chain/x/oracle/client/rest/rest.go
> +	r.HandleFunc(fmt.Sprintf("/%s/data_sources/{%s}", storeName, dataSourceIDTag), getDataSourceByIDHandler(cliCtx, storeName)).Methods("GET")
data_source?

2020-05-29 02:53 UTC, sorawit commented on chain/x/oracle/client/cli/query.go
> +// GetCmdDataSource implements the query data source command.
I don't think we need long desc. I'll fix short desc to be more understandable.

2020-05-29 02:53 UTC, sorawit commented on chain/x/oracle/types/querier.go
> +	QueryDataSources   = "data_sources"
Let's follow REST convention

2020-05-29 11:44 UTC, taobun approved these changes

2020-05-31 05:54 UTC, taobun commented
@perimeko please review this pr

2020-06-01 04:34 UTC, perimeko approved these changes

2020-06-01 04:37 UTC, merged