chain: Request data message handler test
bandprotocol/bandchain pull request #1792
Opened 2020-05-28 04:56 UTC by perimeko

Fixed #1698

2020-05-28 08:47 UTC, taobun requested changes

2020-05-28 08:47 UTC, taobun commented on chain/x/oracle/handler_test.go
> +	for reqID := 1; reqID <= 3; reqID++ {
Use i is better reqID that misleading to request id but it doesn't

2020-05-29 14:10 UTC, taobun submitted a review, later dismissed

2020-05-30 16:10 UTC, sorawit commented
@perimeko Please resolve conflict. Likely a small conflict with #1793

2020-06-02 12:27 UTC, taobun submitted a review, later dismissed

2020-06-02 13:38 UTC, Benzbeeb submitted a review, later dismissed

2020-06-04 09:23 UTC, Benzbeeb submitted a review, later dismissed
💯

2020-06-04 10:03 UTC, taobun approved these changes

2020-06-04 10:04 UTC, Benzbeeb approved these changes
⛓️ 💯

2020-06-04 10:04 UTC, sorawit approved these changes

2020-06-04 10:05 UTC, merged