chain: Add and remove reporter handler test
bandprotocol/bandchain pull request #1793
Opened 2020-05-28 07:37 UTC by perimeko

Fixed: #1699

2020-05-28 10:06 UTC, Benzbeeb requested changes

2020-05-28 10:06 UTC, Benzbeeb commented on chain/x/oracle/handler_test.go
> +	// Should fail, bob isn't alice validator's reporter
Bob 💯

2020-05-29 02:34 UTC, sorawit requested changes

2020-05-29 02:34 UTC, sorawit commented on chain/x/oracle/keeper/reporter.go
> +// IsReporter returns true if the address is an authorized reporter for the given validator.
leave it as iff. It's more correct (:

2020-05-29 14:30 UTC, sorawit approved these changes

2020-05-30 14:11 UTC, Benzbeeb approved these changes

2020-05-30 16:09 UTC, merged