scan: removed input field for unused oracle script input
bandprotocol/bandchain pull request #1797
Opened 2020-05-28 12:49 UTC by tansawit

2020-05-28 13:25 UTC, prin-r submitted a review, later dismissed

2020-05-28 14:21 UTC, prin-r submitted a review, later dismissed

2020-05-29 02:49 UTC, sorawit requested changes

2020-05-29 02:49 UTC, sorawit commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +    let (isUnused, setIsUnused) = React.useState(_ => false);
Why do you need state here?

2020-05-29 03:16 UTC, prin-r commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +      if (isUnused) {
can we move the condition here ?

2020-05-29 03:17 UTC, prin-r commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +    let isUnused = {
move condition in to useEffect

2020-05-29 03:21 UTC, prin-r approved these changes

2020-05-29 08:32 UTC, merged