Scan: add warning unboning count
bandprotocol/bandchain pull request #1807
Opened 2020-05-29 08:07 UTC by evilpeach

- add a warning when the user has reached the unbending count limit.
- disable unbending btn if reach.
@sorawit Is it proper to show?

2020-05-29 10:18 UTC, tansawit approved these changes

2020-06-01 07:41 UTC, sorawit requested changes

2020-06-01 07:41 UTC, sorawit commented on scan/src/components/modal/ValidatorStakingInfo.re
> +                 <Text value="Warning: You have reached the unbonding count. (7 times)" />
You can have the maximum of 7 pending delegation unbonding entries.

2020-06-01 07:43 UTC, tansawit requested changes

2020-06-01 07:43 UTC, tansawit commented on scan/src/components/modal/ValidatorStakingInfo.re
> +                 <Text value="Warning: You have reached the unbonding count. (7 times)" />
Change to "Warning: You have reached the maximum number (7) of pending unbonding actions"

2020-06-01 11:16 UTC, sorawit approved these changes

2020-06-02 11:09 UTC, tansawit approved these changes

2020-06-02 11:12 UTC, merged