Scan: Not found placeholder on Tx Index
bandprotocol/bandchain pull request #1808
Opened 2020-05-29 09:40 UTC by evilpeach

![image](https://user-images.githubusercontent.com/14128977/83245528-0c98e080-a1cb-11ea-9a53-1d6bb1399e9f.png)

2020-05-29 10:21 UTC, tansawit requested changes

2020-05-29 10:21 UTC, tansawit commented on scan/src/pages/TxIndexPage.re
> +          value="Note that: If you have just submitted a transaction please wait for at least 5-10 seconds."
Change to "Note: Transactions usually take 5-10 seconds to appear"

2020-05-29 10:21 UTC, tansawit commented on scan/src/pages/TxIndexPage.re
> +          value="Sorry, We are unable to locate this TxnHash"
Change to "Sorry, we are unable to retrieve information on this transaction hash"

2020-05-29 11:52 UTC, tansawit approved these changes

2020-05-31 18:32 UTC, prin-r approved these changes

2020-05-31 18:32 UTC, merged