Open Handler test for MsgCreate/Edit Oracle script
bandprotocol/bandchain pull request #1811
Opened 2020-05-29 13:57 UTC by Benzbeeb

Fixed #1697

2020-05-30 16:11 UTC, sorawit requested changes

2020-05-30 16:11 UTC, sorawit commented on chain/x/oracle/keeper/oracle_script.go
> +	oracleScript, err := k.GetOracleScript(ctx, id)
Let's remove `EditOracleScript` since it's not used anymore.

2020-06-02 04:43 UTC, taobun requested changes

2020-06-02 04:43 UTC, taobun commented on chain/x/oracle/keeper/oracle_script.go
> +// EditOracleScript edits the given oracle script by id and flushes it to the storage. Panic if not exists.
Fix comment to match this function behavior

2020-06-02 04:43 UTC, taobun commented on chain/x/oracle/handler_test.go
> +	require.Nil(t, err)
require.NoError

2020-06-02 04:43 UTC, taobun commented on chain/x/oracle/handler_test.go
> +	require.Nil(t, err)
ditto

2020-06-02 11:12 UTC, taobun submitted a review, later dismissed

2020-06-02 11:14 UTC, sorawit requested changes

2020-06-02 11:14 UTC, sorawit commented on chain/x/oracle/keeper/oracle_script.go
>  	oracleScript, err := k.GetOracleScript(ctx, id)
MustGet

2020-06-04 03:08 UTC, taobun approved these changes

2020-06-04 03:17 UTC, sorawit approved these changes

2020-06-04 03:21 UTC, merged