oracled2: Get executable content from bandchain querier
bandprotocol/bandchain pull request #1843
Opened 2020-06-01 07:29 UTC by perimeko

Fixed: #1786

2020-06-01 11:15 UTC, sorawit requested changes
Can you also update your script instruction to not run rest-server anymore?

2020-06-01 13:45 UTC, sorawit submitted a review, later dismissed
This is great!

2020-06-02 03:31 UTC, taobun requested changes

2020-06-02 03:31 UTC, taobun commented on chain/cmd/bandoracled2/execute.go
> +	cliCtx := sdkCtx.CLIContext{Client: c.client}
Try using c.client.ABCIQueryWithOptions(path, nil, rpcclient.ABCIQueryOptions{})

2020-06-02 12:22 UTC, taobun approved these changes

2020-06-02 13:37 UTC, sorawit approved these changes

2020-06-02 13:49 UTC, merged