scan: added loading state to validator index page
bandprotocol/bandchain pull request #1854
Opened 2020-06-03 11:20 UTC by tansawit

Fixes: #1564

2020-06-05 02:07 UTC, evilpeach requested changes

2020-06-05 02:07 UTC, evilpeach commented on scan/src/components/validator/ProposedBlocksTable.re
> +               <BlocksTable blocks />
Should `<TableHeader>` place outside of blocksSub ?

2020-06-05 02:07 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +               ->React.array}
add key

2020-06-05 02:07 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +               ->Belt_Array.map(externalDataID => {
add key

2020-06-05 02:07 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +               ->Belt_Array.map(value => {
add key

2020-06-05 02:07 UTC, evilpeach commented on scan/src/components/validator/DelegatorsTable.re
> +                    <TBody>
add key?

2020-06-12 04:00 UTC, evilpeach commented
@tansawit Please fix conflict.

2020-06-14 08:02 UTC, evilpeach requested changes
Please fix 
1) ![image](https://user-images.githubusercontent.com/14128977/84588198-6c3fee80-ae4f-11ea-8c78-e2fcfa8b91c6.png)

2) ![image](https://user-images.githubusercontent.com/14128977/84588250-0b64e600-ae50-11ea-86ab-13263cb9d622.png)

2020-06-23 12:57 UTC, evilpeach approved these changes

2020-06-23 12:58 UTC, prin-r approved these changes

2020-06-23 13:02 UTC, merged