Scan: implement sorting on validator home
bandprotocol/bandchain pull request #1856
Opened 2020-06-03 18:59 UTC by evilpeach

Fixes #1614

2020-06-04 03:13 UTC, sorawit requested changes

2020-06-04 03:13 UTC, sorawit commented on scan/src/pages/ValidatorHomePage.re
> +      | NameAsc =>
Let's make this stable sort. If the property is equal, we just compare voting power. If voting power is equal we compare moniker.

2020-06-09 04:23 UTC, sorawit approved these changes

2020-06-09 04:24 UTC, prin-r approved these changes

2020-06-09 04:24 UTC, merged