Owasm executor on google cloud function
bandprotocol/bandchain pull request #1872
Opened 2020-06-04 14:20 UTC by perimeko

Fixed #1825

2020-06-08 07:58 UTC, sorawit requested changes

2020-06-08 07:58 UTC, sorawit commented on cloud-function/google_cloud_function.py
> +        timeout_millisec = request_json["timeout"]
Can't we use `request.timeout`?

2020-06-08 07:58 UTC, sorawit commented on cloud-function/google_cloud_function.py
> +            env=env,
Don't think we need to pass env

2020-06-08 07:58 UTC, sorawit commented on cloud-function/google_cloud_function.py
> +        return (
Can we create a helper function `success(returncode="", stdout="", stderr="", err="")` so we don't repeat `jsonify(...), 200` everywhere?

2020-06-09 15:30 UTC, taobun requested changes

2020-06-09 15:30 UTC, taobun commented on CHANGELOG.md
> +- (feat) [\#1872](https://github.com/bandprotocol/bandchain/pull/1872) Add Owasm executor on Google Cloud function
I think this PR must be in chain not owasm or open new tag `executor`.

2020-06-09 15:30 UTC, taobun commented on cloud-function/google_cloud_function.py
> +
Remove endline

2020-06-09 15:30 UTC, taobun commented on cloud-function/google_cloud_function.py
> +
ditto

2020-06-09 15:30 UTC, taobun commented on cloud-function/google_cloud_function.py
> +
ditto

2020-06-09 15:30 UTC, taobun commented on cloud-function/main_test.py
> +def test_error_calldata_empty(mock_env):
Why this test is test_error?

2020-06-09 15:30 UTC, taobun commented on cloud-function/main_test.py
> +            }  # timeout shouldn't be string
Remove comment

2020-06-12 03:50 UTC, taobun approved these changes

2020-06-12 03:59 UTC, sorawit requested changes

2020-06-12 03:59 UTC, sorawit commented on cloud-function/google_cloud_function.py
> +    loaded_request = ""
This is not needed.

2020-06-12 03:59 UTC, sorawit commented on cloud-function/google_cloud_function.py
> +        f.write(loaded_request.get("executable"))
Can we do `loaded_request.executable`

2020-06-12 07:35 UTC, sorawit approved these changes

2020-06-12 10:44 UTC, merged