Make sure bandoracled cache data source content
bandprotocol/bandchain pull request #1874
Opened 2020-06-05 04:14 UTC by Benzbeeb

Fixed #1753

2020-06-05 06:32 UTC, taobun requested changes

2020-06-05 06:32 UTC, taobun commented on chain/cmd/bandoracled2/context.go
> +	"github.com/bandprotocol/bandchain/chain/pkg/filecache"
Let's move to the bottom of import.

2020-06-05 06:32 UTC, taobun commented on chain/cmd/bandoracled2/run.go
> +	"github.com/bandprotocol/bandchain/chain/pkg/filecache"
ditto

2020-06-05 09:24 UTC, taobun submitted a review, later dismissed

2020-06-05 10:58 UTC, sorawit submitted a review, later dismissed
looks good.

2020-06-05 11:00 UTC, sorawit submitted a review, later dismissed

2020-06-10 03:18 UTC, taobun submitted a review, later dismissed

2020-06-10 03:18 UTC, sorawit submitted a review, later dismissed

2020-06-10 03:21 UTC, sorawit approved these changes

2020-06-10 03:21 UTC, taobun approved these changes

2020-06-10 03:23 UTC, merged