Scan: 1819 binding obi.js
bandprotocol/bandchain pull request #1888
Opened 2020-06-06 11:48 UTC by evilpeach

Fixes #1819 

- patch `obi.js` for publishing
- binding `obi.js`
- unit test

2020-06-08 04:45 UTC, smiled0g commented on obi/obi.js/package.json
> +    "@babel/cli": "^7.10.1",
Add `lodash` here

2020-06-08 14:38 UTC, prin-r submitted a review, later dismissed

2020-06-09 03:09 UTC, tansawit requested changes

2020-06-09 03:09 UTC, tansawit commented on CHANGELOG.md
> +- (feat) [\#1888](https://github.com/bandprotocol/bandchain/pull/1888) Binding Obi.js
Please elaborate. For example "Added OBI bindings and patched scan to use OBI standard"

2020-06-09 03:09 UTC, tansawit commented on scan/src/bindings/Obi.re
> +    console.log(schema, t)
Should we remove this log?

2020-06-09 04:14 UTC, tansawit submitted a review, later dismissed

2020-06-09 05:52 UTC, prin-r submitted a review, later dismissed

2020-06-09 05:54 UTC, prin-r approved these changes

2020-06-09 06:29 UTC, tansawit approved these changes

2020-06-09 06:29 UTC, merged