Rewrite execution environment
bandprotocol/bandchain pull request #1892
Opened 2020-06-07 11:19 UTC by taobun

2020-06-07 13:42 UTC, sorawit requested changes

2020-06-07 13:42 UTC, sorawit commented on chain/x/oracle/types/exec_env.go
>  	if int64(len(data)) > MaxRawRequestDataSize {
In that case, should we panic here?

2020-06-18 15:08 UTC, sorawit requested changes

2020-06-18 15:08 UTC, sorawit commented on go-owasm/api/bindings.h
> +  Error_SetReturnDataWrongPeriodError = 31,
Let's start this from 128

2020-06-18 15:08 UTC, sorawit commented on go-owasm/api/env.go
> +		if err == ErrSetReturnDataWrongPeriod {
Let's have parseError function that takes care of all these comparisons.

2020-06-18 15:08 UTC, sorawit commented on go-owasm/cbindgen.toml
> + header = "/* (c) 2020 Bandprotocol. Licensed under Apache-2.0 */"
Band Protocol

2020-06-18 15:08 UTC, sorawit commented on go-owasm/src/error.rs
> +  SetReturnDataWrongPeriodError = 31,
128

2020-06-19 09:53 UTC, Benzbeeb approved these changes

2020-06-19 10:10 UTC, sorawit approved these changes

2020-06-19 10:10 UTC, sorawit commented on go-owasm/src/span.rs
> +    pub fn create_writable(ptr: *mut u8, cap: usize) -> Span {
Can we add unit tests?

2020-06-19 10:11 UTC, merged