Store result in store instead of result hash
bandprotocol/bandchain pull request #1903
Opened 2020-06-08 08:57 UTC by Benzbeeb

Fixed #1881

2020-06-08 09:10 UTC, sorawit requested changes

2020-06-08 09:10 UTC, sorawit commented on bridges/evm/contracts/Bridge.sol
>              abi.encodePacked(
I think we can remove `abi.encodePacked`

2020-06-08 09:10 UTC, sorawit commented on chain/x/oracle/keeper/request.go
> +	encodedResult := types.CalculateEncodedResult(req, res)
Let's make this one liner.

2020-06-08 09:10 UTC, sorawit commented on chain/x/oracle/types/packets.go
> +func CalculateEncodedResult(req OracleRequestPacketData, res OracleResponsePacketData) []byte {
Can make this one line!

2020-06-08 09:10 UTC, sorawit commented on chain/x/oracle/types/packets.go
> +// CalculateEncodedResult returns append obi encode of request and response packet.
obi encoded of ... packets.

2020-06-08 09:10 UTC, sorawit commented on chain/x/oracle/types/events.go
> +	AttributeKeyEncodedResult  = "encoded_result"
Let's remove this event.

2020-06-08 12:53 UTC, sorawit requested changes

2020-06-08 12:53 UTC, sorawit commented on chain/x/oracle/types/packets_test.go
> +	expectedEncodedResult := []byte{0x0, 0x0, 0x0, 0x4, 0x62, 0x65, 0x65, 0x62, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0, 0xf, 0x3, 0x0, 0x0, 0x0, 0x42, 0x54, 0x43, 0x64, 0x0, 0x0, 0x0, 0x0
Please use `mustDecodeString`

2020-06-09 02:33 UTC, sorawit approved these changes

2020-06-09 03:30 UTC, taobun approved these changes

2020-06-09 04:08 UTC, merged