scan: added helper tooltip
bandprotocol/bandchain pull request #1904
Opened 2020-06-08 09:06 UTC by tansawit

2020-06-08 09:47 UTC, evilpeach commented
@tansawit I think we should use a question mark tooltip like this 
![image](https://user-images.githubusercontent.com/14128977/84016594-b46e9500-a9a7-11ea-94e4-44a0c005afe2.png)

2020-06-09 04:31 UTC, evilpeach requested changes
Let's create a new component for Tooltip. Don't use Text.

2020-06-09 10:26 UTC, evilpeach approved these changes

2020-06-09 10:27 UTC, prin-r approved these changes

2020-06-09 10:27 UTC, merged