Add request + response packet to request rest endpoint
bandprotocol/bandchain pull request #1905
Opened 2020-06-08 10:18 UTC by Benzbeeb

Fixed #1882

2020-06-09 11:17 UTC, sorawit requested changes

2020-06-09 11:17 UTC, sorawit commented on chain/x/oracle/types/querier.go
> +	Result  Result   `json:"result"`
Make this pointer.

2020-06-09 11:17 UTC, sorawit commented on chain/x/oracle/keeper/querier.go
> +	resultBytes, _ := k.GetResult(ctx, types.RequestID(id))
GetResult return pair type. MustGetResult.

2020-06-09 13:04 UTC, sorawit requested changes

2020-06-09 13:04 UTC, sorawit commented on chain/x/oracle/client/common/request_search.go
> +					if err != nil {
if err != nil we should just return error in my opinion. We never expect to get error.

2020-06-09 13:04 UTC, sorawit requested changes

2020-06-09 13:04 UTC, sorawit commented on CHANGELOG.md
> +- (impv) [\#1900](https://github.com/bandprotocol/bandchain/pull/1900) Shorten marketcap amount on landing page
let's remove this?

2020-06-09 17:39 UTC, taobun requested changes

2020-06-09 17:39 UTC, taobun commented on chain/x/oracle/keeper/querier.go
> +	result := k.MustGetResult(ctx, types.RequestID(id))
I think it should use HasResult first if the result doesn't exist it should return nil not panic endpoint.

2020-06-10 03:16 UTC, taobun requested changes

2020-06-10 03:16 UTC, taobun commented on chain/x/oracle/keeper/result.go
> +// MustGetResult returns the result bytes for the given request ID. Panics on error.
ditto

2020-06-10 03:51 UTC, taobun requested changes

2020-06-10 03:51 UTC, taobun commented on chain/x/oracle/keeper/querier.go
> +	if !k.HasRequest(ctx, types.RequestID(id)) {
HasResult!!

2020-06-10 04:21 UTC, taobun approved these changes

2020-06-10 04:24 UTC, sorawit approved these changes

2020-06-10 04:33 UTC, merged