scan: search bar on validator home page
bandprotocol/bandchain pull request #1906
Opened 2020-06-08 10:53 UTC by tansawit

Fixes: #1896

2020-06-12 04:01 UTC, evilpeach commented
@tansawit  Please fix the conflict.

2020-06-12 04:19 UTC, evilpeach requested changes
Please the conflict.

2020-06-14 10:58 UTC, evilpeach requested changes

2020-06-14 10:58 UTC, evilpeach commented on scan/src/pages/ValidatorHomePage.re
> +                ->Belt_Array.mapWithIndex((i, e) =>
sorting ??

2020-06-16 17:56 UTC, evilpeach commented
IMO, we should disable the toggle button by using opacity.

2020-06-17 07:45 UTC, evilpeach requested changes

2020-06-17 07:45 UTC, evilpeach commented on scan/src/pages/ValidatorHomePage.re
> +        onChange={event => setSearchTerm(ReactEvent.Form.target(event)##value)}
setState function expects the function that returns a new state.
So, It should be like this.
```
event => {
      let newVal = ReactEvent.Form.target(event)##value;
      setSearchTerm(_ => newVal);
}
```

2020-06-17 08:47 UTC, evilpeach approved these changes

2020-06-17 12:04 UTC, prin-r approved these changes

2020-06-17 12:04 UTC, merged