Oracled2 Google cloud executor
bandprotocol/bandchain pull request #1908
Opened 2020-06-08 14:01 UTC by perimeko

2020-06-08 14:42 UTC, sorawit requested changes

2020-06-08 14:42 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +	executable := string(exec)
```
var executable string
if e.Name == "cloud-function" {
   executable = base64.StdEncoding.EncodeToString(exec)
} else {
   executable = string(exec)
}
```

2020-06-08 14:42 UTC, sorawit commented on chain/cmd/bandoracled2/executor.go
> +				"timeout":    timeoutStr,
I think we can pass u64 directly. Let's use `map[string]interface{}`?

2020-06-09 17:41 UTC, taobun submitted a review, later dismissed

2020-06-10 02:02 UTC, sorawit submitted a review, later dismissed

2020-06-11 03:43 UTC, sorawit commented
@perimeko Please rebase this into changelog_unreleased

2020-06-12 03:53 UTC, sorawit approved these changes

2020-06-12 08:17 UTC, taobun approved these changes

2020-06-12 08:19 UTC, merged