go-owasm: Compile wat to wasm
bandprotocol/bandchain pull request #1922
Opened 2020-06-09 13:24 UTC by perimeko

fixed #1863

2020-06-09 16:52 UTC, sorawit requested changes

2020-06-09 16:52 UTC, sorawit commented on go-owasm/api/lib.go
> +func WatToWasm(code []byte) ([]byte, error) {
Let's call this`Wat2Wasm` for the sake of consistency

2020-06-09 16:52 UTC, sorawit commented on go-owasm/api/lib.go
> +	outputSpan := newSpan(1 * 1024 * 1024)
Eventually we will need to take this as parameter or define it as a constant somewhere.

2020-06-09 16:52 UTC, sorawit commented on go-owasm/src/error.rs
> +  CompileFail = 1,
Please remove unused errors.

2020-06-09 16:52 UTC, sorawit commented on go-owasm/src/error.rs
> +  Ok = 0,
Let's suffix them with "Error"
```
NoError = 0
CompliationError = 1
ParseError = 2
...
```

2020-06-09 17:51 UTC, perimeko commented on go-owasm/src/error.rs
> +  CompileFail = 1,
This error is used in Compile function

2020-06-11 08:19 UTC, taobun requested changes

2020-06-11 08:19 UTC, taobun commented on go-owasm/api/lib_test.go
> +	wasm, err := Wat2Wasm(code)
I think we don't need to test wasm if an error happens.

2020-06-11 08:20 UTC, sorawit requested changes

2020-06-11 08:20 UTC, sorawit commented on chain/x/oracle/keeper/owasm.go
> +		k.Logger(ctx).Info(fmt.Sprintf("failed to prepare request with error: %s", err.Error()))
Let's wrap error and stop logging.

2020-06-11 08:20 UTC, sorawit commented on chain/x/oracle/keeper/owasm.go
> +			"failed to execute request id: %d with error: %s", reqID, err.Error(),
ditto.

2020-06-11 08:24 UTC, taobun commented on chain/x/oracle/keeper/owasm.go
> +			"failed to execute request id: %d with error: %s", reqID, err.Error(),
Use log when executing code.

2020-06-11 08:48 UTC, taobun requested changes

2020-06-11 08:48 UTC, taobun commented on go-owasm/api/lib_test.go
> +	wasm, err := Wat2Wasm(code)
ditto

2020-06-11 08:49 UTC, sorawit approved these changes

2020-06-11 08:52 UTC, taobun approved these changes

2020-06-11 08:55 UTC, merged