chain: Add query validator report info on CLI and REST endpoint
bandprotocol/bandchain pull request #1929
Opened 2020-06-10 11:41 UTC by perimeko

fixed #1885

2020-06-11 09:30 UTC, taobun approved these changes

2020-06-12 03:35 UTC, sorawit requested changes

2020-06-12 03:35 UTC, sorawit commented on chain/x/oracle/client/rest/rest.go
> +	r.HandleFunc(fmt.Sprintf("/%s/report-info/{%s}", storeName, validatorAddressTag), getReportInfoHandler(cliCtx, storeName)).Methods("GET")
Let's make this underscore

2020-06-12 03:35 UTC, sorawit commented on chain/x/oracle/types/querier.go
> +	QueryReportInfo    = "report-info"
underscore

2020-06-12 07:29 UTC, sorawit approved these changes

2020-06-12 07:40 UTC, merged