chain: Wireup go-owasm with blockchain properly
bandprotocol/bandchain pull request #1934
Opened 2020-06-11 09:18 UTC by taobun

fixed #1868

2020-06-13 11:15 UTC, sorawit requested changes
Let's add validate basic to ensure that you can't create do-not-modify data sources or oracle scripts.

2020-06-23 05:43 UTC, sorawit requested changes

2020-06-23 05:43 UTC, sorawit commented on chain/x/oracle/common_test.go
> +	absPath, _ := filepath.Abs(fmt.Sprintf("../../pkg/owasm/res/%s", filename))
Let's move out of this legacy `pkg/owasm`. We can create `testfiles` folder in `x/oracle`

2020-06-23 05:43 UTC, sorawit commented on chain/x/oracle/keeper/common_test.go
> +	absPath, _ := filepath.Abs("../../../pkg/owasm/res/beeb.wat")
also here

2020-06-23 05:43 UTC, sorawit commented on chain/x/oracle/types/error.go
> +	ErrCompileFailed               = sdkerrors.Register(ModuleName, 37, "owasm compile failed")
ErrOwasmCompilation ... owasm compilation failed

2020-06-23 07:21 UTC, Benzbeeb requested changes

2020-06-23 07:21 UTC, Benzbeeb commented on chain/x/oracle/handler_test.go
> +	code := []byte("non wasm coce")
non wasm code

2020-06-23 07:31 UTC, Benzbeeb requested changes

2020-06-23 07:31 UTC, Benzbeeb commented on chain/pkg/owasm/res/edited_beeb.wat
> +    i32.const 1024
change this line to ``` i64.const 1024```

2020-06-23 07:31 UTC, Benzbeeb commented on chain/pkg/owasm/res/edited_beeb.wat
> +    i64.extend_u/i32
remove this line

2020-06-23 07:35 UTC, Benzbeeb requested changes

2020-06-23 07:35 UTC, Benzbeeb commented on chain/pkg/owasm/res/edited_beeb.wat
> +    i32.const 1024
ditto

2020-06-23 07:35 UTC, Benzbeeb commented on chain/pkg/owasm/res/edited_beeb.wat
> +    i64.extend_u/i32
ditto

2020-06-23 09:58 UTC, Benzbeeb approved these changes

2020-06-23 10:18 UTC, sorawit requested changes

2020-06-23 10:18 UTC, sorawit commented on chain/x/oracle/handler_test.go
> +	fmt.Println(filename)
remove please

2020-06-23 10:18 UTC, sorawit commented on chain/x/oracle/handler_test.go
> +	fmt.Println(filename)
remove

2020-06-23 12:20 UTC, sorawit approved these changes

2020-06-23 12:20 UTC, merged