go-owasm: Return error if writing beyond the provided span length
bandprotocol/bandchain pull request #1936
Opened 2020-06-11 12:35 UTC by perimeko

fixed #1862

2020-06-11 17:11 UTC, sorawit requested changes

2020-06-11 17:11 UTC, sorawit commented on go-owasm/src/span.rs
> +    fn test_success_write_span_ok() {
Let's also test reading and creating spans here!

2020-06-12 13:44 UTC, sorawit approved these changes
Looks great.

2020-06-15 03:43 UTC, Benzbeeb approved these changes

2020-06-15 03:51 UTC, taobun approved these changes

2020-06-15 03:52 UTC, merged