Allow gas configuration from golang world to wasmer
bandprotocol/bandchain pull request #1937
Opened 2020-06-11 12:51 UTC by Benzbeeb

Fixed #1866

2020-06-11 17:09 UTC, sorawit requested changes

2020-06-11 17:09 UTC, sorawit commented on go-owasm/api/test_util.go
> +package api
Can this `common_test.go`

2020-06-11 17:09 UTC, sorawit commented on go-owasm/src/lib.rs
> +fn run(code: &[u8], gas_limit: u32, is_prepare: bool, env: Env) -> Result<(), i32> {
I think we should make this function return `Result<(), Error>`

2020-06-15 03:36 UTC, perimeko commented on go-owasm/api/lib_test.go
> +func TestCom(t *testing.T) {
Is this function means `TestCompile`? Can we change to `TestCompileError`?

2020-06-16 04:35 UTC, sorawit approved these changes

2020-06-16 04:40 UTC, perimeko approved these changes

2020-06-16 04:41 UTC, merged