Scan: add validator image from identity
bandprotocol/bandchain pull request #1938
Opened 2020-06-11 13:42 UTC by evilpeach

Fixes #1560

2020-06-12 08:10 UTC, tansawit requested changes
Change 1-line columns in ValidatorHomePage to center-aligned

2020-06-12 08:17 UTC, tansawit requested changes

2020-06-12 08:17 UTC, tansawit commented on scan/src/components/Avatar.re
> +      src={j|https://ui-avatars.com/api/?rounded=true&size=128&name=$moniker&color=fff&background=CA47EB|j}
Use `https://ui-avatars.com/api/?rounded=true&size=128&name=figment&color=9714B8&background=F3CEFD` instead?

2020-06-12 10:37 UTC, sorawit approved these changes

2020-06-14 09:15 UTC, tansawit approved these changes

2020-06-14 09:17 UTC, merged