Scan: use Format on user balance
bandprotocol/bandchain pull request #1939
Opened 2020-06-11 13:56 UTC by evilpeach

Fixes #1488

2020-06-14 09:27 UTC, tansawit approved these changes

2020-06-14 09:28 UTC, tansawit requested changes
Please fix changelog conflict

2020-06-17 04:17 UTC, prin-r approved these changes

2020-06-17 07:09 UTC, tansawit approved these changes

2020-06-17 07:09 UTC, merged