Scan: improve address validation
bandprotocol/bandchain pull request #1940
Opened 2020-06-11 14:42 UTC by evilpeach

Fixes #1899 

What I do
- trim address
- alert when sending to yourself

2020-06-12 07:55 UTC, tansawit requested changes

2020-06-12 07:55 UTC, tansawit commented on scan/src/pages/AccountIndexPage.re
> +          Window.alert("Why are you sending BAND to yourself?");
Change blocking to a warning instead. For example, "Are you sure you want to send tokens to yourself?" with "Continue" and "Cancel" options.

2020-06-14 09:23 UTC, tansawit requested changes
Please fix conflict

2020-06-14 09:25 UTC, evilpeach commented
> Please fix conflict

Done

2020-06-17 07:23 UTC, tansawit approved these changes

2020-06-17 08:32 UTC, prin-r approved these changes

2020-06-17 09:13 UTC, merged