Add bandchain.js
bandprotocol/bandchain pull request #1963
Opened 2020-06-13 07:46 UTC by smiled0g

2020-06-14 10:12 UTC, evilpeach reviewed
Should we add the test to GitHub action?

2020-06-14 16:47 UTC, smiled0g commented
> Should we add the test to GitHub action?

Hmm.. I'm not entirely sure here. I guess we should, but in that case, we should also use mock server requests instead of the real requests to GuanYu devnet we're doing right now.

What do you think? @sorawit

2020-06-14 16:48 UTC, sorawit commented
Yes. I think if we are to add it to github action, better be tests that don't rely on external API calls.

2020-06-17 09:15 UTC, evilpeach approved these changes

2020-06-17 09:59 UTC, prin-r approved these changes

2020-06-17 10:04 UTC, prin-r commented on helpers/bandchain.js/src/lib/BandChain.js
> +  async getRequestID(txHash) {
I saw retryTimeout = 200 at "getRequestProof". So should we add it here as well ?

2020-06-17 10:08 UTC, taobun requested changes
Nope

2020-06-17 10:19 UTC, taobun approved these changes

2020-06-17 10:19 UTC, taobun commented on helpers/README.md
> +| [`Python 3 🐍`](pyobi)          | 🤔 Not Started |
obi LUL

2020-06-17 10:20 UTC, merged