scan: implement ui and wireup redelegate modal
bandprotocol/bandchain pull request #1985
Opened 2020-06-15 13:29 UTC by tansawit

Fixes: #1968

2020-06-16 18:14 UTC, evilpeach requested changes
1. Let's add the limit to 7 warning msg like undelegate msg modal.
2. Add more gas 
![image](https://user-images.githubusercontent.com/14128977/84811553-3b221280-b037-11ea-802d-bcd834d4402c.png)

2020-06-16 18:14 UTC, evilpeach commented on scan/src/components/modal/submitTx/RedelegateMsg.re
> +         msg="Undelegate Amount (BAND)"
Let's use Amount

2020-06-16 18:14 UTC, evilpeach commented on scan/src/components/modal/submitTx/RedelegateMsg.re
> +     | _ => <EnhanceTxInput.Loading msg="Undelegate Amount (BAND)" width=300 />
Let's use Amount

2020-06-16 18:14 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +            disabled={balanceAtStakeAmount.amount == 0. || isReachUnbondingLimit}>
Can we use `isReachUnbondingLimit`?

2020-06-16 18:14 UTC, evilpeach commented on scan/src/components/modal/submitTx/RedelegateMsg.re
> +        setSelectedValidator(_ => newVal);
Add `TODO: Hack styles for react-select` here.

2020-06-17 08:57 UTC, evilpeach requested changes

2020-06-17 08:57 UTC, evilpeach commented on scan/src/components/modal/submitTx/RedelegateMsg.re
> +         placeholder="Insert unbonding amount"
redelegate amount?

2020-06-17 09:01 UTC, sorawit approved these changes

2020-06-17 09:37 UTC, evilpeach approved these changes

2020-06-17 09:39 UTC, merged