scan: add autofocus to submittx modal
bandprotocol/bandchain pull request #1986
Opened 2020-06-15 16:36 UTC by tansawit

Fixes: #1980

2020-06-16 17:26 UTC, evilpeach requested changes

2020-06-16 17:26 UTC, evilpeach commented on scan/src/components/modal/submitTx/SendMsg.re
> +      autoFocus=true
If the modal is opened with the recipient address, then focus on the amount's input.
If not, then focus on the recipient address input.

2020-06-17 03:08 UTC, evilpeach approved these changes

2020-06-17 03:47 UTC, prin-r approved these changes

2020-06-17 04:00 UTC, merged