Implement safe guard to check memory limit from wasm
bandprotocol/bandchain pull request #1988
Opened 2020-06-16 09:49 UTC by Benzbeeb

Fixed #1965

2020-06-16 11:57 UTC, sorawit requested changes

2020-06-16 11:57 UTC, sorawit commented on go-owasm/src/lib.rs
> +    let memory = section.entries()[0];
Is it always the case that `section.entries()` has size 1?

2020-06-16 12:44 UTC, sorawit approved these changes
looks great

2020-06-16 12:45 UTC, sorawit approved these changes
looks great

2020-06-17 09:24 UTC, taobun approved these changes

2020-06-17 09:27 UTC, merged