chain: Downgrade to Cosmos-SDK 0.38.4
bandprotocol/bandchain pull request #1999
Opened 2020-06-17 17:23 UTC by sorawit

In order to make sure we can control the release timeline, we decide to rollback BandChain to based on Cosmos-SDK 0.38.4. We will migrate to IBC version once a stable release has come.

2020-06-18 15:03 UTC, Benzbeeb approved these changes

2020-06-18 15:05 UTC, perimeko approved these changes

2020-06-18 17:31 UTC, taobun requested changes

2020-06-18 17:31 UTC, taobun commented on chain/app/db_app.go
> +	// dbBand.IBCKeeper = app.IBCKeeper
Delete this

2020-06-18 17:31 UTC, taobun commented on chain/app/db_app.go
> +	// var bankState bank.GenesisState
Here too

2020-06-18 17:31 UTC, taobun commented on chain/cmd/bandoracled2/handler.go
> +	// ibc "github.com/cosmos/cosmos-sdk/x/ibc/04-channel/types"
Delete!

2020-06-18 17:31 UTC, taobun commented on chain/x/oracle/keeper/result.go
> +		currentReqID := types.RequestID(binary.BigEndian.Uint64(iterator.Key()[1:]))
Back to the basic lul

2020-06-18 17:31 UTC, taobun commented on chain/x/supply/keeper.go
> +func WrapSupplyKeeperBurnToCommunityPool(bk supply.Keeper) WrappedSupplyKeeper {
sk

2020-06-19 03:53 UTC, taobun approved these changes

2020-06-19 03:54 UTC, merged