Implement recursive and memory test in go-owasm
bandprotocol/bandchain pull request #2004
Opened 2020-06-18 15:08 UTC by Benzbeeb

Fixed #1990 
Fixed #1991

2020-06-18 15:11 UTC, sorawit requested changes

2020-06-18 15:11 UTC, sorawit commented on go-owasm/api/lib_test.go
> +	require.Equal(t, ErrUnknownError, err)
We should not knowingly have unknown error.

2020-06-18 15:14 UTC, sorawit requested changes

2020-06-18 15:14 UTC, sorawit commented on go-owasm/api/lib_test.go
> +	require.Equal(t, ErrCompliationFail, err)
Let's change to instantiate error.

2020-06-19 08:18 UTC, sorawit approved these changes

2020-06-22 12:23 UTC, sorawit requested changes

2020-06-22 12:23 UTC, sorawit commented on go-owasm/api/error.go
> +	case C.Error_OutOfMemoryRangeError:
Let's move this to the right place

2020-06-22 12:23 UTC, sorawit commented on go-owasm/api/bindings.h
> +  Error (*get_calldata)(env_t *, Span *calldata);
Make sure to use cbindgen format

2020-06-22 12:23 UTC, sorawit commented on go-owasm/api/bindings.h
> +  Error_OutOfMemoryRangeError = 14,
MemoryOutOfBoundError

2020-06-22 12:23 UTC, sorawit commented on go-owasm/api/error.go
> +	ErrOutOfMemoryRange        = errors.New("out of memory range")
out-of-bound memory access while executing the wasm script

2020-06-22 12:23 UTC, sorawit commented on go-owasm/src/error.rs
> +  OutOfMemoryRangeError = 14,  // Request out of memory range.
Update this comment accordingly.

2020-06-22 12:23 UTC, sorawit commented on go-owasm/src/lib.rs
> +                require_mem_range( ctx.memory(0).size().bytes().0, (ptr +span_size) as usize )?;
Let's move this check to right after when `span_size` is created. also make sure code is properly formatted.

ditto for all places below.

2020-06-22 12:59 UTC, sorawit approved these changes

2020-06-24 07:15 UTC, taobun approved these changes

2020-06-24 07:15 UTC, taobun commented
Add change log

2020-06-24 07:36 UTC, merged