Add bridge with cache
bandprotocol/bandchain pull request #2055
Opened 2020-06-23 13:26 UTC by prin-r

2020-06-24 03:07 UTC, sorawit requested changes

2020-06-24 03:07 UTC, sorawit commented on bridges/evm/contracts/Bridge.sol
> +    function relayAndVerify(bytes memory _data)
What the gas cost implication?

2020-06-25 03:31 UTC, smiled0g requested changes

2020-06-25 03:31 UTC, smiled0g commented on bridges/evm/contracts/BridgeWithCache.sol
> +            "FAIL_REQUEST_SHOULD_NEWER_THAN_THE_LATEST"
"FAIL_LATEST_REQUEST_SHOULD_BE_NEWEST"

2020-06-25 03:31 UTC, smiled0g commented on bridges/evm/contracts/BridgeWithCache.sol
> +            res.requestId > requestsCache[getRequestKey(req)].requestId,
use `res.resolveTime`

2020-06-25 06:23 UTC, taobun requested changes

2020-06-25 06:23 UTC, taobun commented on CHANGELOG_UNRELEASED.md
> +- (patch) [\#2041](https://github.com/bandprotocol/bandchain/pull/2041) Patch Multistore to new structure tree of 0.38.
Remove this change

2020-06-25 06:23 UTC, taobun commented on bridges/evm/contracts/BridgeWithCache.sol
> +
Can we store getRequestKey in a variable? remove duplicate call encode.

2020-06-25 06:23 UTC, taobun commented on bridges/evm/contracts/BridgeWithCache.sol
> +contract BridgeWithCache is Bridge {
Inherit IBridgeCache too?

2020-06-25 06:24 UTC, sorawit requested changes

2020-06-25 06:24 UTC, sorawit commented on bridges/evm/contracts/BridgeWithCache.sol
> +    /// Create hash of a RequestPacket.
Returns the hash of

2020-06-25 06:24 UTC, sorawit commented on bridges/evm/contracts/BridgeWithCache.sol
> +    function getRequestKey(RequestPacket memory _request)
represents

2020-06-25 06:24 UTC, sorawit commented on bridges/evm/contracts/BridgeWithCache.sol
> +    /// Query the ResponsePacket for a given RequestPacket.
Returns ... Reverts ...

2020-06-25 06:24 UTC, sorawit commented on bridges/evm/contracts/BridgeWithCache.sol
> +    function getLatestResponse(RequestPacket memory _request)
represents

2020-06-25 06:24 UTC, sorawit commented on bridges/evm/contracts/IBridgeCache.sol
> +    /// Query the ResponsePacket for a given RequestPacket.
ditto

2020-06-25 07:43 UTC, sorawit requested changes

2020-06-25 07:43 UTC, sorawit commented on bridges/evm/contracts/BridgeWithCache.sol
> +        (bool ok, bytes memory rawResult) = address(this).call(
We can just do `this.relayAndVerify`

2020-06-25 07:59 UTC, taobun approved these changes

2020-06-25 08:05 UTC, sorawit approved these changes

2020-06-25 08:41 UTC, smiled0g approved these changes

2020-06-25 09:06 UTC, merged