BandChain.JS: Added getChainID()
bandprotocol/bandchain pull request #2063
Opened 2020-06-25 03:09 UTC by tansawit

Added getChainID function to get current chainID from genesis endpoint and patch accordingly

2020-06-29 03:14 UTC, smiled0g requested changes

2020-06-29 03:14 UTC, smiled0g commented on helpers/bandchain.js/src/lib/BandChain.js
> +const proofSchema =
Let's move this inside `getRequestNonEVMProof` function

2020-06-29 03:14 UTC, smiled0g commented on helpers/bandchain.js/src/lib/BandChain.js
> +/* function convertSignedMsg(signedMsg) {
If we no longer needs this, just remove it.

2020-07-01 13:02 UTC, smiled0g approved these changes

2020-07-01 13:09 UTC, prin-r approved these changes

2020-07-01 13:18 UTC, merged