Handle resolve request for emitter/flusher.
bandprotocol/bandchain pull request #2072
Opened 2020-06-25 12:19 UTC by Benzbeeb

2020-06-25 12:58 UTC, taobun requested changes

2020-06-25 12:58 UTC, taobun commented on chain/emitter/handler.go
> +	kvMap := make(map[string]string)
Separate this function to `transformEvent`

2020-06-25 12:58 UTC, taobun commented on chain/emitter/handler.go
> +		id, err := strconv.ParseInt(kvMap[types.AttributeKeyRequestID], 10, 64)
use atoi

2020-06-25 12:58 UTC, taobun commented on flusher/flusher/db.py
> +    Unknown = 4
Remove it

2020-06-26 05:11 UTC, taobun requested changes

2020-06-26 05:11 UTC, taobun commented on chain/emitter/handler.go
> +		app.Write("UPDATE_REQUEST", dict)
Why we cannot write this message after add result?

2020-06-26 19:13 UTC, sorawit requested changes

2020-06-26 19:13 UTC, sorawit commented on chain/emitter/handler.go
> +	case types.EventTypeRequestExecute:
Let's expose this in alias.go, then use it as `oracle.EventTypeRequestExecute`

2020-06-26 19:13 UTC, sorawit commented on chain/emitter/handler.go
> +		resolveStatus := types.ResolveStatus(atoi(evMap[types.EventTypeRequestExecute+"."+types.AttributeKeyResolveStatus][0]))
I prefer we bring this logic to `oracle.go`

2020-06-26 19:13 UTC, sorawit commented on chain/emitter/handler.go
> +			"request_time":   atoi(evMap[types.EventTypeRequestExecute+"."+types.AttributeKeyRequestTime][0]),
Let's get all information apart from `id` from calling into the keeper's `GetResult` function. I think it's safer.

2020-06-29 04:15 UTC, taobun requested changes

2020-06-29 04:15 UTC, taobun commented on chain/x/oracle/alias.go
> +	EventTypeRequestExecute = types.EventTypeRequestExecute
Add new line between RegisterCodec and Event.

2020-06-29 04:15 UTC, taobun commented on chain/emitter/oracle.go
> +		app.OracleKeeper.GetResult(app.DeliverContext, id)
GetResult?

2020-06-29 06:19 UTC, sorawit requested changes

2020-06-29 06:19 UTC, sorawit commented on chain/emitter/oracle.go
> +func (app *App) handleRequestExecute(evMap EvMap) {
handleEventRequestExecute

2020-06-29 06:19 UTC, sorawit commented on chain/emitter/oracle.go
> +// handleRequestExecuteimplements emitter handler for EventRequestExecute.
Add space

2020-06-29 06:19 UTC, sorawit commented on chain/emitter/handler.go
> +			"request_time":   atoi(evMap[types.EventTypeRequestExecute+"."+types.AttributeKeyRequestTime][0]),
This is not resolved

2020-06-29 08:11 UTC, sorawit requested changes

2020-06-29 08:11 UTC, sorawit commented on chain/emitter/oracle.go
> +		"resolve_status": resolveStatus,
I don't need to need special logic branch for result.

2020-06-29 12:25 UTC, sorawit approved these changes

2020-07-01 03:28 UTC, taobun requested changes
Add change log

2020-07-01 03:47 UTC, taobun approved these changes

2020-07-01 06:41 UTC, merged