chain: Use rolling block hash as seed from validator sampling
bandprotocol/bandchain pull request #2074
Opened 2020-06-25 18:34 UTC by sorawit

2020-06-26 09:06 UTC, taobun requested changes

2020-06-26 09:06 UTC, taobun commented on chain/pkg/bandrng/sampling.go
> +// height weight sum among all tries.
highest?

2020-06-26 09:06 UTC, taobun commented on chain/x/oracle/keeper/keeper.go
> +		return make([]byte, 32)
sha256.Size?

2020-06-26 19:06 UTC, sorawit commented on chain/pkg/bandrng/sampling.go
> +// height weight sum among all tries.
Good catch!

2020-06-26 19:07 UTC, sorawit commented on chain/x/oracle/keeper/keeper.go
> +		return make([]byte, 32)
I added a constant for this.

2020-06-28 04:05 UTC, taobun approved these changes

2020-06-29 02:50 UTC, Benzbeeb approved these changes

2020-06-29 05:09 UTC, merged