Add Validator table and handle create validator message from genesis
bandprotocol/bandchain pull request #2109
Opened 2020-06-30 04:47 UTC by Benzbeeb

…file and tx for emitter and flusher

Fixed: #2109

## Implementation details
1. Add validators table.
2. Add handler new validator for flusher.
3. Add genesis validator from genesis state to Kafka.
4. Implement handle msgCreateValidator.

---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-06-30 07:04 UTC, taobun requested changes

2020-06-30 07:04 UTC, taobun commented on flusher/flusher/db.py
> +    Column("consensus_address", sa.String, unique=True),
Add fk

2020-07-01 07:14 UTC, taobun approved these changes

2020-07-01 07:34 UTC, sorawit requested changes

2020-07-01 07:34 UTC, sorawit commented on chain/emitter/staking.go
> +		"jailed":                false,
Should we read this from `val`?

2020-07-01 07:34 UTC, sorawit commented on chain/emitter/staking.go
> +func (app *App) SetValidator(addrs sdk.ValAddress, blockHeight int64) {
Let's call this `emitSetValidator`

2020-07-01 07:34 UTC, sorawit commented on chain/emitter/staking.go
> +	val, _ := app.StakingKeeper.GetValidator(app.DeliverContext, addrs)
Let's remove `blockHeight` argument.

2020-07-01 08:42 UTC, sorawit approved these changes

2020-07-01 09:03 UTC, merged