cdb: Delegation table emitter and flusher
bandprotocol/bandchain pull request #2118
Opened 2020-07-01 14:01 UTC by Benzbeeb

Fixed: #2086  

## Implementation details
TBD

---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-02 12:54 UTC, tansawit submitted a review, later dismissed

2020-07-02 12:54 UTC, tansawit commented on chain/emitter/delegation.go
> +	fmt.Println(delegatorAddress)
Remove "yo"

2020-07-03 05:12 UTC, sorawit requested changes

2020-07-03 05:12 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("shares", sa.String),
Why is this string?

2020-07-03 05:12 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("delegator_address", sa.String, primary_key=True),
Foreign key?

2020-07-03 13:32 UTC, sorawit requested changes

2020-07-03 13:32 UTC, sorawit commented on flusher/flusher/handler.py
> +    def handle_remove_delegation(self, msg):
I think we can delete

2020-07-03 13:32 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("active", sa.Boolean),
Let's not have this col

2020-07-03 13:32 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("last_ratio", sa.String),
Decimal?

2020-07-03 14:32 UTC, sorawit approved these changes

2020-07-03 14:48 UTC, tansawit approved these changes

2020-07-03 14:49 UTC, merged