Scan: support ledger on window by using WebHID
bandprotocol/bandchain pull request #2122
Opened 2020-07-02 03:46 UTC by evilpeach

## Implementation details
- Use WebHID to support Ledger on Windows
- Implement disconnect function

2020-07-02 13:53 UTC, tansawit requested changes

2020-07-02 13:53 UTC, tansawit commented on scan/src/utils/Os.re
> +let isWindow: unit => bool = [%bs.raw
change to `isWindows`?

2020-07-03 07:50 UTC, evilpeach commented on scan/src/utils/Os.re
> +let isWindow: unit => bool = [%bs.raw
Done!

2020-07-07 12:09 UTC, sorawit approved these changes
looks great

2020-07-07 13:02 UTC, tansawit approved these changes

2020-07-07 13:02 UTC, merged