add react-highlight and create binding, implement code tab for cript
bandprotocol/bandchain pull request #214
Opened 2020-01-13 14:27 UTC by prin-r

Fixes #192

2020-01-13 14:40 UTC, sorawit requested changes

2020-01-13 14:40 UTC, sorawit commented on scan/package.json
> +    "bs-react-syntax-highlighter": "^0.2.0",
Do we use this?

2020-01-13 14:40 UTC, sorawit commented on scan/package.json
> +    "react": ">= 0.14.0",
Is this change necessary?

2020-01-13 14:40 UTC, sorawit commented on scan/src/pages/ScriptIndexPage.re
> +           <Text value={j|📄 Cargo.toml|j} size=Text.Lg color=Colors.grayHeader />
Let's use image from design, not emoji

2020-01-14 05:16 UTC, evilpeach approved these changes
LGTM

2020-01-14 06:16 UTC, evilpeach approved these changes
LGTM

2020-01-14 07:51 UTC, sorawit approved these changes

2020-01-14 08:01 UTC, merged