Add account transactions table.
bandprotocol/bandchain pull request #2142
Opened 2020-07-03 15:22 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details
TBD
---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-03 15:27 UTC, sorawit requested changes

2020-07-03 15:27 UTC, sorawit commented on chain/emitter/app.go
> +	accsInTx    map[string]bool
The accounts related to the current processing transaction.

2020-07-03 15:27 UTC, sorawit commented on chain/emitter/app.go
> +	fmt.Println("!!", accsInTx, "!!")
?

2020-07-03 15:27 UTC, sorawit commented on flusher/flusher/handler.py
> +        print(tx_id)
???

2020-07-03 15:27 UTC, sorawit commented on flusher/flusher/handler.py
> +            if account != "":
This if should not be necessary

2020-07-03 15:27 UTC, sorawit commented on chain/emitter/distribution.go
> +	app.AddAccountsInTx(msg.WithdrawAddress.String(), msg.DelegatorAddress.String())
remove delegator address?

2020-07-03 15:27 UTC, sorawit commented on chain/emitter/distribution.go
> +	app.AddAccountsInTx(msg.DelegatorAddress.String())
don't think this is right.

2020-07-06 06:41 UTC, taobun requested changes

2020-07-06 06:41 UTC, taobun commented on chain/emitter/app.go
> +	accMap := make(map[string]bool)
Why we need to declare this map, we can't use app.AddAccountsInBlock(app.accsInTx...)?

2020-07-07 14:12 UTC, sorawit requested changes

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/app.go
> +func (app *App) AddAccountsInBlock(accs ...string) {
This should take AccAddress. Ditto for below.

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/app.go
> +	app.AddAccountsInBlock(stdTx.GetSigners()[0].String())
Signers also need to get added to "account_transactions"

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/app.go
> +	txDict["account_transcations"] = accsInTx
Let's call this "related_accounts". Make sure to also update flusher.

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/app.go
> +
nit: Remove extra space

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/distribution.go
> +	delegatorAddr := app.DistrKeeper.GetDelegatorWithdrawAddr(app.DeliverContext, msg.DelegatorAddress)
This should be called `withdrawAddr`

2020-07-07 14:12 UTC, sorawit commented on chain/emitter/bank.go
> +	app.AddAccountsInTx(msg.FromAddress.String(), msg.ToAddress.String())
From is not necessary as it's already the signer.

2020-07-07 15:52 UTC, sorawit requested changes

2020-07-07 15:52 UTC, sorawit commented on chain/emitter/app.go
> +	app.AddAccountsInTx(stdTx.GetSigners()[0])
Let's append all the signers here.

2020-07-07 15:52 UTC, sorawit commented on chain/emitter/app.go
> +	// Index 0 is message new block, We insert set account message after new block message
// Index 0 is message **NEW_BLOCK**, **w**e insert **SET_ACCOUNT** message**s** right after it.

2020-07-07 16:04 UTC, sorawit requested changes

2020-07-07 16:04 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("id", sa.Integer, sa.ForeignKey("transactions.id"), primary_key=True),
Call this `transaction_id`. We will have `account_id` soon.

2020-07-08 03:14 UTC, sorawit requested changes

2020-07-08 03:14 UTC, sorawit commented on chain/emitter/app.go
> +	txIdx       int             // The current transaction's index on the current block starting from 1.
Let's remove this.

2020-07-08 03:44 UTC, taobun requested changes

2020-07-08 03:44 UTC, taobun commented on chain/emitter/handler.go
>  		app.handleMsgDelegate(msg)
Change function signature

2020-07-08 06:56 UTC, sorawit requested changes

2020-07-08 06:56 UTC, sorawit commented on chain/emitter/app.go
> +	accsInTx := []sdk.AccAddress{}
Let's call this `relatedAccounts` and initalize it with capacility of `len(app.accsInTx)`

2020-07-08 06:56 UTC, sorawit commented on chain/emitter/app.go
> +	modifyMsgs := []Message{app.msgs[0]}
modified

2020-07-08 07:11 UTC, sorawit approved these changes

2020-07-08 07:16 UTC, taobun approved these changes

2020-07-08 07:34 UTC, merged