Add validator votes table.
bandprotocol/bandchain pull request #2144
Opened 2020-07-03 16:22 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-03 16:28 UTC, sorawit requested changes

2020-07-03 16:28 UTC, sorawit commented on chain/emitter/app.go
> +		app.Write("SET_VALIDATOR_VOTE", JsDict{
let's do insert here.

2020-07-03 16:42 UTC, sorawit requested changes

2020-07-03 16:42 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("block_height", sa.Integer, primary_key=True),
fk

2020-07-03 16:47 UTC, sorawit approved these changes

2020-07-06 06:24 UTC, taobun approved these changes

2020-07-06 06:31 UTC, merged