Add missing field in raw reports and reports table
bandprotocol/bandchain pull request #2160
Opened 2020-07-06 12:01 UTC by Benzbeeb

## Implementation details

1. Add data source id in raw reports table
2. Add oracle script id in reports table
3. Add FK  for reports table
---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-06 12:56 UTC, sorawit requested changes

2020-07-06 12:56 UTC, sorawit commented on chain/emitter/oracle.go
> +		"oracle_script_id": rq.OracleScriptID,
I don't think this is needed. You can look it up through FK, right?

2020-07-06 12:56 UTC, sorawit commented on chain/emitter/oracle.go
> +			"data_source_id": kv[data.ExternalID],
Same here. I think you need to add FK between raw report and raw request

2020-07-07 02:59 UTC, sorawit approved these changes

2020-07-07 08:27 UTC, taobun approved these changes

2020-07-07 09:04 UTC, merged