Add field validator id for validators table.
bandprotocol/bandchain pull request #2177
Opened 2020-07-08 10:26 UTC by Benzbeeb

## Implementation details

1. Add field id in validators table.
2. Change all foreign key that refers from operator address to id.
3. Fix flusher handler

---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 10:38 UTC, sorawit requested changes

2020-07-08 10:38 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("validator", sa.Integer, sa.ForeignKey("validators.id"), primary_key=True),
Let's call all of these "validator_id"

2020-07-09 05:45 UTC, sorawit requested changes

2020-07-09 05:45 UTC, sorawit commented on flusher/flusher/db.py
> +    Column("validato_id", sa.Integer, sa.ForeignKey("validators.id"), primary_key=True),
This won't work. Please make sure to test it.

2020-07-09 05:54 UTC, sorawit approved these changes

2020-07-09 06:02 UTC, taobun requested changes

2020-07-09 06:02 UTC, taobun commented on flusher/flusher/handler.py
> +            .where(msg["operator_address"] == validators.c.operator_address)
swap operand side

2020-07-09 06:58 UTC, taobun requested changes

2020-07-09 06:58 UTC, taobun commented on flusher/flusher/db.py
>      Column("account_id", sa.Integer, sa.ForeignKey("accounts.id"), primary_key=True),
Revisit all account_id.

2020-07-09 07:14 UTC, sorawit approved these changes

2020-07-09 07:43 UTC, taobun approved these changes

2020-07-09 07:45 UTC, merged