add field id in accounts table
bandprotocol/bandchain pull request #2178
Opened 2020-07-08 11:03 UTC by Benzbeeb

## Implementation details

1. Add field id in accounts table.
2. Change all foreign key that refers from account address to id.
3. Fix flusher handler
---

Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 11:11 UTC, sorawit approved these changes

2020-07-09 05:50 UTC, taobun requested changes

2020-07-09 05:50 UTC, taobun commented on flusher/flusher/handler.py
> +    def get_account_id(self, delegator_address):
Rename delegator_address to address.

2020-07-09 05:50 UTC, taobun commented on flusher/flusher/handler.py
> +
remove empty line

2020-07-09 05:50 UTC, taobun commented on flusher/flusher/handler.py
> +
ditto

2020-07-09 06:03 UTC, taobun approved these changes

2020-07-09 06:23 UTC, merged