emitter: Add parse bytes to convert nill slice to empty slice
bandprotocol/bandchain pull request #2179
Opened 2020-07-08 12:44 UTC by taobun

## Implementation details
Fixed emitter to send empty bytes to JSON instead of empty bytes that transformed to `null` that make flusher cannot set this value to the database.

Please ensure the following requirements are met before submitting a pull request:
---
- [x] The pull request is targeted against the correct target branch
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests (
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 13:15 UTC, sorawit requested changes

2020-07-08 13:15 UTC, sorawit commented on CHANGELOG_UNRELEASED.md
> +- (bugs) [\#2179](https://github.com/bandprotocol/bandchain/pull/2179) Add parse bytes to convert nill slice to empty slice.
typo: nil slices to empty slices.

2020-07-08 16:11 UTC, sorawit approved these changes
Looks great!

2020-07-09 09:00 UTC, Benzbeeb approved these changes

2020-07-09 09:12 UTC, merged