cdb: Fix bug data source and oracle script id from genesis.
bandprotocol/bandchain pull request #2180
Opened 2020-07-08 13:01 UTC by Benzbeeb

## Implementation details
1. set oracle scripts and data sources id start from 1
---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 13:35 UTC, sorawit requested changes

2020-07-08 13:35 UTC, sorawit commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2180](https://github.com/bandprotocol/bandchain/pull/2180) Fix bug data source and oracle script id from genesis.
🐛🐛🐛

2020-07-08 16:02 UTC, taobun approved these changes

2020-07-09 05:39 UTC, sorawit approved these changes

2020-07-09 05:39 UTC, merged