cdb: Change all foreign key that refers from tx_hash to id.
bandprotocol/bandchain pull request #2181
Opened 2020-07-08 13:26 UTC by Benzbeeb

## Implementation details
1. Change all foreign key that refers from tx_hash to id.
2. Fix flusher handler
---

Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 13:34 UTC, sorawit requested changes

2020-07-08 13:34 UTC, sorawit commented on flusher/flusher/handler.py
> +        del msg["tx_hash"]
I don't think you can delete a key if it does not exist.

2020-07-08 16:05 UTC, taobun commented on flusher/flusher/handler.py
> +            msg["transaction_id"] = self.conn.execute(
Can we create a helper function to get transaction_id instead of copy these lines of code to be the same work?

2020-07-09 08:20 UTC, sorawit approved these changes
Thanks!

2020-07-09 08:25 UTC, taobun requested changes

2020-07-09 08:25 UTC, taobun commented on flusher/flusher/db.py
>      Column("reporter", sa.String),
Change to reporter_id

2020-07-09 08:57 UTC, taobun approved these changes

2020-07-09 09:01 UTC, merged