Add `validator_moniker` on `add_reporter` msg.
bandprotocol/bandchain pull request #2184
Opened 2020-07-08 14:08 UTC by Benzbeeb

## Implementation details
Add `validator_moniker` on `add_reporter` msg. 
---

Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-08 16:08 UTC, taobun commented on chain/emitter/oracle.go
> +	extra["validator_moniker"] = val.GetMoniker()
We need to add this field on MsgRemoveReporter too?

2020-07-09 05:39 UTC, sorawit approved these changes

2020-07-09 05:42 UTC, taobun requested changes

2020-07-09 05:42 UTC, taobun commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2184](https://github.com/bandprotocol/bandchain/pull/2184) Add `validator_moniker` on `add_reporter` msg.
Update `remove_reporter` and in the description too.

2020-07-09 06:59 UTC, taobun approved these changes

2020-07-09 07:00 UTC, merged