chain/yoda: Add commands for improve experience
bandprotocol/bandchain pull request #2204
Opened 2020-07-11 12:57 UTC by taobun

## Implementation details
- Add `multi-send` command in the same level of send cmd to send coin from 1 account to multiple accounts with the same amount.
- Add `add-reporters` command to pack `MsgAddReport`s in one transaction.
- Add flag in `yoda keys list` to get only address using in `multi-send` and `add-reporters` command. Look example at `start_yoda.sh`.

Please ensure the following requirements are met before submitting a pull request:
---
- [x] The pull request is targeted against the correct target branch
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests. (Test by run chain can request and report correctly)
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-11 16:55 UTC, sorawit requested changes
Looking good. Some comments from me.

2020-07-11 16:55 UTC, sorawit commented on chain/x/oracle/client/cli/tx.go
> +		GetCmdAddReporters(cdc),
I don't think we need a new command. Let's change the current `add-reporter` to take any number of reporters.

2020-07-11 16:55 UTC, sorawit commented on chain/x/oracle/client/cli/tx.go
> +		Short: "Add an agent authorized to submit report transactions.",
an agent -> agents

2020-07-11 16:55 UTC, sorawit commented on chain/x/oracle/client/cli/tx.go
> +// GetCmdAddReporter implements the add reporter command handler.
add reporters

2020-07-11 16:55 UTC, sorawit commented on chain/cmd/bandcli/multi_send.go
> +			for _, arg := range args[1:] {
I think it's safer to use Coin.Add. So we start with `inputCoins = nil` and do `inputCoins = inputCoins.Add(coins)` in the loop and contract `bank.Input` after we complete the loop. That way we don't need `mulCoins` function too.

2020-07-11 16:55 UTC, sorawit commented on chain/cmd/bandcli/multi_send.go
> +			// parse coins trying to be sent
// Parse the coins we are trying to send

2020-07-11 16:55 UTC, sorawit commented on chain/cmd/bandcli/multi_send.go
> +// MultiSendTxCmd will create a multi-send tx and sign it with the given key.
MultiSendTxCmd creates ... and signs ...

2020-07-12 07:50 UTC, sorawit approved these changes
Looks great!

2020-07-13 10:45 UTC, tansawit approved these changes

2020-07-13 11:16 UTC, merged