scan: added expired status to scan
bandprotocol/bandchain pull request #2228
Opened 2020-07-13 14:30 UTC by tansawit

## Implementation details

Added support for `expired` request status on scan

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-14 07:04 UTC, evilpeach approved these changes
LGTM

2020-07-14 07:04 UTC, evilpeach requested changes
Please add CHANGELOG

2020-07-15 04:21 UTC, evilpeach approved these changes

2020-07-15 04:22 UTC, prin-r approved these changes

2020-07-15 04:43 UTC, merged