go-owasm: Allow OEI to read nil external data
bandprotocol/bandchain pull request #2251
Opened 2020-07-17 10:23 UTC by sorawit

## Implementation details
Allow Owasm script to read nil report data. This fixes a potential issue where a malicious validator may intentionally report `nil` data to make oracle request complete failure. With this change, the oracle script can decide what to do with empty data itself.

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-19 06:56 UTC, taobun approved these changes

2020-07-20 03:28 UTC, Benzbeeb requested changes

2020-07-20 03:28 UTC, Benzbeeb commented on chain/x/oracle/keeper/owasm_test.go
> +		// 4st Wasm. Append all reports from all validators.
4th

2020-07-20 03:30 UTC, Benzbeeb approved these changes

2020-07-20 04:45 UTC, merged