Mobile update on block hp
bandprotocol/bandchain pull request #2287
Opened 2020-07-21 11:32 UTC by pzshine

Fixed: #2261

## Implementation details

- Increased the spacing on the inner container.
- Implemented the new mobile card component the data tables
  - Now it's only able to use only blockHomepage.
  - This component can be reused.

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-07-21 12:21 UTC, evilpeach requested changes

2020-07-21 12:21 UTC, evilpeach commented on scan/src/App.re
> +  let innerContainer = style([marginLeft(`auto), marginRight(`auto), paddingLeft(`px(15)), paddingRight(`px(15))]);
Let's use `padding2`.

2020-07-21 12:21 UTC, evilpeach commented on scan/src/reusable/InfoMobileCard.re
> +  let oracleScriptContainer = style([display(`flex), width(`px(240))]);
remove

2020-07-21 12:21 UTC, evilpeach commented on scan/src/reusable/InfoMobileCard.re
> +  | BlockHeight(ID.Block.t)
rename to `Height`

2020-07-21 12:21 UTC, evilpeach commented on scan/src/reusable/InfoMobileCard.re
> +  | BlockTXNCount(int)
rename to `Count`

2020-07-22 02:55 UTC, tansawit requested changes

2020-07-22 02:55 UTC, tansawit commented on scan/src/pages/BlockHomePage.re
> +          "PROPERSER",
"PROPOSER"

2020-07-22 02:55 UTC, tansawit commented on scan/src/pages/BlockHomePage.re
> +        ("PROPERSER", Loading(136)),
ditto

2020-07-22 04:14 UTC, tansawit approved these changes

2020-07-22 04:17 UTC, evilpeach approved these changes

2020-07-22 04:25 UTC, merged