scan: implement top part of validatorindexpagemobile
bandprotocol/bandchain pull request #2294
Opened 2020-07-22 09:39 UTC by tansawit

Fixed: #2265 

## Implementation details

Implement top part of `ValidatorIndexPage` mobile version

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

## If this PR doesn't need to be merged into v1.0.6 please remove this option:

- [ ] The pull request has been cherry-picked to `rc/1.0.6`

2020-07-23 05:07 UTC, evilpeach requested changes
Please fix detail style also.
![image](https://user-images.githubusercontent.com/14128977/88253717-11ff3c80-ccdd-11ea-9d60-f91ec287da59.png)

2020-07-23 05:07 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +      borderRadius(`px(4)),
Let's use 100 percent width.

2020-07-23 09:24 UTC, pzshine requested changes

2020-07-23 09:24 UTC, pzshine commented on scan/src/pages/ValidatorIndexPage.re
> +  let underline = style([color(Colors.bandBlue)]);
Can you change `underline` to `blueLink` or something?

2020-07-23 11:35 UTC, evilpeach requested changes

2020-07-23 11:35 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +      backgroundColor(`hex("FFFFFF")),
Colors.white

2020-07-23 11:35 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +        Shadow.box(~x=`zero, ~y=`px(2), ~blur=`px(4), ~spread=`px(0), rgba(0, 0, 0, 0.08)),
`zero ?

2020-07-23 11:35 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +      paddingBottom(`px(16)),
padding4?

2020-07-23 11:35 UTC, evilpeach commented on scan/src/pages/ValidatorIndexPage.re
> +};
Do need to create a new one for mobile. Let's use `Uptime` module. In the `Uptime` module, I just see the duplicated title and description like "Percentage of the blocks that the validator is active for out of the last 250".

2020-07-23 13:27 UTC, pzshine approved these changes

2020-07-24 04:13 UTC, evilpeach approved these changes

2020-07-24 04:20 UTC, merged