scan: implement implement proposed blocks and delegators tables for `ValidatorIndexPage` mobile version
bandprotocol/bandchain pull request #2296
Opened 2020-07-23 07:51 UTC by tansawit

…alidatorindexpage mobile

Fixed: #2266, #2267

## Implementation details

Implemented proposed blocks and delegators table in `ValidatorIndexPage` mobile version.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

## If this PR doesn't need to be merged into v1.0.6 please remove this option:

- [ ] The pull request has been cherry-picked to `rc/1.0.6`

2020-07-23 11:11 UTC, evilpeach requested changes

2020-07-23 11:11 UTC, evilpeach commented on scan/src/components/validator/DelegatorsTable.re
> +  let mobileCount = style([paddingTop(`px(25)), paddingBottom(`px(25)), display(`flex)]);
padding2 ?

2020-07-23 11:11 UTC, pzshine requested changes

2020-07-23 11:11 UTC, pzshine commented on scan/src/components/validator/DelegatorsTable.re
> +  Media.isMobile() ? renderMobile(~address) : renderDesktop(~address);
Change `Media.isMobile()` to `let isMobile = Media.isMobile()` then replace to 3 places you wrote.

2020-07-24 05:21 UTC, pzshine approved these changes

2020-07-24 05:26 UTC, evilpeach approved these changes

2020-07-24 05:27 UTC, merged