scan: implement latest blocks mobile version
bandprotocol/bandchain pull request #2300
Opened 2020-07-23 10:42 UTC by tansawit

Fixed: #2216 

## Implementation details

Implemented latest blocks module for mobile version.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

## If this PR doesn't need to be merged into v1.0.6 please remove this option:

- [ ] The pull request has been cherry-picked to `rc/1.0.6`

2020-07-23 15:33 UTC, evilpeach requested changes

2020-07-23 15:33 UTC, evilpeach commented on scan/src/components/LatestBlocks.re
> +let make = (~blocksSub: ApolloHooks.Subscription.variant(_)) => {
you can remove declared type.

2020-07-23 15:33 UTC, evilpeach commented on scan/src/components/LatestBlocks.re
> +let renderMobile = (~blocksSub: ApolloHooks.Subscription.variant(_)) => {
Remove declared type.

2020-07-23 15:33 UTC, evilpeach commented on scan/src/components/LatestBlocks.re
> +         | Data(blocks) =>
Change `Data(blocks)` to `ApolloHooks.Subscription.Data(blocks)`.

2020-07-24 03:14 UTC, pzshine approved these changes

2020-07-24 03:17 UTC, pzshine requested changes

2020-07-24 03:17 UTC, pzshine commented on scan/src/pages/HomePage.re
> +        <Col size=1.> <LatestBlocks blocksSub=lastest11BlocksSub /> </Col>
Can you check `size=1.` again? It breaks on desktop view.

2020-07-24 04:12 UTC, pzshine approved these changes

2020-07-24 04:14 UTC, evilpeach approved these changes

2020-07-24 04:14 UTC, merged