Yoda configurable timeout duration
bandprotocol/bandchain pull request #2307
Opened 2020-07-24 09:20 UTC by Benzbeeb

Fixed: #2258 

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

## If this PR doesn't need to be merged into v1.0.6 please remove this option:

- [ ] The pull request has been cherry-picked to `rc/1.0.6`

2020-07-24 12:49 UTC, taobun requested changes

2020-07-24 12:49 UTC, taobun commented on chain/yoda/executor/executor.go
> +	query.Del(flagQueryTimeout)
Add comment why we must do this

2020-07-31 06:50 UTC, sorawit requested changes

2020-07-31 06:50 UTC, sorawit commented on chain/yoda/executor/executor.go
> +	timeoutStr := query.Get(flagQueryTimeout)
Let's make this required.

2020-07-31 08:05 UTC, taobun requested changes

2020-07-31 08:05 UTC, taobun commented on chain/yoda/executor/docker_test.go
> +	// 	e := NewDockerExec("bandprotocol/runtime:1.0.1", 20*time.Second)
10 second and use runtime 1.0.2 version

2020-07-31 08:05 UTC, taobun commented on chain/yoda/executor/docker_test.go
> +	// 	e := NewDockerExec("bandprotocol/runtime:1.0.1", 10*time.Second)
ditto

2020-07-31 08:05 UTC, taobun commented on chain/yoda/executor/executor.go
> +	flagQueryTimeout   = "timeout"
I think we can use 
```
const (
    flagQueryTimeout   = "timeout"
)
```

2020-07-31 08:05 UTC, taobun commented on chain/yoda/executor/executor.go
> +	timeoutStr := query.Get(flagQueryTimeout)
timeoutParams, found := query[flagQueryTimeout]
...
timeout, err = time.ParseDuration(timeoutParams[0])

2020-07-31 08:25 UTC, taobun approved these changes

2020-07-31 09:21 UTC, sorawit approved these changes

2020-07-31 09:34 UTC, merged