Fix sync broadcast and poll for transaction status
bandprotocol/bandchain pull request #2331
Opened 2020-07-29 07:40 UTC by Benzbeeb

Fixed: #2324 

## Implementation details
1. Fix broadcast from commit to sync
2. Polling for transaction status

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

## If this PR doesn't need to be merged into v1.0.6 please remove this option:

- [ ] The pull request has been cherry-picked to `rc/1.0.6`

2020-07-29 08:07 UTC, sorawit requested changes

2020-07-29 08:07 UTC, sorawit commented on chain/yoda/execute.go
> +				l.Error(":exploding_head: Failed to query tx with error: %s", err.Error())
Isn't this expected? Why do we log error with exploding head?

2020-07-29 09:13 UTC, taobun requested changes

2020-07-29 09:13 UTC, taobun commented on chain/yoda/execute.go
> +				break
return

2020-07-29 13:17 UTC, taobun requested changes

2020-07-29 13:17 UTC, taobun commented on chain/yoda/execute.go
> +	for start := time.Now(); time.Since(start) < c.broadcastTimeout; {
What happens after trying until MaxTry and cannot send tx (got error every try) We need to query on empty tx response?

2020-07-29 13:17 UTC, taobun commented on chain/yoda/execute.go
>  	}
Need to log if cannot find tx if timeout?

2020-07-29 13:17 UTC, taobun commented on chain/yoda/run.go
> +	cmd.Flags().String(flagBroadcastTimeout, "", "The time that Yoda will wait for tx commit")
Add `10s` as default value

2020-07-29 16:16 UTC, taobun requested changes

2020-07-29 16:16 UTC, taobun commented on chain/scripts/start_yoda.sh
> +# setup broadcast-timeout  to yoda config
Space

2020-07-29 16:16 UTC, taobun commented on chain/scripts/start_yoda.sh
> +yoda config broadcast-timeout "10s"
@sorawit 10 seconds is the default of BroadcastTxCommit if we want to solve this problem how much time is a recommended option?

2020-07-29 16:16 UTC, taobun commented on chain/yoda/execute.go
>  		l.Error(":exploding_head: Failed to broadcast tx with error: %s", err.Error())
We don't want to see this log to be critical error. There are 2 options that I think it make sense
1. Change icon to ⚠️ 
2. Change log level to debug.

2020-07-29 16:16 UTC, taobun commented on chain/yoda/execute.go
> +		l.Info("Try to broadcast: %d/%d", try, MaxTry)
Try to broadcast report transaction(%d/%d)

2020-07-29 16:16 UTC, taobun commented on chain/yoda/execute.go
> +		l.Info("Try to broadcast: %d/%d", try, MaxTry)
add some emoji too.

2020-07-29 16:16 UTC, taobun commented on chain/yoda/execute.go
> +	l.Info("Can't find tx hash: %s before timeout", res.TxHash)
❓ Cannot get transaction response from hash: %s transaction might be included in the next few blocks or check your node's health.

2020-07-29 16:16 UTC, taobun commented on chain/yoda/execute.go
> +			l.Debug("Failed to query tx with error: %s", err.Error())
emoji!

2020-07-31 06:49 UTC, taobun requested changes

2020-07-31 06:49 UTC, taobun commented on chain/yoda/execute.go
> +	MaxTry    = 5
Move to config

2020-07-31 06:54 UTC, sorawit requested changes

2020-07-31 06:54 UTC, sorawit commented on chain/yoda/run.go
> +	cmd.Flags().String(flagBroadcastTimeout, "10s", "The time that Yoda will wait for tx commit")
30s

2020-07-31 06:54 UTC, sorawit commented on chain/yoda/execute.go
> +	SleepTime = 3 * time.Second
Change this config and rename it to `RPCPollInterval`

2020-07-31 09:10 UTC, taobun requested changes

2020-07-31 09:10 UTC, taobun commented on chain/yoda/run.go
> +	cmd.Flags().String(flagMaxTry, "5", "Maximum times of try to report transaction")
cmd.Flags().Uint64(...)

2020-07-31 09:10 UTC, taobun commented on chain/yoda/main.go
> +	MaxTry           string `mapstructure:"max-try"`           // Maximum times of try to report transaction
uint64

2020-07-31 09:53 UTC, taobun requested changes

2020-07-31 09:53 UTC, taobun commented on chain/scripts/start_yoda.sh
>  yoda config executor "docker:bandprotocol/runtime:1.0.1?timeout=10s"
Can you change this to 1.0.2?

2020-07-31 09:53 UTC, taobun commented on chain/yoda/run.go
> +	cmd.Flags().Uint64(flagMaxTry, 5, "Maximum times of try to report transaction")
The maximum number of tries to submit a report transaction.

2020-07-31 09:53 UTC, taobun commented on chain/yoda/main.go
> +	MaxTry           uint64 `mapstructure:"max-try"`           // Maximum times of try to report transaction
The maximum number of tries to submit a report transaction

2020-07-31 11:53 UTC, sorawit approved these changes

2020-07-31 11:54 UTC, taobun approved these changes

2020-07-31 12:00 UTC, merged