Scan: Add loading state to AccountIndexPage
bandprotocol/bandchain pull request #2363
Opened 2020-08-02 04:55 UTC by pzshine

Fixed: #1565

## Implementation details

 - Added Loading State to index page including the tab detail
 - `AccountIndexDelegations`, `AccountIndexUnbonding` and AccountIndexRedelegate

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-02 04:59 UTC, pzshine commented
Note:

The image needs to be changed on each tab, now I used `noTransaction` image.

![image](https://user-images.githubusercontent.com/17017699/89115869-71b4cf00-d4b7-11ea-9fad-1fcbc5a32b12.png)

2020-08-02 07:30 UTC, evilpeach requested changes

2020-08-02 07:30 UTC, evilpeach commented on scan/src/components/account/AccountIndexRedelegate.re
> +        ++ (reserveIndex |> string_of_int)
It's duplicated. Let's make it a variable.

2020-08-02 07:30 UTC, evilpeach commented on scan/src/components/account/AccountIndexUnbonding.re
> +        ++ (reserveIndex |> string_of_int)
Make a variable here as well.

2020-08-02 07:30 UTC, evilpeach commented on scan/src/pages/AccountIndexPage.re
> +    totalBalance;
It's no need to declare a variable. Just return `availableBalance +. .... `

2020-08-02 07:30 UTC, evilpeach commented on scan/src/components/account/AccountIndexDelegations.re
> +      }
Make a variable.

2020-08-02 07:31 UTC, evilpeach commented
> Note:
> 
> The image needs to be changed on each tab, now I'm using the `noTransaction` image.
> 
> ![image](https://user-images.githubusercontent.com/17017699/89115869-71b4cf00-d4b7-11ea-9fad-1fcbc5a32b12.png)

Okay, let's ask a designer for a new image.

2020-08-24 17:24 UTC, evilpeach requested changes

2020-08-24 17:24 UTC, evilpeach commented on scan/src/components/TxsTable.re
> +        ("Tx Hash", TxHash(txHash, Media.isSmallMobile() ? 170 : 200)),
TX Hash

2020-08-24 17:24 UTC, evilpeach commented on scan/src/components/TxsTable.re
> +        ("Tx Hash", Loading(Media.isSmallMobile() ? 170 : 200)),
TX Hash

2020-08-24 17:24 UTC, evilpeach commented on scan/src/components/account/AccountIndexDelegations.re
> +    <>
remove?

2020-08-24 17:24 UTC, evilpeach commented on scan/src/components/account/AccountIndexRedelegate.re
> +    <>
remove?

2020-08-24 17:24 UTC, evilpeach commented on scan/src/components/account/AccountIndexUnbonding.re
> +    <>
remove?

2020-08-24 17:24 UTC, evilpeach commented on scan/src/pages/AccountIndexPage.re
> +        dispatchModal(OpenModal(SubmitTx(SubmitMsg.Send(Some(address)))));
I think we should use this for easy understanding.
```
Some(Address) |> SubmitMsg.Send |> SubmitTx |> OpenModal |> dispatchModal
```

2020-08-24 17:24 UTC, evilpeach commented on scan/src/pages/TxHomePage.re
> +                 <Text block=true value="Tx Hash" weight=Text.Semibold color=Colors.gray7 />
TX Hash

2020-08-24 17:26 UTC, evilpeach requested changes

2020-08-24 17:26 UTC, evilpeach commented on scan/src/components/account/AccountIndexDelegations.re
> +         Belt_Array.make(1, ApolloHooks.Subscription.NoData)
Let's add more to 10 rows.

2020-08-24 17:26 UTC, evilpeach commented on scan/src/components/account/AccountIndexRedelegate.re
> +         Belt_Array.make(1, ApolloHooks.Subscription.NoData)
here as well

2020-08-24 17:26 UTC, evilpeach commented on scan/src/components/account/AccountIndexUnbonding.re
> +         Belt_Array.make(1, ApolloHooks.Subscription.NoData)
here as well

2020-08-24 17:28 UTC, evilpeach requested changes
Please check this
![image](https://user-images.githubusercontent.com/14128977/91076562-e4a20780-e669-11ea-8a23-ab9aad26bbca.png)
[Link](https://d3n-scan-pr-2363.onrender.com/account/band140lp4vgc0lvuvwef8pg4uqu9gg0vmv4ggn68jg)

2020-08-25 04:07 UTC, evilpeach requested changes

2020-08-25 04:07 UTC, evilpeach commented on scan/src/components/TxMessages.re
> +      // Media.mobile([height(overflowed ? `px(50) : `auto)]),
remove

2020-08-25 04:07 UTC, evilpeach commented on scan/src/components/account/AccountIndexUnbonding.re
> +    <>
remove

2020-08-25 04:10 UTC, evilpeach approved these changes

2020-08-25 04:11 UTC, merged