Allow report gas fee
bandprotocol/bandchain pull request #2387
Opened 2020-08-05 06:57 UTC by Benzbeeb

Fixed: #2372 #2370 

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-07 04:04 UTC, taobun requested changes

2020-08-07 04:04 UTC, taobun commented on chain/x/ante/ante.go
> +package ante
Move to /x/oracle/ante/ante.go

2020-08-07 04:04 UTC, taobun commented on chain/x/ante/ante.go
> +	"github.com/bandprotocol/bandchain/chain/x/oracle"
Order import like other files.

2020-08-07 04:04 UTC, taobun commented on chain/x/ante/ante.go
> +			if isValidReportTx = checkValidReportMsg(ctx, oracleKeeper, msg); !isValidReportTx {
I thought set `isValidReportTx` to false in if condition looks better.

2020-08-07 04:04 UTC, taobun commented on chain/app/app.go
> +	wrappedAnte := bandante.BandWrapAnteHandler(ante.NewAnteHandler(app.AccountKeeper, app.SupplyKeeper, auth.DefaultSigVerificationGasConsumer), app.OracleKeeper)
Create a flag for toggle wrap or unwrap mode

2020-08-11 06:09 UTC, sorawit requested changes

2020-08-11 06:09 UTC, sorawit commented on chain/emitter/app.go
> +	withFeeReportTx bool, baseAppOptions ...func(*bam.BaseApp),
Doesn't seem correct

2020-08-11 06:09 UTC, sorawit commented on chain/x/oracle/ante/ante.go
> +func BandWrapAnteHandler(ante sdk.AnteHandler, oracleKeeper oracle.Keeper) sdk.AnteHandler {
`NewFeelessReportsAnteHandler`

2020-08-19 11:54 UTC, sorawit approved these changes
lgtm. just some minor comment change

2020-08-19 11:54 UTC, sorawit commented on chain/x/oracle/ante/ante.go
> +// NewFeelessReportsAnteHandler returns a new ante handler that set minimum gas price to be zero if the
sets ... that waive minimum gas price requirement if

2020-08-21 11:43 UTC, merged