chain: Patch cosmos-sdk to v0.39.1-rc3
bandprotocol/bandchain pull request #2396
Opened 2020-08-05 10:52 UTC by Benzbeeb

## Implementation details

chain: Patch cosmos-sdk to v0.39.1-rc3

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-05 13:35 UTC, sorawit reviewed
Looks good

2020-08-06 06:31 UTC, taobun requested changes

2020-08-06 06:31 UTC, taobun commented on CHANGELOG_UNRELEASED.md
> +- (chain) [\#2396](https://github.com/bandprotocol/bandchain/pull/2396) Upgrade to Cosmos-SDK v0.39.1-rc3.
patch

2020-08-06 13:31 UTC, taobun approved these changes

2020-08-06 13:44 UTC, sorawit approved these changes

2020-08-06 14:32 UTC, merged