chain: Add migrate command to guanyu version
bandprotocol/bandchain pull request #2446
Opened 2020-08-09 18:28 UTC by taobun

Fixed: #2256

## Implementation details
- Modify migrate command from cosmos-sdk to specific migrate from `Wenchang` version to `Guanyu` version.
- Fix evidence param in consensus parameters of Tendermint
- Using migrate function for 0.36 -> 0.38 -> 0.39 from `cosmos-sdk`
- Add genesis state on new modules (oracle, evidence, and upgrade)

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-10 03:40 UTC, Benzbeeb approved these changes

2020-08-10 06:52 UTC, sorawit requested changes

2020-08-10 06:52 UTC, sorawit commented on chain/cmd/bandd/migrate.go
> +			defaultGaunyu := app.NewDefaultGenesisState()
GuanYu

2020-08-13 13:00 UTC, sorawit approved these changes

2020-08-13 13:04 UTC, merged