View table to calculate oracle script response time
bandprotocol/bandchain pull request #2452
Opened 2020-08-11 03:35 UTC by Benzbeeb

Fixed: #2444 

## Implementation details
Implement oracle scripts view table for track oracle script status

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-18 07:44 UTC, taobun requested changes

2020-08-18 07:44 UTC, taobun commented on flusher/flusher/init.py
> +        """CREATE VIEW oracle_script_statistics AS
Calculate on each oracle script and resolve status make more sense and limit calculate only latest (1, 3, 7 days)

2020-08-18 18:08 UTC, taobun approved these changes

2020-08-19 04:11 UTC, sorawit requested changes

2020-08-19 04:11 UTC, sorawit commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2452](https://github.com/bandprotocol/bandchain/pull/2452) Impelemented view table to calculate oracle script response time
typo

2020-08-19 06:56 UTC, sorawit approved these changes

2020-08-19 06:57 UTC, merged