Implement full copy non evm proof
bandprotocol/bandchain pull request #2455
Opened 2020-08-11 11:49 UTC by prin-r

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-16 08:08 UTC, evilpeach approved these changes

2020-08-18 07:26 UTC, tansawit requested changes

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{clientID: string, oracleScriptID: u64, calldata: bytes, askCount: u64, minCount: u64}/{_:u64}|j},
Use normal string here?

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{clientID: string, requestID: u64, ansCount: u64, requestTime: u64, resolveTime: u64, resolveStatus: u32, result: bytes}/{_:u64}|j},
ditto?

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{isDataOnRight: u8, subtreeHeight: u8, subtreeSize: u64, subtreeVersion: u64, siblingHash: bytes}/{_:u64}|j},
ditto

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{r: bytes, s: bytes, v: u8, signedPrefixSuffix: bytes, signedDataSuffix: bytes}/{_:u64}|j},
ditto

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +  | Signatures(list_of_tm_signatures) => {
rename/shorten to `tm_signatures`?

2020-08-18 07:26 UTC, tansawit commented on scan/src/utils/proof/NonEVMProof.re
> +  | IAVLMerklePaths(list_of_iavl_merkle_paths) => {
Rename/shorten to `iavl_merkle_paths`?

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{clientID: string, oracleScriptID: u64, calldata: bytes, askCount: u64, minCount: u64}/{_:u64}|j},
done

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{clientID: string, requestID: u64, ansCount: u64, requestTime: u64, resolveTime: u64, resolveStatus: u32, result: bytes}/{_:u64}|j},
done

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{isDataOnRight: u8, subtreeHeight: u8, subtreeSize: u64, subtreeVersion: u64, siblingHash: bytes}/{_:u64}|j},
done

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +        {j|{r: bytes, s: bytes, v: u8, signedPrefixSuffix: bytes, signedDataSuffix: bytes}/{_:u64}|j},
done

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +  | Signatures(list_of_tm_signatures) => {
done

2020-08-18 09:47 UTC, prin-r commented on scan/src/utils/proof/NonEVMProof.re
> +  | IAVLMerklePaths(list_of_iavl_merkle_paths) => {
done

2020-08-20 03:32 UTC, evilpeach commented
Can we merge after revamped GuanYu version done?

2020-08-21 14:17 UTC, evilpeach commented
@pzshine Can you check about design?

2020-08-21 16:09 UTC, tansawit approved these changes

2020-08-21 16:10 UTC, merged