cdb: Related data source and oracle script
bandprotocol/bandchain pull request #2475
Opened 2020-08-14 10:23 UTC by Benzbeeb

Fixed: #2443 

## Implementation details
Implement related ds os table for `bandchain/scan` can show information

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-18 07:47 UTC, taobun requested changes

2020-08-18 07:47 UTC, taobun commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2473](https://github.com/bandprotocol/bandchain/pull/2473) Implemented OWASM code tab for OC index page, improved some components
what?

2020-08-18 07:47 UTC, taobun commented on flusher/flusher/handler.py
> +            .on_conflict_do_update(constraint="related_data_source_oracle_scripts_pkey", set_=msg)
use `on_conflict_do_nothing` make more sense

2020-08-18 18:07 UTC, taobun approved these changes

2020-08-19 04:12 UTC, sorawit approved these changes

2020-08-19 05:04 UTC, merged