Bonded token amount with timestamp.
bandprotocol/bandchain pull request #2476
Opened 2020-08-14 13:51 UTC by Benzbeeb

Fixed: #2442

## Implementation details
Impelment table that store bonded token amount with timestamp.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-18 08:03 UTC, taobun requested changes

2020-08-18 08:03 UTC, taobun commented on flusher/flusher/db.py
> +shares_tracks = sa.Table(
historical_bonded_token_on_validators.

2020-08-18 08:03 UTC, taobun commented on flusher/flusher/db.py
> +    Column("shares_amount", sa.DECIMAL),
bonded_tokens

2020-08-18 08:03 UTC, taobun commented on flusher/flusher/handler.py
> +        if "delegator_shares" in msg.keys():
tokens

2020-08-18 08:03 UTC, taobun commented on flusher/flusher/db.py
> +    Column("last_update", CustomDateTime),
Remove it for now

2020-08-18 18:07 UTC, taobun requested changes

2020-08-18 18:07 UTC, taobun commented on flusher/flusher/handler.py
> +        self.conn.execute(validators.insert(), msg)
Why we removed the validator exited before update?

2020-08-19 04:14 UTC, sorawit requested changes

2020-08-19 04:14 UTC, sorawit commented on flusher/flusher/handler.py
> +        if "tokens" in msg.keys():
don't think `.keys()` is necessary

2020-08-19 08:38 UTC, taobun approved these changes

2020-08-19 08:39 UTC, sorawit approved these changes

2020-08-19 08:40 UTC, merged