Scan: implement request index page top part
bandprotocol/bandchain pull request #2501
Opened 2020-08-20 04:46 UTC by evilpeach

Fixed: #2430 

## Implementation details
- Request Info
- Calldata table
- Result table
- Proof
- External Data
- Support Mobile & Desktop

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-20 20:29 UTC, pzshine commented
![image](https://user-images.githubusercontent.com/17017699/90822330-79e98700-e35e-11ea-9f41-09e033f6c1a7.png)

I just checked on mobile screen and found only one point is about buttons.

2020-08-21 08:24 UTC, evilpeach commented
> ![image](https://user-images.githubusercontent.com/17017699/90822330-79e98700-e35e-11ea-9f41-09e033f6c1a7.png)
> 
> I just checked on mobile screen and found only one point is about buttons.

Do we change in this PR or make another PR for changing all button styles on mobile?

2020-08-21 08:50 UTC, pzshine requested changes

2020-08-21 08:50 UTC, pzshine commented on scan/src/pages/RequestIndexPage.re
> +             </div>
No need to use flexBox

2020-08-21 08:50 UTC, pzshine commented on scan/src/pages/RequestIndexPage.re
> +                   </div>
No need to use flexBox

2020-08-21 08:50 UTC, pzshine commented on scan/src/pages/RequestIndexPage.re
> +                   </div>
No need to use flexBox

2020-08-21 08:50 UTC, pzshine commented on scan/src/pages/RequestIndexPage.re
> +                   </div>
No need to use flexBox

2020-08-21 11:53 UTC, pzshine approved these changes

2020-08-21 12:28 UTC, merged