pyband: Auth module implementation
bandprotocol/bandchain pull request #2588
Opened 2020-08-30 19:09 UTC by taobun

Fixed: #2531 

## Implementation details
- Verify msg from public key.
- Check request status from chian.

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-08-31 03:13 UTC, sorawit requested changes

2020-08-31 03:13 UTC, sorawit commented on helpers/pyband/pyband/auth.py
> +REQUET_DURATION = 100
typo

2020-09-02 04:04 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (feat) [\#2588](https://github.com/bandprotocol/bandchain/pull/2577) pyband: Auth module implementation
It should be 2588, not 2577.

2020-09-14 02:17 UTC, sorawit approved these changes

2020-09-14 08:55 UTC, merged