Implement proof of validity and copy proof for Ethereum
bandprotocol/bandchain pull request #260
Opened 2020-01-16 15:34 UTC by prin-r

Fixes #199 
Fixes #200

2020-01-16 16:03 UTC, sorawit requested changes

2020-01-16 16:03 UTC, sorawit commented on scan/src/components/ProofTab.re
> +   var element = document.createElement('textarea');
What's the difference between using this vs using https://www.npmjs.com/package/clipboard-copy, similar to what we did in staking portal. 

Can you confirm the solution you are doing will work on all platforms?

2020-01-17 06:28 UTC, sorawit requested changes

2020-01-17 06:28 UTC, sorawit commented on scan/src/components/ProofTab.re
> +        evmProofBytes |> JsBuffer.toHex,
Why don't you send the `0x`  prefixed version here, so you don't need to do that conversion again.

2020-01-17 06:48 UTC, sorawit approved these changes
lgtm

2020-01-17 06:51 UTC, evilpeach approved these changes

2020-01-17 07:27 UTC, merged