add query height parameter from url
bandprotocol/bandchain pull request #2607
Opened 2020-09-03 10:25 UTC by prin-r

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-09-07 08:54 UTC, taobun requested changes

2020-09-07 08:54 UTC, taobun commented on chain/x/oracle/client/common/proof/proof.go
> +func GetProofHandlerFn(ctx context.CLIContext, route string) http.HandlerFunc {
We didn't rename this param

2020-09-08 08:56 UTC, prin-r commented on chain/x/oracle/client/common/proof/proof.go
> +func GetProofHandlerFn(ctx context.CLIContext, route string) http.HandlerFunc {
done

2020-09-09 09:53 UTC, taobun requested changes

2020-09-09 09:53 UTC, taobun commented on chain/x/oracle/client/common/proof/proof.go
> +		fmt.Println(requestIDs)
Remove this

2020-09-09 09:53 UTC, taobun commented on chain/x/oracle/client/common/proof/proof.go
> +			commit, err := ctx.Client.Commit(height)
Bring this to out of loop.

2020-09-09 09:53 UTC, taobun commented on chain/x/oracle/client/common/proof/proof.go
> +				} else if opType == "multistore" {
Only save this value to process later

2020-09-09 11:35 UTC, prin-r commented on chain/x/oracle/client/common/proof/proof.go
> +		fmt.Println(requestIDs)
done

2020-09-09 13:52 UTC, taobun approved these changes
LGTM

2020-09-09 13:54 UTC, merged