Scan: Wire up proposal vote
bandprotocol/bandchain pull request #2621
Opened 2020-09-08 12:47 UTC by pzshine

Fixed: #2615 

## Implementation details

- Wired up the data to proposal vote
  - Turnout rate on Proposal Homepage
  - Proposal Index page
    - Turnout rate on Turnout pie chart
    - VoteStat on result box.
- Fixed some typo
- Added optionInt to ID.re

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-09-10 13:56 UTC, evilpeach commented on scan/src/pages/AccountIndexPage.re
> +    <Col size=2.0>
Why we have to change this?

2020-09-10 13:59 UTC, evilpeach commented on scan/src/pages/ProposalIndexPage.re
> +
Why don't we declare it on `VoteSub`?

2020-09-10 14:57 UTC, evilpeach requested changes

2020-09-10 14:57 UTC, evilpeach commented on scan/src/pages/ProposalIndexPage.re
> +                   //TODO: will re-structure when the data is wired up.
remove?

2020-09-10 14:57 UTC, evilpeach commented on scan/src/pages/ProposalIndexPage.re
> +                                //TODO: wire up later
remove?

2020-09-10 14:59 UTC, evilpeach requested changes
Let's check https://d3n-scan-pr-2621.onrender.com/proposal/25. Why the percentage of abstain choice is 0?

2020-09-11 03:52 UTC, pzshine commented on scan/src/pages/AccountIndexPage.re
> +    <Col size=2.0>
Fixed the wrapped text

2020-09-11 12:51 UTC, evilpeach requested changes

2020-09-11 12:51 UTC, evilpeach commented on scan/src/subscriptions/VoteSub.re
> +    parsedData->getValVote(Yes) +. delVotes##non_validator_vote_proposals_view->getDelVote(Yes);
declare `delVotes##non_validator_vote_proposals_view` as variable

2020-09-11 12:51 UTC, evilpeach commented on scan/src/subscriptions/VoteSub.re
> +    totalYesPercent: totalYesPower != 0. ? totalYesPower /. totalPower *. 100. : 0.,
remove `totalYesPower` and friends

2020-09-11 12:51 UTC, evilpeach commented on scan/src/subscriptions/VoteSub.re
> +let getVoteStat = () => {
getVoteStats

2020-09-11 12:51 UTC, evilpeach commented on scan/src/subscriptions/VoteSub.re
> +    subscription ValidatorVoteByProposalID {
ValidatorVotes

2020-09-11 12:51 UTC, evilpeach commented on scan/src/subscriptions/VoteSub.re
> +    subscription DelegatorVoteByProposalID {
DelegatorVotes

2020-09-11 13:18 UTC, evilpeach approved these changes

2020-09-11 15:07 UTC, merged