icon: implement aggregator contract
bandprotocol/bandchain pull request #2632
Opened 2020-09-11 10:51 UTC by prin-r

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-09-23 08:06 UTC, sorawit requested changes

2020-09-23 08:06 UTC, sorawit commented on bridges/icon/std_reference_basic/std_reference_basic.py
> +        # Mapping from symbol to obi encoded ref data.
invalid comment?

2020-09-23 08:06 UTC, sorawit commented on bridges/icon/std_reference_basic/std_reference_basic.py
> +    def RefDataUpdate(self, _symbol: str, _rate: int, _last_update: int, _request_id: int):
do not index

2020-09-23 08:09 UTC, prin-r commented on bridges/icon/std_reference_basic/std_reference_basic.py
> +    def _get_reference_data(self, _pair: str) -> dict:
fix the param according to the specification

2020-09-23 10:19 UTC, prin-r commented on bridges/icon/std_reference_basic/std_reference_basic.py
> +        # Mapping from symbol to obi encoded ref data.
done

2020-09-25 07:37 UTC, sorawit approved these changes

2020-09-28 03:49 UTC, taobun approved these changes

2020-09-28 04:02 UTC, merged