Scan: Remove unused images and replace with icon.
bandprotocol/bandchain pull request #2695
Opened 2020-10-02 08:36 UTC by Pitchanai

Fixed: #2612

## Implementation details
- Remove unused images and replace with icon.

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-02 09:17 UTC, evilpeach requested changes

2020-10-02 09:17 UTC, evilpeach commented on scan/src/components/NavBar.re
>      let telegramLogo = style([width(`px(17))]);
remove unused styles

2020-10-02 09:17 UTC, evilpeach commented on scan/src/components/Header.re
> +                    <Icon name="fab fa-twitter" color=Colors.bandBlue size=16 />
Don't forget remove the unused style above.

2020-10-02 09:17 UTC, evilpeach commented on scan/src/components/Header.re
> -                    <img src=Images.telegramLogo className=Styles.telegramLogo />
Here as well.

2020-10-02 09:17 UTC, evilpeach commented on scan/src/components/ValidatorsTable.re
> -         <img src=Images.sortDown className={Styles.downIcon(false)} />;
remove unused styles

2020-10-02 10:57 UTC, pzshine commented
![image](https://user-images.githubusercontent.com/17017699/94916309-a99cba80-04d8-11eb-9256-7a53b028ad1b.png)

Can you wrap these social media with `<div>` and align center to them?

2020-10-03 11:59 UTC, evilpeach commented
@Pitchanai Please check the integration test.

2020-10-05 03:26 UTC, pzshine approved these changes

2020-10-05 04:11 UTC, evilpeach approved these changes
LGTM

2020-10-05 04:12 UTC, merged