create execWithTimeout function to execute command with specific timeout
bandprotocol/bandchain pull request #271
Opened 2020-01-20 04:55 UTC by prin-r

Fixes #19

2020-01-20 08:39 UTC, taobun commented on chain/cmd/provider/main.go
> +func execWithTimeout(command Command, timeoutInMiliSecond int64) ([]byte, error) {
MilliSecond

2020-01-20 09:50 UTC, sorawit approved these changes
LGTM. @taobun any comment?

2020-01-20 09:50 UTC, sorawit commented on chain/cmd/provider/main.go
> +var allowedCommands = map[string]bool{"curl": true, "ping": true}
Example of the workaround you need to do when a language is so stupid that it does not have `set`

2020-01-20 09:50 UTC, sorawit commented on chain/cmd/provider/main_test.go
> +	//sdk "github.com/cosmos/cosmos-sdk/types"
Remove this?

2020-01-20 09:50 UTC, sorawit requested changes
LGTM minus the minor comments. @taobun any comment?

2020-01-20 09:51 UTC, sorawit requested changes

2020-01-20 09:51 UTC, sorawit commented on chain/cmd/provider/main_test.go
> +func TestExecWithTimeoutSuccess(t *testing.T) {
We will see if all these tests cause the CI to be too slow. We can decide how to deal with that later if it ever becomes a problem.

2020-01-20 11:01 UTC, taobun requested changes

2020-01-20 11:01 UTC, taobun commented on chain/cmd/provider/main.go
> +		query, err := execWithTimeout(command, 3000)
Bring 3000 as global variable scope.

2020-01-20 16:45 UTC, sorawit commented
@prin-r the CI is failing on `TestExecWithTimeoutSuccess`

2020-01-21 03:40 UTC, taobun requested changes

2020-01-21 03:40 UTC, taobun commented on chain/cmd/provider/main.go
> +const LIMIT_TIMEOUT = 3 * time.Second
In go convention, private constant use lowerCamelCase. Therefore changed it to `limitTimeOut`

2020-01-21 05:58 UTC, taobun approved these changes
lgtm

2020-01-21 07:33 UTC, sorawit approved these changes

2020-01-21 08:06 UTC, merged