Implement query Band supply
bandprotocol/bandchain pull request #2719
Opened 2020-10-05 12:10 UTC by Pitchanai

Fixed: #2717 

## Implementation details
- Implement query band supply

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-06 05:51 UTC, evilpeach requested changes

2020-10-06 05:51 UTC, evilpeach commented on scan/src/rpc/PriceHook.re
> +        };
Let's use `Belt.Option.map` like this
```
let%Opt supply = supplyJson->Belt.Option.map(sp |> Js.Json.decodeNumber);
```

2020-10-06 05:51 UTC, evilpeach commented on scan/src/rpc/PriceHook.re
>      // TODO: Find the formular to calulate this
remove `TODO`

2020-10-06 05:51 UTC, evilpeach commented on scan/src/rpc/PriceHook.re
> +    let decode = (usdJson, btcJson, supplyJson) =>
change `supplyJson` to `circulatingSupply `

2020-10-06 05:51 UTC, evilpeach commented on scan/src/rpc/PriceHook.re
> +      let%Opt result = decode(usd, btc, supply);
Use `Belt.Option.map` also.

2020-10-06 05:51 UTC, evilpeach commented on scan/src/rpc/PriceHook.re
> +    let decode = (usdJson, btcJson, supplyJson) =>
name it as `circulatingSupply`

2020-10-06 07:21 UTC, evilpeach approved these changes

2020-10-06 12:01 UTC, evilpeach commented
@pzshine Please review this.

2020-10-07 04:28 UTC, pzshine approved these changes

2020-10-07 04:33 UTC, merged