Scan: Tx msg restructure
bandprotocol/bandchain pull request #2723
Opened 2020-10-05 15:31 UTC by pzshine

Fixed: #2682 

## Implementation details

- Refactor on `Msg.re`
- Made two Msg to be used as example
  - SendMsg
  - ReceiveMsg

**Note: If you pick the continue task**

- Please `checkout -b` from this branch
- Now there are separate Msg categories components as this image below.

![image](https://user-images.githubusercontent.com/17017699/95099090-af550300-0759-11eb-8808-04095c9edac8.png)

So I've already made the function for getting the badge color by each category on `MsgBadge.re`

- You have to consider these functions before working
  - `getCatVarientbyMsgType` for getting the Msg category
  - `getNameByMsgType` for for getting the string of Msg name 

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-08 12:12 UTC, Pitchanai approved these changes

2020-10-09 03:31 UTC, evilpeach requested changes

2020-10-09 03:31 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +               //TODO: will remove when doing the ravamp style
revamp

2020-10-09 08:53 UTC, evilpeach requested changes

2020-10-09 08:53 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2695](https://github.com/bandprotocol/bandchain/pull/2695) Remove unused images and replace with icon.
It's duplicated.

2020-10-09 08:53 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +    success ? msg->Belt.List.map(Msg.decodeAction) : msg->Belt.List.map(Msg.decodeFailAction);
Move ternary inside Belt.List.map

2020-10-09 08:53 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
>        let firstInput = tx.inputs |> Belt_List.getExn(_, 0);
Let's move these msg above the IBC and add todo

2020-11-16 02:12 UTC, evilpeach requested changes
1. Reduce margin bottom 
<img width="992" alt="Screen Shot 2563-11-16 at 09 00 02" src="https://user-images.githubusercontent.com/14128977/99205145-3500af80-27ea-11eb-9f85-8bdaf261c88e.png">

2020-11-16 06:44 UTC, evilpeach approved these changes

2020-11-16 06:45 UTC, merged