Scan: Revamp connect modal
bandprotocol/bandchain pull request #2727
Opened 2020-10-07 06:41 UTC by Pitchanai

Fixed: #2710 

## Implementation details
- Revamp connect modal

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-08 03:53 UTC, pzshine commented
![image](https://user-images.githubusercontent.com/17017699/95412921-52716c80-0954-11eb-8cdd-da71f86d7775.png)

Could you re-check the font-size that whether matches the mockup or not?

2020-10-08 04:36 UTC, pzshine requested changes

2020-10-08 04:36 UTC, pzshine commented on scan/src/components/modal/connect/ConnectModal.re
>        width(`px(480)),
I think we can remove this `width`

2020-10-08 04:36 UTC, pzshine commented on scan/src/components/modal/connect/ConnectModal.re
> +      <VSpacing size=Spacing.xl />
We can add `paddingTop` on Styles.innerContainer instead

2020-10-08 04:36 UTC, pzshine commented on scan/src/components/modal/connect/ConnectWithLedger.re
> +      padding4(~top=`px(0), ~left=`px(18), ~right=`px(18), ~bottom=`px(0)),
Can use `padding2` instead

2020-10-08 04:36 UTC, pzshine commented on scan/src/components/modal/connect/ConnectWithMnemonic.re
> +      padding4(~top=`px(0), ~left=`px(18), ~right=`px(18), ~bottom=`px(0)),
use `padding2` instead

2020-10-08 07:46 UTC, evilpeach requested changes

2020-10-08 07:46 UTC, evilpeach commented on scan/src/components/modal/connect/ConnectWithLedger.re
> +  let createLedger = aCcccountIndex => {
typo

2020-10-09 03:47 UTC, pzshine approved these changes

2020-10-21 09:49 UTC, evilpeach requested changes

2020-10-21 09:49 UTC, evilpeach commented on scan/src/components/EnhanceTxInput.re
> +
Can we replace `Loading` with `Loading2` ?

2020-10-21 09:49 UTC, evilpeach commented on scan/src/components/modal/connect/ConnectModal.re
>          {chainID == "band-wenchang-mainnet"
change it to `band-guanyu-mainnet`

2020-10-21 10:22 UTC, evilpeach requested changes

2020-10-21 10:22 UTC, evilpeach commented on scan/src/components/modal/connect/ConnectWithMnemonic.re
> +      padding2(~v=`px(0), ~h=`px(18)),
replace `px(0) with `zero

2020-10-22 04:25 UTC, evilpeach approved these changes
LGTM

2020-10-22 04:25 UTC, merged