Scan: Add delegate UI test
bandprotocol/bandchain pull request #2728
Opened 2020-10-07 09:13 UTC by Pitchanai

Fixed: #2703 

## Implementation details
- Add delegate UI test

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-08 12:16 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2728](https://github.com/bandprotocol/bandchain/pull/2728) Add delegation UI test
Let's combine it.

2020-10-08 12:16 UTC, evilpeach approved these changes

2020-10-08 12:19 UTC, pzshine requested changes

2020-10-08 12:19 UTC, pzshine commented on scan/cypress/integration/send_action.spec.js
> +      '[id="nav-/validator/bandvaloper1j9vk75jjty02elhwqqjehaspfslaem8pr20qst#reports"]'
Can we remove `/` from every IDs?

2020-10-09 03:50 UTC, pzshine approved these changes

2020-10-09 03:51 UTC, merged