Scan: Add UI test for all pages
bandprotocol/bandchain pull request #2740
Opened 2020-10-08 12:05 UTC by Pitchanai

Fixed: #2709 

## Implementation details
- Add UI test for all pages

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-09 03:56 UTC, pzshine requested changes

2020-10-09 03:56 UTC, pzshine commented on scan/cypress/integration/all_pages.spec.js
> +          '[id="latestTransactionsSectionHeader"] > div:nth-of-type(1) > span:nth-of-type(1)'
Can we use `h2` instead to all of the selectors which related to this?

2020-10-14 04:32 UTC, evilpeach approved these changes

2020-10-14 04:34 UTC, pzshine approved these changes

2020-10-14 04:34 UTC, merged