Scan: Validator and proposal message restructure
bandprotocol/bandchain pull request #2742
Opened 2020-10-09 13:39 UTC by Pitchanai

Fixed: #2699 
Fixed: #2700 

## Implementation details
- Restructure validator message
- Restructure proposal message

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-12 10:30 UTC, pzshine approved these changes

2020-10-14 04:03 UTC, pzshine commented
Could you wire up the data(moniker, proposalname, etc)?

2020-10-14 07:09 UTC, evilpeach requested changes

2020-10-14 07:09 UTC, evilpeach commented on scan/src/components/msgs/Msg.re
> +     | AddReporterMsgSuccess({validator, reporter}) => <ValidatorMsg.AddReporter reporter />
validator?

2020-10-14 07:09 UTC, evilpeach commented on scan/src/components/msgs/ProposalMsg.re
> +      // TODO: Proposal ID
Let's implement it.

2020-10-15 09:17 UTC, evilpeach requested changes

2020-10-15 09:17 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +    };
It's duplicated.

2020-10-15 09:17 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
> +      Js.log(json);
remove log

2020-10-15 09:17 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
>      | VoteMsgFail(vote) => vote.voterAddress
Why do you change it?

2020-10-18 17:40 UTC, evilpeach commented on scan/src/subscriptions/TxSub.re
>      | VoteMsgFail(vote) => vote.voterAddress
@Pitchanai

2020-10-22 04:24 UTC, pzshine requested changes

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
The `mb` should be removed, there is extra space on the bottom of box.

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
The `mb` should be removed, there is extra space on the bottom of box.

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please remove `mb`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexProposalMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please replace `mb` with `mbSm` to apply the marginbottom only on mobile screen

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexProposalMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please remove `mb`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexProposalMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please replace `mb` with `mbSm` to apply the marginbottom only on mobile screen

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexProposalMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please remove `mb`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
The default `col` is `Col.Twelve`, so we can use `<Col.Grid>`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
The default `col` is `Col.Twelve`, so we can use `<Col.Grid>`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
Please remove `mb`, and `col=Col.Twelve`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Twelve mb=24>
The default `col` is `Col.Twelve`, so we can use `<Col.Grid>`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please replace `mb` with `mbSm`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six mb=24>
Please remove `mb`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six>
Please add `mbSm`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six>
Please add `mbSm`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six>
Please add `mbSm`

2020-10-22 04:24 UTC, pzshine commented on scan/src/components/tx-index/IndexValidatorMsg.re
> +      <Col.Grid col=Col.Six>
Please add `mbSm`

2020-11-11 12:15 UTC, pzshine approved these changes

2020-11-11 12:16 UTC, merged