Scan: patch for fast-sync db and guanyu migration db
bandprotocol/bandchain pull request #2747
Opened 2020-10-12 09:32 UTC by evilpeach

## Implementation details
- patch subscription for fast sync DB and new GuanYu DB

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-12 10:55 UTC, pzshine requested changes

2020-10-12 10:55 UTC, pzshine commented on scan/src/components/request/DataReports.re
> +            {reportValidator: {operatorAddress, moniker, identity}, transaction, reportDetails},
Can you change `transaction` to `optTransaction`?

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +          sender
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +               sender
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +          sender
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +               sender: y##sender->Belt.Option.getExn->Address.fromBech32,
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +               sender: y##sender->Belt.Option.getExn->Address.fromBech32,
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +        sender
Change it into `addressExn` from `GraphQLParser`

2020-10-12 10:55 UTC, pzshine commented on scan/src/subscriptions/RequestSub.re
> +        sender
Change it into `addressExn` from `GraphQLParser`

2020-10-12 14:30 UTC, pzshine approved these changes
Good to go!

2020-10-14 04:01 UTC, Pitchanai approved these changes

2020-10-14 04:12 UTC, merged