Set up code execution timeout, both for prepare and execution
bandprotocol/bandchain pull request #275
Opened 2020-01-20 10:40 UTC by prin-r

Fixes #137

2020-01-21 03:40 UTC, sorawit requested changes
@prin-r Change on prepare function?

2020-01-21 03:40 UTC, sorawit commented on chain/wasm/wasm.go
> +	return res.ptr, res.err
Do we need to kill the wasm process, or does everything get killed automatically?

2020-01-21 03:52 UTC, taobun requested changes

2020-01-21 03:52 UTC, taobun commented on chain/wasm/wasm.go
> +	ptr, err := executeWithTimeout(fn, paramsInput, wasmInput, 100*time.Millisecond)
0.1 sec is too fast. I think 3 seconds still fine

2020-01-21 09:11 UTC, evilpeach commented on chain/wasm/wasm.go
> +		chanWasmOutput <- wasmOutput{ptr: ptr, err: err}
use `chanWasmOutput <- wasmOutput{ptr,err}` instead ?

2020-01-22 04:27 UTC, sorawit requested changes

2020-01-22 04:27 UTC, sorawit commented on chain/wasm/wasm.go
> +func executeWithTimeout(limitTimeout time.Duration, inst wasm.Instance, funcName string, args ...interface{}) (wasm.Value, error) {
Let's pass around instance pointer: https://github.com/wasmerio/go-ext-wasm/blob/master/wasmer/instance.go#L51

2020-01-22 04:40 UTC, taobun approved these changes

2020-01-22 04:43 UTC, sorawit approved these changes

2020-01-22 05:49 UTC, merged