owasm: Make result a data structure
bandprotocol/bandchain pull request #276
Opened 2020-01-20 14:12 UTC by taobun

fixed #202 

- Declare new macro to specific result structure
- Export new function to get result info and parse result
- Update script, request endpoint to show result info and parsed result

2020-01-20 16:43 UTC, sorawit requested changes
Looks good overall. I see that the CI is failing. Can you confirm why / fix it?

2020-01-20 16:43 UTC, sorawit commented on owasm/src/macros.rs
> +/// use serde::{Deserialize, Serialize};
Why is this necessary? Can't we `use` inside of the macro?

2020-01-21 10:22 UTC, sorawit approved these changes
LGTM. @evilpeach Please note the API change.

2020-01-21 10:22 UTC, sorawit commented on chain/x/zoracle/internal/types/querier.go
> +	ParamsRaw   []byte            `json:"paramsRaw"`
@evilpeach Note this field change. Will need to update `scan` once this is live.

2020-01-21 10:46 UTC, evilpeach approved these changes

2020-01-21 12:24 UTC, merged