Scan: Revamp undelegate and redelegate modal
bandprotocol/bandchain pull request #2766
Opened 2020-10-16 05:58 UTC by Pitchanai

Fixed: #2733 
Fixed: #2735 

## Implementation details
- Revamp undelegate modal
- Revamp redelegate modal

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-16 09:56 UTC, pzshine requested changes

2020-10-16 09:56 UTC, pzshine commented on scan/src/components/modal/ValidatorStakingInfo.re
> +      height(`px(41)),
change it to `minHeight`

2020-10-18 17:26 UTC, evilpeach approved these changes
Looks good!

2020-10-20 04:40 UTC, pzshine approved these changes

2020-10-20 04:40 UTC, merged