Scan: Revamp every state of confirmation popup
bandprotocol/bandchain pull request #2784
Opened 2020-10-20 07:35 UTC by pzshine

Fixed: #2738 

## Implementation details

- Implemented the confirmation modal
  - JSON preview
  - Success/Fail status
  - Loading state

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-20 12:18 UTC, evilpeach requested changes

2020-10-20 12:18 UTC, evilpeach commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +      <Text value="Connect with your wallet" weight=Text.Medium size=Text.Xl />
Is it correct?

2020-10-20 12:18 UTC, evilpeach commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +               value="View Detail"
View Details?

2020-10-21 04:20 UTC, Pitchanai requested changes

2020-10-21 04:20 UTC, Pitchanai commented on scan/cypress/integration/send_action.spec.js
> +    cy.get('[id="broadcastButton"] > button').wait(1000).click();
Could you change the `id` to `broadcastButtonContainer`?

2020-10-21 04:20 UTC, Pitchanai commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +         />
Could you add a `font-family` to `<textarea />` to match the design?

2020-10-21 04:20 UTC, Pitchanai commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +  let modalTitle = style([paddingBottom(`px(16))]);
Please change the `padding-bottom` to `24px`.

2020-10-21 04:20 UTC, Pitchanai commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +           <Text value="Broadcast Transaction Success" size=Text.Lg block=true align=Text.Center />
Please check that the message not match with the design and don't have to be all caps.

2020-10-21 04:20 UTC, Pitchanai commented on scan/src/components/modal/submitTx/PreviewJsonStep.re
> +           <Text value="Broadcast Transaction Success" size=Text.Lg block=true align=Text.Center />
This one too.

2020-10-21 04:39 UTC, Pitchanai approved these changes

2020-10-21 08:17 UTC, evilpeach approved these changes

2020-10-21 08:17 UTC, merged