Scan: Remove unused dependencies
bandprotocol/bandchain pull request #2788
Opened 2020-10-21 10:05 UTC by Pitchanai

Fixed: #2752 

## Implementation details
- Remove unused dependencies

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-04 03:42 UTC, evilpeach commented
@Pitchanai Please fix the conflict.

2020-12-02 09:27 UTC, pzshine requested changes

2020-12-02 09:27 UTC, pzshine commented on CHANGELOG_UNRELEASED.md
> +- (feat) [\#2594](https://github.com/bandprotocol/bandchain/pull/2594) Added meta og tag to scan
Remove all except #2788

2020-12-03 05:39 UTC, evilpeach requested changes

2020-12-03 05:39 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> -- (feat) [\#2854](https://github.com/bandprotocol/bandchain/pull/2854) Implement reinvest
Please don't remove it

2020-12-16 10:15 UTC, pzshine approved these changes

2020-12-16 10:18 UTC, evilpeach approved these changes

2020-12-16 10:18 UTC, merged