Scan: Remove redundant loading component
bandprotocol/bandchain pull request #2790
Opened 2020-10-21 13:45 UTC by Pitchanai

Fixed: #1556 

## Implementation details
- Remove redundant loading component

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-28 06:56 UTC, evilpeach requested changes
Please fix the conflict.

2020-10-28 06:56 UTC, evilpeach commented on scan/src/components/data-source/DataSourceExecute.re
> +  <div className={Styles.withWH(wDiv, h)}> <Loading width=wImg height=h /> </div>;
Can we remove `<div>`?

2020-10-28 06:56 UTC, evilpeach commented on scan/src/components/Loading.re
> +      height(h),
IMO, we can use only the width. The height will be adjusted automatically.

2020-12-02 09:26 UTC, pzshine requested changes

2020-12-02 09:26 UTC, pzshine commented on CHANGELOG_UNRELEASED.md
> +- (feat) [\#2594](https://github.com/bandprotocol/bandchain/pull/2594) Added meta og tag to scan
Remove all except #2790

2020-12-16 09:56 UTC, evilpeach approved these changes

2020-12-16 09:57 UTC, pzshine approved these changes

2020-12-16 09:58 UTC, merged