Scan: Remove legacy row and column
bandprotocol/bandchain pull request #2793
Opened 2020-10-22 09:45 UTC by Pitchanai

Fixed: #2774 

## Implementation details
- Remove legacy row and column

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-22 09:49 UTC, Pitchanai commented
I'm waiting for the other branch to continue removing legacy row and column.

2020-12-02 09:18 UTC, pzshine approved these changes

2020-12-02 09:37 UTC, evilpeach requested changes

2020-12-02 09:37 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (feat) [\#2594](https://github.com/bandprotocol/bandchain/pull/2594) Added meta og tag to scan
Just add 2793

2020-12-02 09:37 UTC, evilpeach commented on scan/src/components/TxIndexPageTable.re
> +  React.null;
It should be rendered and please capitalize "UNKNOWN MESSAGE"

2020-12-08 12:46 UTC, evilpeach approved these changes

2020-12-08 12:46 UTC, merged