Pyband: Refactor and wrote tests for client and send_tx
bandprotocol/bandchain pull request #2807
Opened 2020-10-30 05:10 UTC by pzshine

## Implementation details

- Refactor the client module
  -  Changed the way to send tx to be separated by mode
   - `send_tx_sync_mode`
   - `send_tx_async_mode`
   - `send_tx_block_mode`
- Added new dataclasses on data module
  - `TransactionSyncMode`
  - `TransactionAsyncMode`
  - `TransactionBlockMode`
- Added new test cases for the client api

**Note:** About `get_latest_block`, it will be on the other pr.

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-10-30 08:34 UTC, evilpeach requested changes

2020-10-30 08:34 UTC, evilpeach commented on helpers/pyband/pyband/client.py
> +from pyband.transaction import Transaction
Is it used?

2020-10-30 08:34 UTC, evilpeach commented on helpers/pyband/tests/client/send_tx_test.py
> +    )
add new line

2020-11-02 10:02 UTC, taobun requested changes

2020-11-02 10:02 UTC, taobun commented on helpers/pyband/pyband/data.py
> +    tx_hash: str
Add code and log.

2020-11-05 05:17 UTC, taobun approved these changes
LGTM

2020-11-05 06:13 UTC, sorawit requested changes

2020-11-05 06:13 UTC, sorawit commented on helpers/pyband/pyband/client.py
> +            log = data["logs"]
Let's make `log` / `error_log` order consistent with the `if` block above

2020-11-05 06:13 UTC, sorawit commented on helpers/pyband/pyband/data.py
> +    tx_hash: str
should `tx_hash` be `str` or `bytes`?

2020-11-05 06:43 UTC, sorawit approved these changes
Looks good

2020-11-05 06:50 UTC, evilpeach approved these changes

2020-11-05 06:50 UTC, merged