Make nodes in multi validator genesis have different monikers
bandprotocol/bandchain pull request #282
Opened 2020-01-20 18:23 UTC by prin-r

Fixes #242

2020-01-21 01:00 UTC, sorawit commented
How did you test this change?

2020-01-22 04:42 UTC, taobun approved these changes

2020-01-22 04:43 UTC, taobun requested changes

2020-01-22 04:43 UTC, taobun commented on chain/docker-config/generate-genesis.sh
> +
Remove temp file after used

2020-01-22 04:45 UTC, sorawit submitted a review, later dismissed
Looks great!

2020-01-22 07:16 UTC, evilpeach approved these changes
LGTM

2020-01-22 09:10 UTC, taobun approved these changes
lgtm

2020-01-22 09:11 UTC, sorawit approved these changes
Looks good!

2020-01-22 10:06 UTC, merged