Pyband: Add msg send
bandprotocol/bandchain pull request #2830
Opened 2020-11-04 09:26 UTC by Pitchanai

Fixed: #2816 

## Implementation details
- Add msg send

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-04 09:46 UTC, evilpeach requested changes

2020-11-04 09:46 UTC, evilpeach commented on helpers/pyband/pyband/message.py
> +
validate coin?

2020-11-04 09:46 UTC, evilpeach commented on helpers/pyband/tests/message_send_test.py
> +        [x.validate() for x in msg_send.amount]
It should test like this 
```python
with pytest.raises(ValueError, match="Expect amount more than 0"):
     msg_send.validate()
```

2020-11-04 09:46 UTC, evilpeach commented on helpers/pyband/tests/message_send_test.py
> +    assert [x.validate() for x in msg_send.amount] == [True]
remove

2020-11-04 10:11 UTC, evilpeach requested changes

2020-11-04 10:11 UTC, evilpeach commented on helpers/pyband/pyband/message.py
> +        [x.validate() for x in self.amount]
```
for x in self.amount:
    x.validate()
```

2020-11-04 10:42 UTC, taobun requested changes

2020-11-04 10:42 UTC, taobun commented on helpers/pyband/pyband/message.py
> +        for x in self.amount:
for coin in self.amount

2020-11-05 03:51 UTC, evilpeach approved these changes

2020-11-05 06:33 UTC, taobun approved these changes

2020-11-05 07:20 UTC, merged