Pyband: add message delegate
bandprotocol/bandchain pull request #2835
Opened 2020-11-05 07:53 UTC by Pitchanai

Fixed: #2817 

## Implementation details
- Add message delegate

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-06 07:50 UTC, evilpeach requested changes

2020-11-06 07:50 UTC, evilpeach commented on helpers/pyband/pyband/message.py
> +        return True
add end line. Did you use black?

2020-11-09 04:23 UTC, evilpeach approved these changes

2020-11-10 11:16 UTC, taobun approved these changes

2020-11-12 04:01 UTC, merged