Scan: Implement reinvest
bandprotocol/bandchain pull request #2854
Opened 2020-11-10 07:57 UTC by Pitchanai

Fixed: #2770 

## Implementation details
- Implement reinvest

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-12 07:10 UTC, pzshine requested changes

2020-11-12 07:10 UTC, pzshine commented on scan/src/components/modal/ValidatorStakingInfo.re
> +      );
Could you change the code format to

```
 let reinvest = () =>
    (
      validatorAddress,
      switch (balanceAtStakeSub) {
      | Data({reward: {amount}}) => amount
      | _ => 0.
      },
    )
    ->SubmitMsg.Reinvest
    ->SubmitTx
    ->OpenModal
    ->dispatchModal;



```

2020-11-13 08:25 UTC, evilpeach requested changes

2020-11-13 08:25 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2854](https://github.com/bandprotocol/bandchain/pull/2854) Implement reinvest
feat

2020-11-13 08:25 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +              </Button>
1. Let's move switch on allSub above the `<div>` like this.
2. Pass the amount to reinvest function.
```
{switch(allSub) {
     | Data((_, balanceAtStake, _)) => {
          let disable = balanceAtStake.reward.amount <= 0.;
          <div className={CssHelper.flexBox()} id="withdrawRewardContainer">
               // render 2 button here and use disable variable.
          </div>
     }
     | _ => 
           <div className={CssHelper.flexBox()}>
               // render 2 button here and set disable as true
          </div>
     }
}}
```

2020-11-13 08:25 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +    let reinvest = () =>
pass amount as parameter

2020-11-13 08:25 UTC, evilpeach commented on scan/src/components/modal/submitTx/ReinvestMsg.re
> +          {amount: amountValue |> Js.Float.toFixedWithPrecision(~digits=0), denom: "uband"},
I guess this function will automatically round up if the remainder is more than 5. So, I think you have to use `amountValue->Js.Math.floor_float->Js.Float.toString` to do it.

2020-11-30 08:14 UTC, evilpeach approved these changes

2020-11-30 08:16 UTC, pzshine approved these changes

2020-11-30 08:40 UTC, merged