Scan: Implement all `with_*` methods on Transaction module
bandprotocol/bandchain pull request #2862
Opened 2020-11-11 09:43 UTC by Pitchanai

Fixed: #2842 

## Implementation details
- Implement all `with_*` methods on Transaction module

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-13 07:42 UTC, evilpeach requested changes

2020-11-13 07:42 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/transaction.test.ts
> +})
add end line

2020-11-13 07:42 UTC, evilpeach commented on helpers/bandchain2.js/src/transaction.ts
> +}
add end line

2020-11-13 07:42 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2862](https://github.com/bandprotocol/bandchain/pull/2862) bandchain.js: Implement `getSignData`, `getTxData` and all `with_*` methods on Transaction module
change to feat

2020-11-13 07:42 UTC, evilpeach commented on helpers/bandchain2.js/package-lock.json
> +  "name": "bandchain2.js",
remove this file!

2020-11-13 07:42 UTC, evilpeach commented on helpers/bandchain2.js/src/index.ts
> +export { default as Transaction } from './transaction'
1. add end line
2. Can it use `export Transaction from './transaction'` ?

2020-11-13 07:42 UTC, evilpeach commented on helpers/bandchain2.js/src/transaction.ts
> +import {Msg} from './message'
Please use formatter

2020-11-15 06:51 UTC, evilpeach reviewed
Have you tested it on react app?

2020-11-15 17:59 UTC, pzshine requested changes

2020-11-15 17:59 UTC, pzshine commented on helpers/bandchain2.js/src/transaction.ts
> +    // TODO: Validate Msgs
Is this finished already? If yes, please remove the comment

2020-11-15 18:14 UTC, evilpeach requested changes

2020-11-15 18:14 UTC, evilpeach commented on helpers/bandchain2.js/package.json
> +    "buffer": "^6.0.2",
I think It's no need to install it because the other lib already use it.

2020-11-15 18:14 UTC, evilpeach commented on helpers/bandchain2.js/src/transaction.ts
> +  sequence?: number
Do we use Big number? @pzshine

2020-11-16 08:18 UTC, pzshine approved these changes

2020-11-16 08:26 UTC, evilpeach approved these changes

2020-11-16 08:26 UTC, merged