Bandchain.js: Add github action
bandprotocol/bandchain pull request #2863
Opened 2020-11-11 10:22 UTC by Pitchanai

Fixed: #2839 

## Implementation details
- Add Github action

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-12 04:26 UTC, evilpeach approved these changes
LGTM

2020-11-13 03:57 UTC, pzshine requested changes

2020-11-13 03:57 UTC, pzshine commented on .github/workflows/bandchainjs.yaml
> +        run: yarn test
Can you add node module cached to this flow?

2020-11-13 07:00 UTC, pzshine approved these changes

2020-11-13 07:00 UTC, tansawit approved these changes

2020-11-13 07:23 UTC, merged