Pyband: Implemented get_price_symbols to client module
bandprotocol/bandchain pull request #2883
Opened 2020-11-16 07:36 UTC by pzshine

Fixed: #2882 

## Implementation details

- Implemented get_price_symbols to the client module including test case

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-16 09:05 UTC, evilpeach requested changes

2020-11-16 09:05 UTC, evilpeach commented on helpers/pyband/pyband/client.py
>      def get_reporters(self, validator: str) -> list:
Let's use `List[str]` as well.

2020-11-17 05:44 UTC, evilpeach approved these changes

2020-11-17 07:39 UTC, taobun approved these changes

2020-11-18 08:27 UTC, merged