Bandchain.js: Implement MsgRequest
bandprotocol/bandchain pull request #2885
Opened 2020-11-16 08:45 UTC by Pitchanai

Fixed: #2818 

## Implementation details
- Implement MsgRequest

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-17 05:48 UTC, evilpeach requested changes

2020-11-17 05:48 UTC, evilpeach commented on helpers/bandchain2.js/src/message.ts
> +    this.calldata = Buffer.from(calldata, 'hex')
User should pass `calldata` as Buffer type instead of hex string

2020-11-17 10:34 UTC, pzshine approved these changes

2020-11-18 08:43 UTC, evilpeach requested changes

2020-11-18 08:43 UTC, evilpeach commented on helpers/bandchain2.js/src/message.ts
> +    // this.amount.validate()
Let's validate it both MsgSend and MsgDelegate.

2020-11-20 05:58 UTC, evilpeach requested changes

2020-11-20 05:58 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  asJson(): object {
```
asJson(): {amount: string, denom: string} {
...
}
```

2020-11-20 05:59 UTC, pzshine approved these changes

2020-11-20 06:51 UTC, evilpeach requested changes

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/message.test.ts
> +  const sender_addr = Address.fromAccBech32(
camel case

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/message.test.ts
> +    const msgRequest = new MsgRequest(1, calldata, 2, 2, memo, sender_addr)
camel case

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/message.test.ts
> +describe('MsgSend', () => {
fail case?

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  }
create unit test for Coin

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/message.test.ts
> +describe('MsgDelegate', () => {
fail case?

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/src/message.ts
> +    if (this.calldata.length > constants.MAX_LENGTH)
Let's use MAX_DATA_SIZE = 256

2020-11-20 06:51 UTC, evilpeach commented on helpers/bandchain2.js/src/message.ts
> +        `invalida askCount got: minCount: ${this.minCount}, askCount: ${this.askCount}`,
typo -> invalida

2020-11-20 09:16 UTC, evilpeach requested changes

2020-11-20 09:16 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +    if (this.denom.length == 0) throw Error('Expect denom')
===

2020-11-20 09:23 UTC, evilpeach approved these changes

2020-11-21 04:41 UTC, merged