Bandchain.js: sendtx
bandprotocol/bandchain pull request #2899
Opened 2020-11-18 06:11 UTC by Pitchanai

Fixed: #2888 

## Implementation details
- Send tx

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-23 06:27 UTC, pzshine requested changes

2020-11-23 06:27 UTC, pzshine commented on helpers/bandchain2.js/src/client.ts
> +  private async post(path: string, param: object) {
Can you change `param` -> `option`?

2020-11-23 06:27 UTC, pzshine commented on helpers/bandchain2.js/src/client.ts
> +    const response = await axios.post(`${this.rpcUrl}${path}`, param)
Here as well

2020-11-23 06:27 UTC, pzshine commented on helpers/bandchain2.js/src/client.ts
> +    const response = await this.post(`${path}`, param)
please change here too

2020-11-23 06:32 UTC, evilpeach requested changes

2020-11-23 06:32 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/client/sendTx.test.ts
> +// let client = new Client(MASTER)
remove

2020-11-23 06:32 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/client/sendTx.test.ts
> +// import { jsxText } from '@babel/types'
remove?

2020-11-23 06:32 UTC, evilpeach commented on helpers/bandchain2.js/src/client.ts
> +  private async postResult(path: string, param: object) {
data

2020-11-23 06:32 UTC, evilpeach commented on helpers/bandchain2.js/src/client.ts
> +    const response = await this.post(`${path}`, param)
Let's use data instead of param

2020-11-23 07:16 UTC, evilpeach requested changes

2020-11-23 07:16 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  updated: ReferenceDataUpdated
updatedAt

2020-11-23 07:16 UTC, evilpeach commented
@Pitchanai Please resolve the conflict

2020-11-23 11:37 UTC, pzshine approved these changes

2020-11-23 16:44 UTC, evilpeach requested changes

2020-11-23 16:44 UTC, evilpeach commented on helpers/bandchain2.js/src/client.ts
> +  // }
???

2020-11-24 05:06 UTC, evilpeach approved these changes

2020-11-24 05:46 UTC, merged