Bandchain.js: Add getLatestBlock
bandprotocol/bandchain pull request #2901
Opened 2020-11-18 08:54 UTC by Pitchanai

## Implementation details
- Add getLatestBlock

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-19 10:25 UTC, evilpeach requested changes

2020-11-19 10:25 UTC, evilpeach commented on helpers/bandchain2.js/__tests__/client/client.test.ts
> +          evidenceHash: Buffer.from('', 'hex'),
Just use `Buffer.from('')`

2020-11-20 07:13 UTC, evilpeach requested changes

2020-11-20 07:13 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  time: Timestamp
EpochTime

2020-11-20 07:42 UTC, evilpeach approved these changes

2020-11-20 07:43 UTC, pzshine approved these changes

2020-11-20 07:44 UTC, merged