Bandchain.js: add getAccount
bandprotocol/bandchain pull request #2905
Opened 2020-11-18 12:07 UTC by Pitchanai

## Implementation details
- Add getAccount

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-19 03:32 UTC, evilpeach requested changes

2020-11-19 03:32 UTC, evilpeach commented on helpers/bandchain2.js/src/client.ts
> +    console.log(response)
remove log

2020-11-19 06:55 UTC, evilpeach requested changes

2020-11-19 06:55 UTC, evilpeach commented on helpers/bandchain2.js/src/client.ts
> +      coins: value.coins.map((c: any) => new Coin(c.amount, c.denom)),
`c: {amount: number, denom: string}`

2020-11-19 06:55 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  accountNumber: Number
number

2020-11-20 03:54 UTC, evilpeach approved these changes

2020-11-20 03:54 UTC, evilpeach commented on helpers/bandchain2.js/src/data.ts
> +  accountNumber: Number
number

2020-11-20 03:56 UTC, pzshine approved these changes

2020-11-20 03:57 UTC, merged