Make provider run command inside of docker
bandprotocol/bandchain pull request #291
Opened 2020-01-21 12:24 UTC by taobun

- Add docker to `band-validator` image
- Provider run `docker run` instead of call directly as sub process

2020-01-21 12:30 UTC, evilpeach commented on chain/Dockerfile
> +    curl docker.io\
`curl docker.io \` add more space

2020-01-21 12:30 UTC, sorawit requested changes

2020-01-21 12:30 UTC, sorawit commented on docker-provider/Dockerfile
> +FROM alpine:3.7
`chain/images/provider-vm/Dockerfile`?

2020-01-21 12:32 UTC, evilpeach commented on docker-provider/Dockerfile
> +    apk add curl && \
apk add --no-cache

2020-01-21 12:48 UTC, evilpeach approved these changes

2020-01-22 06:22 UTC, sorawit reviewed
LGTM. @prin-r Please review this change.

2020-01-22 07:14 UTC, prin-r approved these changes

2020-01-22 07:18 UTC, sorawit approved these changes

2020-01-22 07:49 UTC, merged