Bandchain.js: Add return undefined when account does not exist
bandprotocol/bandchain pull request #2943
Opened 2020-11-27 07:48 UTC by Pitchanai

## Implementation details
- Add return `undefined` when account does not exist

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [x] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-11-30 10:14 UTC, evilpeach requested changes

2020-11-30 10:14 UTC, evilpeach commented on helpers/bandchain2.js/src/transaction.ts
> +    if (!account) throw Error('Account is existed yet.')
Account doesn't exist.

2020-12-01 11:52 UTC, evilpeach requested changes

2020-12-01 11:52 UTC, evilpeach commented on CHANGELOG_UNRELEASED.md
> +- (impv) [\#2941](https://github.com/bandprotocol/bandchain/pull/2943) Bandchain.js: Added return `undefined` when account does not exist
It's duplicated

2020-12-08 05:45 UTC, evilpeach approved these changes

2020-12-08 13:44 UTC, pzshine approved these changes

2020-12-08 13:45 UTC, merged