Implement standard library for alphavantage
bandprotocol/bandchain pull request #298
Opened 2020-01-22 08:24 UTC by prin-r

Fixes #168

2020-01-23 03:36 UTC, evilpeach commented
let's rebase and push again.

2020-01-23 05:04 UTC, sorawit requested changes
Let's make this work for stocks as well

2020-01-23 11:47 UTC, taobun requested changes

2020-01-23 11:47 UTC, taobun commented on owasm/src/ext/crypto/alphavantage.rs
> +        Some(parsed["Global Quote"]["05. price"].as_str()?.parse::<f32>().ok()?)
Can we write as `parsed["Global Quote"]["05. price"].as_str()?.parse::<f32>().ok()`

2020-01-23 11:47 UTC, taobun commented on owasm/example/src/lib.rs
> +        assert_eq!(new_params.alphavantage_api_key, String::from("some_key"));
Check `alphavantage_symbol` too

2020-01-23 11:47 UTC, taobun commented on owasm/src/ext/crypto/alphavantage.rs
> +        assert_eq!(
Fix ja

2020-01-24 03:34 UTC, sorawit submitted a review, later dismissed
LGTM

2020-01-24 06:49 UTC, taobun requested changes

2020-01-24 06:49 UTC, taobun commented on owasm/example/src/logic.rs
> +        println!("Current GOOG price (times 100) is {:?}", execute(vec![data]));
This line want to test GOOG current price? but your execute function will average eth price and goog price. That is the thing you want to test?

2020-01-24 07:50 UTC, taobun submitted a review, later dismissed

2020-01-24 09:52 UTC, sorawit requested changes

2020-01-24 09:52 UTC, sorawit commented on owasm/src/ext/crypto/mod.rs
> +pub mod alphavantage;
Why is this in `crypto`, but the yahoo thing is on a different folder? Shouldn't this be in the other folder too since it's not intended for crypto?

2020-01-24 10:04 UTC, sorawit submitted a review, later dismissed

2020-01-25 07:32 UTC, sorawit approved these changes

2020-01-27 03:38 UTC, taobun approved these changes

2020-01-27 03:52 UTC, merged