Implement rust binary to convert JSON parameters into hex
bandprotocol/bandchain pull request #299
Opened 2020-01-22 13:46 UTC by taobun

fixed #288 

After build, you will get `parser` binary
```
./parser serialized_params.wasm {\"symbol\":\"ETH\"}
```

2020-01-23 03:09 UTC, sorawit requested changes
Looks good minus the minor comment

2020-01-23 03:09 UTC, sorawit commented on owasm/example/src/lib.rs
> +pub fn __serialized_params(json_ptr: u64) -> u64 {
let's call this `__serialize_params`.

2020-01-24 08:35 UTC, smiled0g approved these changes

2020-01-24 08:47 UTC, sorawit approved these changes

2020-01-24 08:48 UTC, merged