Implement random library based on qrng.anu.edu.au
bandprotocol/bandchain pull request #300
Opened 2020-01-22 14:52 UTC by prin-r

Fixes #265

2020-01-23 03:07 UTC, sorawit requested changes

2020-01-23 03:07 UTC, sorawit commented on owasm/src/ext/random/qrng_anu.rs
> +        if bytes.len() as u8 == self.size {
Will this pass if, for example, `bytes.len()` is 257 and `self.size` is 1? 🤔

2020-01-23 03:51 UTC, sorawit submitted a review, later dismissed

2020-01-23 12:08 UTC, taobun requested changes

2020-01-23 12:08 UTC, taobun commented on owasm/example/src/logic.rs
> +        let mut acc: u64 = 0;
Use parse vec<u8> to u64 instead sum

2020-01-23 12:08 UTC, taobun commented on owasm/src/ext/random/qrng_anu.rs
> +    }
I want another test in length of result must equal to size parameter

2020-01-27 04:12 UTC, sorawit requested changes

2020-01-27 04:12 UTC, sorawit commented on owasm/example/src/logic.rs
> +        // Average among the two data points is 175.00
Why tis this changed?

2020-01-27 04:17 UTC, sorawit approved these changes
lgtm

2020-01-27 04:34 UTC, taobun approved these changes

2020-01-27 04:34 UTC, merged