Scan: Disable delegate button when balance is insufficient
bandprotocol/bandchain pull request #3008
Opened 2020-12-17 04:52 UTC by Pitchanai

Fixed: #2986 

## Implementation details
- Disable delegate, undelegate and redelegate buttun when balance is insufficient
- Fix button height not match
- Refactor few codes

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-12-21 09:29 UTC, pzshine approved these changes

2020-12-21 09:34 UTC, evilpeach requested changes

2020-12-21 09:34 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +          disabled
Is it correct? Should it be disabled when user's balance is not zero?

2020-12-24 09:01 UTC, evilpeach requested changes

2020-12-24 09:01 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +          px=20 py=5 variant=Button.Outline disabled=disableDelegate onClick={_ => {undelegate()}}>
remove `{}` Let's change to `onClick={_ => undelegate()}`

2020-12-24 09:01 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +          px=20 py=5 variant=Button.Outline disabled=disableDelegate onClick={_ => {redelegate()}}>
here as well

2020-12-24 09:01 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +      let disabled = balance |> Coin.getBandAmountFromCoins == 0.;
`disabledNoBalance`

2020-12-24 09:01 UTC, evilpeach commented on scan/src/components/modal/ValidatorStakingInfo.re
> +      let disableDelegate = amount == 0.;
`disabledNoStake`

2021-01-05 10:32 UTC, evilpeach approved these changes

2021-01-05 10:34 UTC, merged