Scan: Support fast sync
bandprotocol/bandchain pull request #3015
Opened 2020-12-20 12:35 UTC by evilpeach

## Implementation details
1. Display "Syncing" when `txHash`, `txTimestamp`, `requester` is None (undefined)
   1. Oracle Script index page(request tab)
   2. Data source index page(request tab)
![image](https://user-images.githubusercontent.com/14128977/102713254-6a248400-42f9-11eb-9ef6-68e4239ad28b.png)
   3. Request Index Page
![image](https://user-images.githubusercontent.com/14128977/102713276-b7085a80-42f9-11eb-9798-70d61a9b5329.png)
   4. Validator Index Page (Report Tab)
2. Disable Copy Non-EVM Proof (It will solve later)
3. Display block hasn't mined yet and block is syncing on Block Index Page
![image](https://user-images.githubusercontent.com/14128977/102713334-2b42fe00-42fa-11eb-96a7-4d09c3c47165.png)
![image](https://user-images.githubusercontent.com/14128977/102713341-326a0c00-42fa-11eb-9b8f-a2d1c391d3fb.png)
4. Display transaction hash is syncing or not found.
![image](https://user-images.githubusercontent.com/14128977/102713378-72c98a00-42fa-11eb-884d-2406ef829b49.png)
![image](https://user-images.githubusercontent.com/14128977/102713387-7d841f00-42fa-11eb-9967-e2907f9b4667.png)
5. Remove unused function on AxiosRequest

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [x] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2020-12-21 08:01 UTC, pzshine approved these changes

2020-12-21 08:28 UTC, pzshine requested changes
1. Balance didn't decrease when we sent BAND
![image](https://user-images.githubusercontent.com/17017699/102755515-1ec5b080-43a1-11eb-9dd3-683755151aba.png)

2. Owasm code is disappeared
![image](https://user-images.githubusercontent.com/17017699/102755546-2e44f980-43a1-11eb-9540-31c4fc717dd5.png)

2020-12-21 09:26 UTC, Pitchanai requested changes

2020-12-21 09:26 UTC, Pitchanai commented on scan/src/components/data-source/DataSourceRequestTable.re
> +                 time=txTimestamp'
Is this better ?
```
| Some({time: txTimestamp}) =>
```

2020-12-21 09:26 UTC, Pitchanai commented on scan/src/pages/BlockIndexPage.re
> +      justifyContent(`center),
Please use `CssHelper.flexBox()` instead.

2021-01-06 07:22 UTC, evilpeach commented on scan/src/components/data-source/DataSourceRequestTable.re
> +                 time=txTimestamp'
It isn't object.

2021-01-06 07:23 UTC, evilpeach commented
> 1. Balance didn't decrease when we sent BAND
>    ![image](https://user-images.githubusercontent.com/17017699/102755515-1ec5b080-43a1-11eb-9dd3-683755151aba.png)
> 2. Owasm code is disappeared
>    ![image](https://user-images.githubusercontent.com/17017699/102755546-2e44f980-43a1-11eb-9540-31c4fc717dd5.png)

Answer
1. Server was delay.
2. Some oracle script doesn't have sourceCodeURL.

2021-01-07 08:31 UTC, pzshine requested changes
Typo

it should be:

`Please wait until the state is up to date`

2021-01-07 08:41 UTC, pzshine approved these changes

2021-01-07 08:49 UTC, Pitchanai approved these changes

2021-01-07 08:51 UTC, merged