Pyband: Declared the error to pyband world
bandprotocol/bandchain pull request #3033
Opened 2020-12-25 09:55 UTC by pzshine

## Implementation details

- Declared the custom error to pyband

### Here is the error list

- EmptyRequestMsgError
- QueryError
- NegativeIntegerError
- ValueTooLargeError
- InsufficientCoinError
- EmptyMsgError
- NotFoundError
- UndefinedError
- DecodeError
- ConvertError
- UnsuccessfulCallError
- CreateError
- SchemaError  

## Please ensure the following requirements are met before submitting a pull request:

- [x] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [x] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [x] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [x] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-01-04 09:33 UTC, taobun requested changes

2021-01-04 09:33 UTC, taobun commented on helpers/pyband/pyband/error.py
> +class EmptyRequestMsgError(Exception):
I think renaming this file to `exceptions.py` sounds better.

2021-01-04 09:33 UTC, taobun commented on helpers/pyband/pyband/error.py
> +    def __init__(self, message: str):
I think use `pass` in case we don't want to modify any input.

2021-01-18 12:10 UTC, taobun requested changes

2021-01-18 12:10 UTC, taobun commented on helpers/pyband/pyband/exceptions.py
> +class EmptyRequestMsgError(Exception):
Swit recommend to have
```
class PybandError(Exception):
    pass

class EmptyRequestMsgError(PybandError):
    pass
```

2021-01-18 12:10 UTC, taobun commented on helpers/pyband/pyband/data.py
> +            raise InsufficientCoinError("Expect amount more than 0")
I think it can use ValueError or NegativeIntegerError (a coin cannot be less than zero)

2021-02-24 07:42 UTC, taobun approved these changes

2021-02-25 02:40 UTC, evilpeach approved these changes

2021-02-25 02:40 UTC, merged