test bridge contract on matic and add more info of supported chain in readme.md
bandprotocol/bandchain pull request #307
Opened 2020-01-24 09:27 UTC by prin-r

Fixes #280

2020-01-24 09:28 UTC, sorawit commented
Please explain why we support Matic. What did you test? What's the result? How can the reviewers know that we really support Matic?

2020-01-24 09:29 UTC, sorawit requested changes
Please explain why we support Matic. What did you test? What's the result? How can the reviewers know that we really support Matic?

2020-01-24 09:49 UTC, sorawit commented
@taobun Please review + verify

2020-01-27 08:39 UTC, taobun approved these changes

2020-01-27 09:50 UTC, sorawit approved these changes

2020-01-27 10:10 UTC, merged