Update go-owasm
bandprotocol/bandchain pull request #3195
Opened 2021-02-28 16:31 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-03-10 05:31 UTC, sorawit requested changes

2021-03-10 05:31 UTC, sorawit commented on chain/cmd/bandd/genos.go
> +			vm, err := api.NewVm(0) // Compile didn't use cache
doesn't

2021-03-10 09:24 UTC, thebevrishot commented on chain/cmd/bandd/genos.go
> +			vm, err := api.NewVm(0) // Compile didn't use cache
Fixed

2021-03-11 07:33 UTC, taobun approved these changes

2021-03-11 07:37 UTC, sorawit approved these changes

2021-03-11 07:37 UTC, merged