Add timeout attribute for Client
bandprotocol/bandchain pull request #3220
Opened 2021-03-09 07:34 UTC by Benzbeeb

Fixed: #XXXX

## Implementation details

## Please ensure the following requirements are met before submitting a pull request:

- [ ] The pull request is targeted against the correct target branch
- [ ] The pull request is linked to an issue with appropriate discussion and an accepted design OR is linked to a spec that describes the work.
- [ ] The pull request includes a description of the implementation/work done in detail.
- [ ] The pull request includes any and all appropriate unit/integration tests
- [ ] You have added a relevant changelog entry to `CHANGELOG_UNRELEASED.md`
- [ ] You have re-reviewed the files affected by the pull request (e.g. using the `Files changed` tab in the Github PR explorer)

2021-03-09 09:14 UTC, taobun approved these changes

2021-03-09 09:17 UTC, taobun requested changes

2021-03-09 09:17 UTC, taobun commented on helpers/pyband/pyband/client.py
> +    def __init__(self, rpc_url: str, timeout: Optional[int] = None) -> None:
Add testcase

2021-03-10 03:21 UTC, taobun approved these changes
LGTM wait for @evilpeach review again.

2021-03-10 03:21 UTC, Benzbeeb commented
> LGTM wait for @evilpeach review again.

@evilpeach

2021-03-10 03:26 UTC, evilpeach approved these changes

2021-03-10 04:05 UTC, merged