Refine script execute page
bandprotocol/bandchain pull request #380
Opened 2020-01-31 07:13 UTC by prin-r

Fixes #372

2020-01-31 07:16 UTC, sorawit requested changes

2020-01-31 07:16 UTC, sorawit commented on scan/src/components/ScriptExecute.re
> +let newSelection = (name, dataType, value) => {name, dataType, value};
Dont think this function is necessary.

2020-01-31 07:16 UTC, sorawit commented on scan/src/components/ScriptExecute.re
>          if (name == targetName) {
We can do 
```
data->Belt.List.map(selection => {
   ...selection,
   value: select.name == targetName ? newVal : select.value,
}) 
```

2020-01-31 09:15 UTC, sorawit approved these changes
LGTM thanks

2020-01-31 10:17 UTC, prin-r commented on scan/src/components/ScriptExecute.re
>          if (name == targetName) {
done

2020-01-31 10:18 UTC, prin-r commented on scan/src/components/ScriptExecute.re
> +let newSelection = (name, dataType, value) => {name, dataType, value};
done

2020-02-01 02:57 UTC, evilpeach approved these changes

2020-02-01 09:02 UTC, merged