Remove waiting loop for the next block, because we are now can get state from previous block
bandprotocol/bandchain pull request #419
Opened 2020-02-03 13:37 UTC by prin-r

Fixes #413

2020-02-03 14:07 UTC, sorawit requested changes
This is great!

2020-02-03 14:07 UTC, sorawit submitted a review, later dismissed

2020-02-04 03:23 UTC, taobun requested changes

2020-02-04 03:23 UTC, taobun commented on chain/client/proof.go
> +		rc, err := cliCtx.Client.Commit(nil)
Unused err?

2020-02-04 03:23 UTC, sorawit commented on chain/client/proof.go
> +		rc, err := cliCtx.Client.Commit(nil)
Good catch!

2020-02-04 04:02 UTC, prin-r commented on chain/client/proof.go
> +		rc, err := cliCtx.Client.Commit(nil)
done

2020-02-04 04:06 UTC, taobun approved these changes
lgtm

2020-02-04 07:33 UTC, sorawit approved these changes

2020-02-04 07:44 UTC, merged