implement unconfirm and confirm in request data
bandprotocol/bandchain pull request #442
Opened 2020-02-05 12:00 UTC by evilpeach

Fixes #431 

What to do
- [x] Unconfirmed
- [x] Confirmed
- [ ] Confirmed + Proof

2020-02-05 12:32 UTC, taobun requested changes

2020-02-05 12:32 UTC, taobun commented on chain/cmd/bandsv/main.go
> +	fmt.Println("After unconfirmed")
If this line want to make other understand about code, make it to comment seem more make sense

2020-02-05 12:32 UTC, taobun commented on chain/cmd/bandsv/main.go
> +	fmt.Println("After confirmed")
This too

2020-02-06 03:26 UTC, sorawit requested changes

2020-02-06 03:26 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +	Unconfirmed = "UNCONFIRMED"
Let's call this `ASYNCHRONOUS`, `SYNCHRONOUS`, and `FULL`

2020-02-06 04:33 UTC, taobun submitted a review, later dismissed

2020-02-06 06:19 UTC, sorawit requested changes

2020-02-06 06:19 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +		txr, err := bandProvider.SendTransaction(
Do not duplicate code `txr, err := bandProvider.SendTransaction(...)`. Let's write it like this

```
txr, err := bandProvider.SendTransaction(...)
if err != nil {
     ...
}
if reqType == Asynchronous {
    ....
}
```

2020-02-06 06:19 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +type OracleRequestFullResp struct {
I think we can combine the struct. 
```
type OracleRequestResp struct {
    TxHash string
    RequestId *uint64
    Proof ...
}
```
Then just set to nil if not applicable. Would that work @taobun ?

2020-02-06 09:43 UTC, evilpeach commented on chain/cmd/bandsv/main.go
> +		txr, err := bandProvider.SendTransaction(
In the case of Asynchronous, we use `flags.BroadcastAsync` and we use `flags.BroadcastBlock` in synchronous.

2020-02-06 10:20 UTC, sorawit approved these changes

2020-02-06 10:59 UTC, taobun approved these changes

2020-02-06 11:13 UTC, merged