Request handler function
bandprotocol/bandchain pull request #444
Opened 2020-02-06 10:49 UTC by taobun

fixed #427 

- Separate report process from core chain node
- Remove subscriber package
- Add new method of `BandStatefulClient` to return context used in get data from chain

2020-02-06 11:07 UTC, sorawit requested changes

2020-02-06 11:07 UTC, sorawit commented on chain/Makefile
> +		go install -mod=readonly $(BUILD_FLAGS) ./cmd/provider
`bandoracled`

2020-02-06 11:07 UTC, sorawit commented on docker-compose.yaml
> +      - provider1
oracle1

2020-02-07 09:36 UTC, sorawit approved these changes
Looks good.

2020-02-07 10:26 UTC, evilpeach approved these changes

2020-02-07 10:26 UTC, merged