Implement execution environment
bandprotocol/bandchain pull request #532
Opened 2020-02-13 12:19 UTC by taobun

fixed #500

2020-02-13 12:32 UTC, sorawit requested changes

2020-02-13 12:32 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	if validatorIndex >= int64(len(env.request.RequestedValidators)) {
What happens if we get a negative number?

2020-02-13 12:32 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	if validatorIndex >= int64(len(env.request.RequestedValidators)) {
Same question for the two functions below.

2020-02-13 12:32 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	env.keeper.SetRawDataRequest(env.ctx, env.requestID, externalDataID, dataSourceID, calldata)
This must fail if the dataSourceID does not exist.

2020-02-13 12:46 UTC, sorawit requested changes

2020-02-13 12:46 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	env.keeper.SetRawDataRequest(env.ctx, env.requestID, externalDataID, dataSourceID, calldata)
Must also fail if externalData is already used

2020-02-13 12:47 UTC, sorawit requested changes

2020-02-13 12:47 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	env.keeper.SetRawDataRequest(env.ctx, env.requestID, externalDataID, dataSourceID, calldata)
Must also fail if the calldata size is too big. Pending on #531

2020-02-13 13:32 UTC, sorawit requested changes

2020-02-13 13:32 UTC, sorawit commented on chain/x/zoracle/exec_env.go
> +	report, err := env.keeper.GetRawDataReport(env.ctx, env.requestID, externalDataID, validatorAddress)
Why don't we just `return` here?

2020-02-13 13:32 UTC, sorawit commented on chain/x/zoracle/internal/keeper/raw_request.go
> +func (k Keeper) CheckRawDataRequestExists(ctx sdk.Context, requestID, externalID int64) bool {
Comment?

2020-02-13 13:37 UTC, taobun commented on chain/x/zoracle/exec_env.go
> +	report, err := env.keeper.GetRawDataReport(env.ctx, env.requestID, externalDataID, validatorAddress)
Good catch!

2020-02-13 13:57 UTC, sorawit approved these changes
Looks good

2020-02-14 03:35 UTC, evilpeach approved these changes

2020-02-14 03:39 UTC, merged