Rest-server request and report index endpoint
bandprotocol/bandchain pull request #591
Opened 2020-02-17 10:07 UTC by taobun

fixed #557

2020-02-17 14:20 UTC, sorawit requested changes

2020-02-17 14:20 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
> +	if queryRequest.Result == nil {
I think we can leave it as `nil`. People that call this function should know that if `isResolved` is false then result is `nil`.

2020-02-17 14:20 UTC, sorawit commented on chain/x/zoracle/client/rest/types.go
> +	OracleScriptID           int64            `json:"oracleScriptID"`
I think we should also return raw data requests.

2020-02-17 14:20 UTC, sorawit commented on chain/x/zoracle/internal/types/querier.go
> +type RequestInfo struct {
Let's call this `RequestRESTInfo`

2020-02-17 15:45 UTC, sorawit requested changes

2020-02-17 15:45 UTC, sorawit commented on chain/x/zoracle/client/rest/types.go
> +	OracleScriptID           int64            `json:"oracleScriptID"`
Let's call this `RequestRESTInfo`

2020-02-17 15:45 UTC, sorawit commented on chain/x/zoracle/internal/types/querier.go
> +func NewRequestInfo(
Also update the name here.

2020-02-17 15:45 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
> +func newRequestQueryInfo(
```
// buildRequestRESTInfo takes a RequestQuerierInfo instance and builds a more comprehensive version of it.
func buildRequestRESTInfo
```

2020-02-17 15:54 UTC, sorawit requested changes

2020-02-17 15:54 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
> +	searchRequest, err := utils.QueryTxsByEvents(
Can we somehow abstract "finding the transaction of this" as a separate function. We will need to reuse this a lot.

2020-02-17 15:54 UTC, sorawit commented on chain/x/zoracle/client/rest/types.go
> +	RequestedAtTime          string                 `json:"requestedAtTime"`
This can be put into its own struct if it helps with abstracting the transaction. The thing I mentioned above.

2020-02-17 15:54 UTC, sorawit commented on chain/x/zoracle/client/rest/types.go
>  type RequestQueryInfo struct {
Let's call this RequestRESTInfo so we know it's the info for REST. We have way too many "info" structs lol.

2020-02-18 10:08 UTC, sorawit requested changes
looks good overall. just a few comments.

2020-02-18 10:08 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
> +			if msg.Type() == "report" && msg.Route() == types.RouterKey {
Should we use `MsgReportData{}.Type()` here? 

or alternatively should we just try to cast and check if it's ok? like
```
msgReport, ok := msg.(types.MsgReportData)
if ok {
    ...
}
```

Basically so we don't need to hardcode "report"

2020-02-18 10:08 UTC, sorawit commented on chain/x/zoracle/internal/keeper/querier.go
> +	if sdkErr != nil {
Here we should leave it as nil since the `isResolved` is false?

2020-02-18 12:25 UTC, sorawit submitted a review, later dismissed

2020-02-19 03:57 UTC, prin-r submitted a review, later dismissed

2020-02-19 07:48 UTC, sorawit approved these changes

2020-02-19 08:06 UTC, prin-r approved these changes

2020-02-19 08:06 UTC, merged