Design and implement CLI for sending data source related transaction
bandprotocol/bandchain pull request #592
Opened 2020-02-17 15:34 UTC by taobun

fixed #525

2020-02-17 15:42 UTC, sorawit requested changes

2020-02-17 15:42 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	flagCallFee = "call-fee"
Let's call this `flagDataSourceFee = "dsfee"`

2020-02-17 15:42 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Short: "Create new data source",
a new

2020-02-17 15:42 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +// GetCmdCreateDataSource implements the create data source command handler
fullstop

2020-02-17 15:42 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +// GetCmdEditDataSource implements the edit data source command handler
also here

2020-02-17 15:42 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			execBytes, err := readFile(scriptPath)
Can we use `ioutil`? https://golang.org/pkg/io/ioutil

2020-02-17 15:43 UTC, sorawit requested changes

2020-02-17 15:43 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			fmt.Sprintf(`Edit existed data source by current owner.
Edit an existing data source. The caller must be the current data source's owner.

2020-02-17 15:43 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			fmt.Sprintf(`Create new data source that will be used by oracle script.
by oracle scripts.

2020-02-18 03:47 UTC, sorawit requested changes

2020-02-18 03:47 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	flagCallFee = "call-fee"
Actually call fee is also ok. But I'd prefer the flag name be "callfee"

2020-02-18 03:47 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +// GetCmdCreateDataSource implements the create data source command handler
Great job writing the comment though!

2020-02-18 05:07 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	flagCallFee = "call-fee"
Ok let's go with "call-fee"

2020-02-18 07:23 UTC, sorawit approved these changes

2020-02-18 07:31 UTC, evilpeach approved these changes

2020-02-18 07:47 UTC, merged