Design and implement cli for sending oracle script related transactions
bandprotocol/bandchain pull request #599
Opened 2020-02-18 15:07 UTC by prin-r

Fix #526

2020-02-18 15:40 UTC, sorawit requested changes

2020-02-18 15:40 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Use:   "edit-oracle-script (--id [id]) (--name [name]) (--script [path_to_script]) (--owner [owner])",
Should we use positional argument for id?

2020-02-18 15:40 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Use:   "create-oracle-script (--name [name]) (--script [path_to_script]) (--owner [owner])",
@taobun So are we going to use snake_case or camelCase for the things inside [...]?

2020-02-18 18:37 UTC, sorawit requested changes

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Use:   "create-oracle-script (--name [name]) (--script [path_to_script]) (--owner [owner])",
Let's go for dash-case. I think Cosmos-SDK usually uses that.

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			fmt.Sprintf(`Create new oracle script that will be used by making a request.
Create **a** new oracle script that will be used by data requests.

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			fmt.Sprintf(`Edit an existing oracle script that will be used by making a request.
also fix here.

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		Use:   "edit-oracle-script (--id [id]) (--name [name]) (--script [path_to_script]) (--owner [owner])",
ditto for dash-case

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagName, "", "name of oracle script")
Please capitalize first words.

2020-02-18 18:37 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagName, "", "name of oracle script")
Please capitalize first words.

2020-02-19 06:48 UTC, sorawit requested changes

2020-02-19 06:48 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +		GetCmdCreateOracleScript(cdc),
Move this to before Request and Report cmd.

2020-02-19 06:57 UTC, sorawit submitted a review, later dismissed

2020-02-19 07:07 UTC, evilpeach submitted a review, later dismissed

2020-02-19 07:07 UTC, evilpeach commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagOwner, "", "Owner of this oracle script")
Make it consistent with others.

2020-02-19 07:09 UTC, evilpeach commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagOwner, "", "Owner of this oracle script")
Ex. Name of this oracle script

2020-02-19 07:34 UTC, evilpeach approved these changes

2020-02-19 07:35 UTC, sorawit approved these changes

2020-02-19 07:37 UTC, merged