Setup gitlab ci
bandprotocol/bandchain pull request #60
Opened 2019-12-16 15:51 UTC by evilpeach

Fixes #13 #28

2019-12-16 18:08 UTC, sorawit commented
Why does the current check fail? @evilpeach

2019-12-16 18:26 UTC, evilpeach commented
@sorawit It's ok right now. However, I found they are caching while go test.
https://gitlab.com/bandprotocol/d3n/-/jobs/381020259

2019-12-16 18:27 UTC, sorawit requested changes

2019-12-16 18:27 UTC, sorawit commented on bridges/evm/.gitlab-ci.yml
> +      - "bridges/evm/**/*"
Are the quotes needed?

2019-12-17 04:19 UTC, sorawit approved these changes

2019-12-17 04:21 UTC, merged