Write a few sample data sources
bandprotocol/bandchain pull request #601
Opened 2020-02-19 09:18 UTC by taobun

fixed #551

2020-02-19 09:59 UTC, sorawit requested changes

2020-02-19 09:59 UTC, sorawit commented on chain/datasources/binance_price.sh
> +# Performs data fetching and store result to variable
stores

2020-02-19 17:53 UTC, sorawit approved these changes
Looks great. thanks

2020-02-20 03:53 UTC, evilpeach approved these changes
LGTM

2020-02-20 03:55 UTC, merged