Rest-server all requests and reports endpoint
bandprotocol/bandchain pull request #605
Opened 2020-02-20 06:06 UTC by taobun

fixed #559

2020-02-20 09:29 UTC, sorawit requested changes

2020-02-20 09:29 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
> +	request.Reports = make([]ReportDetail, 0)
I think this should be nil, not empty list if withReportTx is false.

2020-02-20 11:18 UTC, sorawit approved these changes

2020-02-20 11:24 UTC, sorawit requested changes

2020-02-20 11:24 UTC, sorawit commented on chain/x/zoracle/internal/keeper/querier.go
> +	res, err := codec.MarshalJSONIndent(keeper.cdc, request)
Yeah same here. Let's use MustMarshalJSON?

2020-02-21 05:37 UTC, sorawit requested changes

2020-02-21 05:37 UTC, sorawit commented on chain/x/zoracle/client/rest/query.go
>  		reqID := vars[requestID]
See. Confusing!

2020-02-21 05:37 UTC, sorawit commented on chain/x/zoracle/client/rest/rest.go
> +	r.HandleFunc(fmt.Sprintf("/%s/request/{%s}", storeName, requestID), getRequestByIDHandler(cliCtx, storeName)).Methods("GET")
Can you rename variable to `requestIDTag`? Having variable name `requestID` on top scope is confusing.

2020-02-21 07:59 UTC, sorawit submitted a review, later dismissed

2020-02-21 08:37 UTC, evilpeach commented on chain/x/zoracle/internal/types/querier.go
> +	RequestID       int64                          `json:id`
It should be `json:"id"`

2020-02-21 08:57 UTC, sorawit approved these changes

2020-02-21 09:00 UTC, evilpeach approved these changes

2020-02-21 09:04 UTC, merged