Write price oracle script
bandprotocol/bandchain pull request #607
Opened 2020-02-20 11:18 UTC by taobun

fixed #552

2020-02-20 11:56 UTC, sorawit requested changes

2020-02-20 11:56 UTC, sorawit commented on chain/owasm/res/crypto_price/src/lib.rs
> +        _ => "Unsupported coin",
Let's panic?

2020-02-21 05:30 UTC, sorawit approved these changes

2020-02-21 09:52 UTC, evilpeach approved these changes

2020-02-23 07:10 UTC, merged