Swagger d3n
bandprotocol/bandchain pull request #618
Opened 2020-02-23 12:15 UTC by taobun

fixed #535

2020-02-23 13:27 UTC, sorawit submitted a review, later dismissed
Thanks. Let's merge it in for now. After we have the base version merged it, edits will be easier to review.

2020-02-24 06:43 UTC, evilpeach requested changes
Build this by using `make update-swagger-docs`

2020-02-25 05:15 UTC, evilpeach submitted a review, later dismissed

2020-02-25 05:16 UTC, sorawit submitted a review, later dismissed

2020-02-25 12:00 UTC, evilpeach approved these changes

2020-02-25 12:02 UTC, sorawit approved these changes

2020-02-25 12:05 UTC, merged