chain-rest: upgrade get latest txs
bandprotocol/bandchain pull request #650
Opened 2020-02-27 05:09 UTC by evilpeach

Fixes #596

2020-02-27 05:59 UTC, sorawit commented
This is not binary search implementation, but let's start with this first and see how it goes. At least it should now not break. It might get slow if we have LOTS of txs and we will figure that out later. Binary search can be used to find the highest height with enough txs and reuse pretty much the same code for finding txs.

2020-02-27 06:01 UTC, sorawit requested changes

2020-02-27 06:01 UTC, sorawit commented on chain/client/client.go
> +			rest.PostProcessResponseBare(w, cliCtx, result)
I think page total should also be in here. Maybe set it above?

2020-02-27 07:35 UTC, taobun requested changes

2020-02-27 07:35 UTC, taobun commented on chain/client/client.go
> +			pageOfTodoIndex := (todoIndex-1)/limit + 1
If `limit` is more than 100, it leads to infinite loop.

2020-02-27 10:49 UTC, taobun requested changes

2020-02-27 10:49 UTC, taobun commented on chain/client/client.go
> +		if limit > 100 {
Return error

2020-02-27 18:29 UTC, sorawit requested changes

2020-02-27 18:29 UTC, sorawit commented on chain/client/client.go
> +			rest.WriteErrorResponse(w, http.StatusBadRequest, "limit must be less than or equal 100.")
must not be greater than

2020-02-28 04:47 UTC, taobun approved these changes

2020-02-28 06:12 UTC, sorawit approved these changes

2020-02-28 12:40 UTC, merged