Add more information to data request result
bandprotocol/bandchain pull request #652
Opened 2020-02-27 10:07 UTC by prin-r

Fix #625

2020-02-27 11:09 UTC, taobun requested changes

2020-02-27 11:09 UTC, taobun commented on chain/x/zoracle/internal/keeper/result_test.go
> +	keeper.SetRequest(ctx, 1, types.NewRequest(
Can you set BlockTime to context, It makes `AggregationTime` test look more solid.

2020-02-27 11:09 UTC, taobun commented on chain/x/zoracle/handler_test.go
> +	require.Equal(t,
Set BlockTime before handleEndBlock?

2020-02-27 11:14 UTC, sorawit requested changes
Are there changes required on the client side (how to get proof?)

2020-02-27 11:14 UTC, sorawit commented on chain/x/zoracle/internal/types/result.go
> +// Result is a data structure that stores the detail of a result of a specific request.
of the result of a specific request.

2020-02-28 03:17 UTC, taobun submitted a review, later dismissed

2020-02-28 03:19 UTC, taobun commented
Implement `evmBytesProof` will be in the next pr?

2020-02-28 12:39 UTC, sorawit requested changes

2020-02-28 12:39 UTC, sorawit commented on chain/x/zoracle/internal/types/result.go
> +func DecodeResult(b []byte) Result {
This function should return (Result, error) or should panic if the condition hits.

2020-02-28 13:18 UTC, sorawit requested changes

2020-02-28 13:18 UTC, sorawit commented on chain/x/zoracle/internal/types/result.go
> +	if len(b) <= 40 {
<

2020-02-28 13:18 UTC, sorawit commented on chain/x/zoracle/internal/types/result.go
> +		return Result{}, fmt.Errorf(fmt.Sprintf("expect size of input to be more than 40 bytes but got %d bytes", len(b)))
Expect .... to be at least ...

2020-02-28 13:24 UTC, sorawit approved these changes

2020-02-28 13:26 UTC, taobun approved these changes

2020-02-28 13:30 UTC, merged