Fix bandd init with custom parameter
bandprotocol/bandchain pull request #653
Opened 2020-02-27 10:16 UTC by taobun

fixed #624 

[Parameter summary](https://docs.google.com/spreadsheets/d/1-BpqJPPLYoqIQJFHmTEskX4HXFfS61b98pDRd1OmBt4/edit?usp=sharing)

2020-02-27 13:36 UTC, sorawit requested changes

2020-02-27 13:36 UTC, sorawit commented on chain/app/genesis.go
> +			ConstantFee: sdk.NewCoin("uband", sdk.NewInt(1000)),
Doesn't seem right.

2020-02-27 13:36 UTC, sorawit commented on chain/app/genesis.go
> +				Quorum:    sdk.NewDecWithPrec(4, 1),
Add comment please. // 0.4 // 0.5 // 0.334

2020-02-27 13:36 UTC, sorawit commented on chain/app/genesis.go
> +				BlocksPerYear:       10519200, //  assuming 3 second  block times
3-second block time

2020-02-27 13:36 UTC, sorawit commented on chain/app/genesis.go
> +				UnbondingTime: time.Hour * 24 * 7 * 3,
// 3 weeks

2020-02-27 13:36 UTC, sorawit commented on chain/app/genesis.go
> +				MaxEvidenceAge:          60 * 30240 * time.Second,
time.Hour * 24 * 7 * 3 // 3 weeks

2020-02-27 13:36 UTC, sorawit commented on chain/cmd/bandd/main.go
> +					MaxAge: 100000, // 27.8 hrs at 1block/s
Don't think this comment is accurate, but we can just remove it honestly.

2020-02-27 18:37 UTC, sorawit requested changes

2020-02-27 18:37 UTC, sorawit commented on chain/cmd/bandd/main.go
> +func InitCmd(ctx *server.Context, cdc *codec.Codec, customAppState map[string]json.RawMessage,
Also I think it makes sense to move this to its own file.

2020-02-27 18:37 UTC, sorawit commented on chain/cmd/bandd/main.go
Now that we write our own InitCmd. Can you also remove my hacky `PersistentPreRunE`? Basically revert my commit 7b41ef74081601ea0f3d9fb0930a2a13b4ee8287

2020-02-28 12:37 UTC, sorawit approved these changes

2020-03-02 09:40 UTC, evilpeach approved these changes

2020-03-02 09:54 UTC, merged