Error invalid basic msg
bandprotocol/bandchain pull request #664
Opened 2020-02-27 17:43 UTC by evilpeach

Fixes #513 
This is a part of #513

2020-02-27 18:27 UTC, sorawit requested changes
So I guess we decide to use our errors in all places. That's fine.

2020-02-27 18:27 UTC, sorawit commented on chain/x/zoracle/internal/types/error.go
> +	CodeInvalidBasicMsg sdk.CodeType = 201
Add TODO: Change this to 101 after old errors were cleared.

2020-02-27 18:27 UTC, sorawit commented on chain/x/zoracle/internal/types/msgs.go
> +			"MsgRequestData: Request validator count (%d) must be greater than sufficient validator count (%d).",
change to must not be less than. We accept the equality case.

2020-02-27 18:27 UTC, sorawit commented on chain/x/zoracle/internal/types/msgs.go
> +		return ErrInvalidBasicMsg("MsgReportData: DataSet must not be empty.")
Data set

2020-02-28 12:35 UTC, sorawit approved these changes

2020-02-28 13:26 UTC, taobun approved these changes

2020-02-28 15:15 UTC, merged