chain/owasm: specify all vm parameters for life
bandprotocol/bandchain pull request #673
Opened 2020-02-27 19:14 UTC by sorawit

To further prevent the risk of non-determinism, we should specify ALL parameters.

2020-02-28 13:38 UTC, taobun requested changes

2020-02-28 13:38 UTC, taobun commented on chain/owasm/execute.go
> +		DisableFloatingPoint:     true,
Not work in crypto_price script

2020-03-02 03:37 UTC, taobun approved these changes

2020-03-02 09:56 UTC, evilpeach approved these changes
LGTM

2020-03-02 12:03 UTC, merged