scan: data source index page with header
bandprotocol/bandchain pull request #694
Opened 2020-02-29 09:02 UTC by evilpeach

Fixes #651 

- [x] add more font size (18px)
- [x] add MockAddress in InfoHL for mocking address (remove later)
- [x] add DataSourceIndexPage to the route
- [x] create DataSourceIndexPage (only header ui)

2020-02-29 13:10 UTC, sorawit requested changes

2020-02-29 13:10 UTC, sorawit commented on scan/src/reusable/InfoHL.re
> +  | MockAddress(Css.Types.Color.t);
Don't think we need this to introduce this type.

2020-02-29 13:10 UTC, sorawit commented
@prin-r Please check if this follows your design

2020-03-02 06:29 UTC, prin-r commented on scan/src/pages/DataSourceIndexPage.re
> +            value="Last updated 4 hours ago"
Use letter-spacing: 0.06em;

2020-03-02 06:29 UTC, prin-r commented on scan/src/pages/DataSourceIndexPage.re
> +            value="DATA SOURCE"
Use letter-spacing: 0.06em;

2020-03-02 06:31 UTC, prin-r commented on scan/src/pages/DataSourceIndexPage.re
> +      <Text value="CoinGecko V.2" size=Text.Xxl weight=Text.Bold nowrap=true />
Use line-height: 22px;

2020-03-02 06:35 UTC, prin-r commented on scan/src/pages/DataSourceIndexPage.re
> +      <Col size=0.8> <InfoHL info={InfoHL.Fee(1000.)} header="REQUEST FEE" /> </Col>
Use font-weight: 500;

2020-03-02 06:35 UTC, prin-r commented on scan/src/pages/DataSourceIndexPage.re
> +          header="OWNER"
Use font-weight: 500;

2020-03-02 06:38 UTC, prin-r commented on scan/src/reusable/InfoHL.re
> +           value="17rprjgtj0krfw3wyl9creueej6ca9dc4dgxv6e"
Use letter-spacing: 0.02em;

2020-03-02 06:41 UTC, prin-r commented on scan/src/reusable/InfoHL.re
> +         <Text value="BAND" size=Text.Lg weight=Text.Regular code=true />
Use letter-spacing: 0.02em;

2020-03-02 06:41 UTC, prin-r commented on scan/src/reusable/InfoHL.re
> +         <Text value="($0.3)" size=Text.Lg weight=Text.Regular code=true />
Use letter-spacing: 0.02em;

2020-03-03 07:39 UTC, taobun approved these changes

2020-03-03 09:08 UTC, sorawit approved these changes
Looks great!

2020-03-03 09:30 UTC, merged