Save error status to request
bandprotocol/bandchain pull request #702
Opened 2020-03-03 04:10 UTC by Benzbeeb

2020-03-03 06:39 UTC, sorawit requested changes

2020-03-03 06:39 UTC, sorawit commented on chain/x/zoracle/internal/types/request.go
> +	Pending ResolveStatus = iota
Let's call them `Open`, `Success`, `Failure`. Pending is a bit confusing with pending list.

2020-03-03 07:55 UTC, taobun requested changes

2020-03-03 07:55 UTC, taobun commented on chain/x/zoracle/handler.go
> +			keeper.SetResolve(ctx, requestID, types.Failure)
I think we can remove TODO

2020-03-03 07:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report.go
> +	if request.ResolveStatus == types.Success || request.ExpirationHeight < ctx.BlockHeight() {
It would be `!= types.Open` ?

2020-03-03 15:49 UTC, sorawit approved these changes
looks great!

2020-03-04 04:34 UTC, taobun approved these changes

2020-03-04 07:31 UTC, evilpeach approved these changes
LGTM

2020-03-04 07:33 UTC, merged