Add caching layer for owasm resolver
bandprotocol/bandchain pull request #705
Opened 2020-03-03 08:14 UTC by Benzbeeb

2020-03-03 08:52 UTC, sorawit requested changes
Make sure you write some tests to cover the condition!

2020-03-03 08:52 UTC, sorawit commented on chain/owasm/resolver.go
> +func (r *resolver) getExternalDataFromCache(externalDataID int64, validatorIndex int64) ([]byte, error) {
This won't work if it's called two times and error. The first call will return error but the second call won't.

2020-03-03 08:52 UTC, sorawit commented on chain/owasm/resolver.go
> +	externalDataID := GetLocalInt64(vm, 0)
Was this a bug before? Nice catch!

2020-03-03 08:52 UTC, sorawit commented on chain/owasm/resolver.go
> +	externalData, err := r.getExternalDataFromCache(externalDataID, validatorIndex)
If user call for `externalDataID = 0` and `validatorIndex = 0`, won't we incorrectly think it's already in the cache?

2020-03-04 07:31 UTC, sorawit requested changes
Looks good overall. Just a small nit comment. Let's also update the test to make it more clear.

2020-03-04 07:31 UTC, sorawit commented on chain/owasm/resolver.go
> +	used           bool
let's call this `isActive`

2020-03-04 13:46 UTC, taobun requested changes

2020-03-04 13:46 UTC, taobun commented on chain/owasm/resolver_test.go
> +	// functioncode[69].Numparams is 5
Please explain more what is function code 69?

2020-03-05 03:37 UTC, taobun requested changes

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	vm.Ignite(functionID, params[:5]...)
If params is a fixed size array that has a length equal to 5, I think we can remove [:5] and uses `params...` instead.

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	params := [5]int64{}
ditto

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	require.Equal(t, dataSize, int64(len(callData)))
Test call data size for?

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	dataSize := resolver.resolveGetCallDataSize(vm)
Test call data size for?

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	params := [5]int64{}
ditto

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +	dataSize := resolver.resolveGetCallDataSize(vm)
ditto

2020-03-05 03:37 UTC, taobun commented on chain/owasm/resolver_test.go
> +
Can you add test `resolveGetExternalDataSize` and `resolveReadExternalData` that return expected result?

2020-03-05 12:19 UTC, sorawit approved these changes
looks great

2020-03-05 12:21 UTC, taobun approved these changes

2020-03-06 05:03 UTC, merged