scan: tabs in data source index page
bandprotocol/bandchain pull request #709
Opened 2020-03-04 04:12 UTC by evilpeach

Fixes #654 , #655 
- Add Exectution Tab
- Add Code Tab

2020-03-05 06:49 UTC, sorawit requested changes

2020-03-05 06:49 UTC, sorawit commented on scan/src/components/data-source/DataSourceExecute.re
> +      fontWeight(`num(500)),
Can you confirm with Q this is the same as the design. I think it looks different but I'm not sure.

2020-03-06 03:22 UTC, sorawit reviewed
LGTM

2020-03-06 03:22 UTC, sorawit approved these changes
LGTM

2020-03-06 06:42 UTC, sorawit commented
@prin-r Did you review this?

2020-03-06 16:45 UTC, prin-r approved these changes

2020-03-06 16:46 UTC, merged

2020-03-07 16:45 UTC, evilpeach commented
Fixes #655