Create custom types for different kinds of IDs
bandprotocol/bandchain pull request #712
Opened 2020-03-04 10:03 UTC by Benzbeeb

2020-03-04 10:23 UTC, sorawit requested changes

2020-03-04 10:23 UTC, sorawit commented on chain/cmd/bandoracled/main.go
> +		go func(externalID , dataSourceID int64, calldata []byte) {
autoformat?

2020-03-04 10:23 UTC, sorawit commented on chain/cmd/bandoracled/main.go
>  			info := queryParallelInfo{externalID: externalID, answer: []byte{}, err: nil}
I think this function can accept custom ID types.

2020-03-04 14:09 UTC, taobun requested changes

2020-03-04 14:09 UTC, taobun commented on chain/cmd/bandsv/main.go
> +				zoracle.OracleScriptID(req.OracleScriptID),
Fix at request type please

2020-03-04 14:09 UTC, taobun commented on chain/x/zoracle/internal/types/querier.go
> +	ID              RequestID                      `json:"id"`
OracleScriptQuerier id must be `OracleScriptID`

2020-03-05 08:32 UTC, sorawit requested changes

2020-03-05 08:32 UTC, sorawit commented on chain/client/proof.go
> +		key := zoracle.ResultStoreKey(zoracle.RequestID(requestID), queryRequest.Request.OracleScriptID, queryRequest.Request.Calldata)
This is not natural. Let's have the proper type when the variable is declared.

2020-03-05 08:32 UTC, sorawit commented on chain/cmd/bandoracled/main.go
> +		reports = append(reports, zoracle.NewRawDataReport(zoracle.ExternalID(info.externalID), info.answer))
smelly.

2020-03-05 08:32 UTC, sorawit commented on chain/cmd/bandoracled/main.go
> +		zoracle.NewMsgReportData(zoracle.RequestID(requestID), reports, sdk.ValAddress(bandClient.Sender())),
Why is casting here necessary?

2020-03-05 08:32 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +			zoracle.OracleScriptID(req.OracleScriptID),
also here

2020-03-05 08:32 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +			RequestID: zoracle.RequestID(requestID),
also here

2020-03-05 08:32 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +				RequestID: zoracle.RequestID(requestID),
also here

2020-03-05 08:32 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +				types.OracleScriptID(oracleScriptID),
Let's have the type when the variable is created.

2020-03-05 08:32 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +				dataset = append(dataset, types.NewRawDataReport(types.ExternalID(externalID), []byte(reportRaw[1])))
also here

2020-03-05 08:32 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			msg := types.NewMsgReportData(types.RequestID(requestID), dataset, sdk.ValAddress(cliCtx.GetFromAddress()))
also here

2020-03-05 08:32 UTC, sorawit commented on chain/x/zoracle/internal/keeper/request.go
> +		if requestID == types.RequestID(entry) {
Is this cast necessary?

2020-03-06 03:35 UTC, sorawit requested changes

2020-03-06 03:35 UTC, sorawit commented on chain/client/proof.go
> +		requestID := zoracle.RequestID(intRequestID)
Check for errors first before proceeding. Make it a habit. Same for all places below.

2020-03-06 03:35 UTC, sorawit commented on chain/x/zoracle/internal/keeper/data_source.go
> +	k.SetDataSource(ctx, types.DataSourceID(newDataSourceID), newDataSource)
Is this necessary?

2020-03-06 03:35 UTC, sorawit commented on chain/x/zoracle/internal/keeper/keeper.go
> +func (k Keeper) GetRequestCount(ctx sdk.Context) types.RequestID {
This should return `int64`. It's request count, not request ID

2020-03-06 03:35 UTC, sorawit commented on chain/x/zoracle/internal/keeper/querier.go
> +	dataSource, sdkErr := keeper.GetDataSource(ctx, types.DataSourceID(id))
Cast type when creating the variable.

2020-03-06 03:35 UTC, sorawit commented on chain/x/zoracle/internal/keeper/querier.go
> +	limit := types.RequestID(startID + numberOfRequests - 1)
limit and and idx should be int!

2020-03-06 06:49 UTC, sorawit requested changes
Looks good overall. Just a few more comments!

2020-03-06 06:49 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			oracleScriptID := types.OracleScriptID(int64OracleScriptID)
also fix error order here.

2020-03-06 06:49 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			requestID := types.RequestID(int64RequestID)
and here.

2020-03-06 06:49 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +				externalID := types.ExternalID(int64ExternalID)
and here

2020-03-06 06:49 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +				types.DataSourceID(id),
Let's make id have the correct type since its creation.

2020-03-06 06:49 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +				types.OracleScriptID(id),
Let's make id have the correct type since its creation.

2020-03-06 13:57 UTC, sorawit approved these changes

2020-03-06 13:57 UTC, sorawit commented on chain/cmd/bandsv/main.go
> +					requestID = zoracle.RequestID(int64RequstID)
Move error check up.

2020-03-06 13:57 UTC, sorawit requested changes
please fix

2020-03-06 16:26 UTC, sorawit submitted a review, later dismissed

2020-03-07 08:01 UTC, sorawit submitted a review, later dismissed
Looks great. Thanks!

2020-03-07 09:19 UTC, taobun requested changes

2020-03-07 09:19 UTC, taobun commented on chain/client/proof.go
> +		res, _, err := cliCtx.QueryWithData(fmt.Sprintf("custom/zoracle/request/%d", uint64(requestID)), nil)
I think we don't need to cast in `Sprintf`

2020-03-07 09:19 UTC, taobun commented on chain/cmd/bandoracled/main.go
> +				fmt.Sprintf("custom/zoracle/%s/%d", zoracle.QueryDataSourceByID, int64(dataSourceID)),
ditto

2020-03-08 08:12 UTC, evilpeach requested changes

2020-03-08 08:12 UTC, evilpeach commented on chain/x/zoracle/handler_test.go
> +	for i := types.RequestID(10); i <= 10; i++ {
What do you prefer? 

1. `for i := types.RequestID(1); i <= types.RequestID(10); i++ {...}` or 
2. `for i := types.RequestID(1); i <= 10; i++ {...}`

Please make it consistent with other test files.

2020-03-09 03:11 UTC, taobun approved these changes

2020-03-09 03:40 UTC, sorawit approved these changes

2020-03-09 04:03 UTC, evilpeach approved these changes

2020-03-09 05:05 UTC, merged