Extend block window and fix wrong comments
bandprotocol/bandchain pull request #714
Opened 2020-03-04 11:54 UTC by taobun

Due to the short block time, we extend the block window size to check the availability of block validators.

2020-03-04 11:56 UTC, sorawit requested changes

2020-03-04 11:56 UTC, sorawit commented on chain/app/genesis.go
> +				SlashFractionDoubleSign: sdk.NewDecWithPrec(5, 2), //  5%
The spacing here and above is a bit weird?

2020-03-05 09:34 UTC, sorawit approved these changes
LGTM

2020-03-05 09:37 UTC, evilpeach approved these changes

2020-03-05 12:24 UTC, merged