Update init genesis to add default data source and oracle script
bandprotocol/bandchain pull request #715
Opened 2020-03-04 13:44 UTC by taobun

fixed #667 
fixed #669

2020-03-07 08:00 UTC, sorawit requested changes

2020-03-07 08:00 UTC, sorawit commented on chain/app/genesis.go
> +	// TODO: Find a better way to specific path to data sources
specify

2020-03-07 08:00 UTC, sorawit commented on chain/app/genesis.go
> +	// TODO: Find a better way to specific path to oracle scripts
ditto

2020-03-07 10:01 UTC, sorawit submitted a review, later dismissed
Looks great

2020-03-09 04:21 UTC, evilpeach submitted a review, later dismissed

2020-03-10 03:42 UTC, sorawit approved these changes

2020-03-10 03:47 UTC, evilpeach approved these changes
LGTM

2020-03-10 04:30 UTC, merged