Add description for data source
bandprotocol/bandchain pull request #716
Opened 2020-03-04 13:47 UTC by Benzbeeb

2020-03-05 03:50 UTC, taobun requested changes

2020-03-05 03:50 UTC, taobun commented on chain/cmd/request/main.go
> +					tx.Sender(), "Crypto compare script","compare script", sdk.Coins{}, cryptoCompare, tx.Sender(),
The Script that queries crypto price from https://cryptocompare.com.

2020-03-05 03:50 UTC, taobun commented on chain/cmd/request/main.go
> +					tx.Sender(), "Coingecko script", "coin market ranking chart", sdk.Coins{}, coingecko, tx.Sender(),
The Script that queries crypto price from https://coingecko.com.

2020-03-05 03:50 UTC, taobun commented on chain/cmd/request/main.go
> +					tx.Sender(), "Binance script","Binance script", sdk.Coins{}, binance, tx.Sender(),
The Script that queries crypto price from https://www.binance.com/en.

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle create-data-source --name coingecko-price --description coin-market-ranking-chart --script ../price.sh --call-fee 100uband --owner band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9 --from m
Change here too

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagDescription, "", "Description")
... of this data source

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle edit-data-source 1 --name coingecko-price --description coin-market-ranking-chart --script ../price.sh --call-fee 100uband --owner band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9 --from m
ditto

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +	cmd.Flags().String(flagDescription, "", "Description")
ditto

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/handler_test.go
> +	msg := types.NewMsgEditDataSource(1, newOwner, newName, newDescription, newFee, newExecutable, sender)
Testing description too.

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/handler_test.go
> +	msg := types.NewMsgEditDataSource(1, newOwner, newName,newDescription, newFee, newExecutable, sender)
ditto

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source.go
> +func (k Keeper) EditDataSource(ctx sdk.Context, dataSourceID int64, owner sdk.AccAddress, name string, descriotion string, fee sdk.Coins, executable []byte) sdk.Error {
typo

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source_test.go
> +	descriotion := "descriotion"
typo

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source.go
> +	newDataSource := types.NewDataSource(owner, name, description, fee, executable)
Add check MaxDataSourceDescriptionSize?

2020-03-05 03:50 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source.go
> +	updatedDataSource := types.NewDataSource(owner, name, descriotion, fee, executable)
Check Namelength and DescriptionLength

2020-03-05 04:09 UTC, evilpeach requested changes

2020-03-05 04:09 UTC, evilpeach commented on chain/x/zoracle/internal/keeper/test_common.go
> +		"descriotion",
typo

2020-03-05 04:09 UTC, evilpeach commented on chain/x/zoracle/internal/types/msgs_test.go
> +			false, NewMsgCreateDataSource(owner, name, description, feeUband10, executable, nil),
check description is not an empty string in `ValidateBasic`

2020-03-05 04:09 UTC, evilpeach commented on chain/x/zoracle/internal/types/msgs_test.go
> +			false, NewMsgEditDataSource(1, owner, name, description, feeUband10, executable, nil),
add checking description for MsgEditDataSource as well.

2020-03-05 09:34 UTC, sorawit requested changes
Looks great overall. Some more changes to be made!

2020-03-05 09:34 UTC, sorawit commented on chain/x/zoracle/internal/types/params.go
> +	MaxDescriptionLength         int64  `json:"max_description_length"`
Why don't we follow the same format as above and also have yaml?

2020-03-05 09:34 UTC, sorawit commented on chain/x/zoracle/internal/keeper/oracle_script.go
> +	updatedOracleScript := types.NewOracleScript(owner, name, description, code)
Check for maximum description length here. Also check for maximum name length.

2020-03-06 06:29 UTC, taobun requested changes

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle create-data-source --name coingecko-price --description the-script-that-queries-crypto-price=from-cryptocompare --script ../price.sh --call-fee 100uband --owner band15d4apf20449ajvwyc
"The script that queries crypto price from cryptocompare"

2020-03-06 06:29 UTC, taobun commented on chain/cmd/request/main.go
> +				[]sdk.Msg{zoracle.NewMsgCreateOracleScript(tx.Sender(), "Crypto price script", "description", oracleBytes, tx.Sender())},
Oracle script for getting an average crypto price from many sources.

2020-03-06 06:29 UTC, taobun commented on chain/cmd/request/main.go
> +				[]sdk.Msg{zoracle.NewMsgCreateOracleScript(tx.Sender(), "Silly script", "description", bytes, tx.Sender())},
Test oracle script

2020-03-06 06:29 UTC, taobun commented on chain/cmd/request/main.go
> +					[]sdk.Msg{zoracle.NewMsgCreateOracleScript(tx.Sender(), fmt.Sprintf("Silly script %d", i),"description", bytes, tx.Sender())},
Test oracle script

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle edit-data-source 1 --name coingecko-price --description cthe-script-that-queries-crypto-price=from-cryptocompare --script ../price.sh --call-fee 100uband --owner band15d4apf20449ajvwy
ditto

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle create-oracle-script --name eth-price --description description --script ../eth_price.wasm --owner band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9 --from mykey
"Oracle script for getting Ethereum price"

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +$ %s tx zoracle edit-oracle-script 1 --name eth-price --description description --script ../eth_price.wasm --owner band15d4apf20449ajvwycq8ruaypt7v6d345n9fpt9 --from mykey
ditto

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source.go
> +	if len(description) > int(k.MaxDescriptionLength(ctx)) {
Check name length too!

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source_test.go
> +}
Endline

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source_test.go
> +}
Test `EditToolongDataSourceName` and `EditToolongDataSourceDescription` too

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/internal/keeper/oracle_script.go
> +	if len(description) > int(k.MaxDescriptionLength(ctx)) {
Missing check `NameLength`

2020-03-06 06:29 UTC, taobun commented on chain/x/zoracle/internal/keeper/oracle_script_test.go
> +
Add `TestEditOracleScriptTooLongName`

2020-03-06 08:00 UTC, taobun requested changes

2020-03-06 08:00 UTC, taobun commented on chain/x/zoracle/internal/keeper/oracle_script_test.go
> +func TestEditOracleScriptTooLongDescription(t *testing.T) {
Can you rearrange the code for consistency?

- TestAddOracleScript
  - Success
  - TooLongCode
  - TooLongName
  - TooLongDescription
- TestEditOracleScript
  - ...

Same of Data source

2020-03-06 13:09 UTC, taobun commented on chain/x/zoracle/internal/keeper/oracle_script_test.go
> +func TestEditOracleScriptTooLongDescription(t *testing.T) {
"Same of Data source"!!!

2020-03-06 13:10 UTC, taobun requested changes

2020-03-06 13:10 UTC, taobun commented on chain/x/zoracle/internal/keeper/data_source_test.go
> +func TestAddTooLongDataSourceDescription(t *testing.T) {
This file too!

2020-03-06 13:55 UTC, taobun submitted a review, later dismissed
LGTM

2020-03-06 14:08 UTC, sorawit requested changes

2020-03-06 14:08 UTC, sorawit commented on chain/x/zoracle/internal/types/msgs_test.go
> +	"fmt"
Why is this added?

2020-03-06 14:10 UTC, sorawit approved these changes

2020-03-06 14:24 UTC, taobun approved these changes

2020-03-06 14:36 UTC, evilpeach approved these changes

2020-03-06 14:36 UTC, merged