Make variables in bandoracled configurable via cobra
bandprotocol/bandchain pull request #720
Opened 2020-03-05 08:07 UTC by taobun

fixed #620 

After run `bandoracled --help`, this is a result.
```
Band oracle to listen new requests from chain and reports data for execution.
Example:
$ bandoracled --node tcp://localhost:26657 --priv-key 06be35b56b048c5a6810a47e2ef612eaed735ccb0d7ea4fc409f23f1d1a16e0b -d 60

Usage:
  bandoracled [flags]

Flags:
  -h, --help                 help for bandoracled
      --node string          <host>:<port> to Tendermint RPC interface for this chain (default "tcp://localhost:26657")
      --priv-key string      Private key of validator to send report transaction (default "06be35b56b048c5a6810a47e2ef612eaed735ccb0d7ea4fc409f23f1d1a16e0b")
  -d, --query-duration int   Max duration to query data (default 60)
```

2020-03-05 09:30 UTC, sorawit requested changes

2020-03-05 09:30 UTC, sorawit commented on chain/cmd/bandoracled/main.go
> +	flagQueryDuration = "query-duration"
call it `flagMaxQueryDuration` for the sake of clarity.

2020-03-06 03:21 UTC, sorawit submitted a review, later dismissed

2020-03-06 04:04 UTC, evilpeach requested changes

2020-03-06 04:04 UTC, evilpeach commented on chain/cmd/bandoracled/main.go
> +			fmt.Println(viper.GetString(flags.FlagNode), currentRequestID)
remove log

2020-03-06 06:31 UTC, evilpeach approved these changes

2020-03-06 07:35 UTC, sorawit approved these changes

2020-03-06 07:35 UTC, merged