Patch TxHook.t's message types
bandprotocol/bandchain pull request #721
Opened 2020-03-05 11:12 UTC by taobun

fixed #671

2020-03-05 12:46 UTC, evilpeach requested changes

2020-03-05 12:46 UTC, evilpeach commented on scan/src/Index.re
> +// AxiosHooks.setRpcUrl("http://rpc.alpha.bandchain.org/");
remove comment line

2020-03-05 12:46 UTC, evilpeach commented on scan/src/rpc/TxHook.re
Let's move to `requestHook`.

2020-03-06 03:51 UTC, evilpeach approved these changes

2020-03-06 03:59 UTC, sorawit approved these changes

2020-03-06 04:01 UTC, merged