Implement hook to get data source information given data source id
bandprotocol/bandchain pull request #722
Opened 2020-03-06 03:54 UTC by taobun

fixed #663 

This pr mock request with old request type. if someone updates the new request type, please update this file too.

2020-03-06 14:14 UTC, sorawit approved these changes

2020-03-06 15:25 UTC, evilpeach requested changes

2020-03-06 15:25 UTC, evilpeach commented on scan/src/rpc/DataSourceHook.re
> +let getDataSource = dataSourceID => {
`let get = id => `

2020-03-07 09:18 UTC, evilpeach approved these changes

2020-03-07 09:22 UTC, merged