scan: update oracle script hook
bandprotocol/bandchain pull request #723
Opened 2020-03-06 04:38 UTC by evilpeach

Fixes #665

2020-03-06 06:41 UTC, taobun requested changes

2020-03-06 06:41 UTC, taobun commented on scan/src/rpc/OracleScriptHook.re
> +    code: JsBuffer.t,
Add more fields that design require.

2020-03-06 06:41 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +    // info: OracleScriptHook.OracleScript.t,
Why remove in this pr?

2020-03-06 07:57 UTC, evilpeach commented on scan/src/rpc/RequestHook.re
> +    // info: OracleScriptHook.OracleScript.t,
It causes errors while testing.

2020-03-07 18:12 UTC, evilpeach commented
@taobun @sorawit @prin-r I've fixed #677 on this PR as well.

2020-03-09 07:56 UTC, taobun requested changes

2020-03-09 07:56 UTC, taobun commented on scan/src/rpc/BlockHook.re
> +  let getProposerMoniker = (height: t, validators: list(ValidatorHook.Validator.t)) =>
block?

2020-03-10 03:32 UTC, taobun approved these changes

2020-03-10 03:44 UTC, sorawit approved these changes
ship it!

2020-03-10 05:40 UTC, merged