Implement scan hook for validators info and all validators
bandprotocol/bandchain pull request #725
Opened 2020-03-06 06:36 UTC by Benzbeeb

2020-03-06 07:10 UTC, taobun requested changes

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/JsonUtils.re
> +};
Endline!

2020-03-06 07:10 UTC, taobun commented on scan/src/contexts/GlobalContext.re
> +};
Endline!

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +let getValidator = (~limit=10, ~page=1, ~status="bonded", ()) => {
getValidators

2020-03-06 07:10 UTC, taobun commented on scan/src/contexts/GlobalContext.re
> +  let validatorsOpt = ValidatorHook.getValidator();
getValidators

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +    repoertRate: float,
Merge ValidatorIndexInfo to this module

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +    repoertRate: float,
Change report rate to Complete and Miss request count?

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +module ValidatorIndexNodeSatus = {
I think to add this data to Validator type

2020-03-06 07:10 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +module ValidatorIndexRequestResponse = {
Same with ValidatorIndexNodeSatus

2020-03-06 14:22 UTC, taobun requested changes

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  type report_t = {
Can reuse from `RequestHook.Report.t`

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +    proposedBlockList: list(proposed_block_t),
proposedBlocks

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +    delegatorList: list(delegator_t),
ditto

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +    indexNodeStatus: status_t,
nodeStatus

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  type request_t = {
Remove this type if not used

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  type status_t = {
node_status_t

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  type external_t = {
Remove

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  type proposed_block_t = {
Reuse `BlockHook.Block.t` instead

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +module ValidatorStatus = {
Make it to function

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +module ValidatorCount = {
ditto

2020-03-06 14:22 UTC, taobun commented on scan/src/rpc/ValidatorHook.re
> +  GlobalInfo.{
. is necessary?

2020-03-06 14:53 UTC, Benzbeeb commented on scan/src/rpc/ValidatorHook.re
> +  type report_t = {
report_t has `requestID` so it isn't equal to RequestHook.Report.t

2020-03-09 12:12 UTC, evilpeach requested changes

2020-03-09 12:12 UTC, evilpeach commented on scan/src/contexts/GlobalContext.re
> +  let validatorsOpt = ValidatorHook.getValidators();
`ValidatorHook.getList()`

2020-03-10 03:46 UTC, sorawit requested changes

2020-03-10 03:46 UTC, sorawit commented on scan/src/rpc/ValidatorHook.re
> +let getValidatorStatus = (~status="bonded", ()) => {
Why does this return an int?

2020-03-10 05:39 UTC, evilpeach requested changes

2020-03-10 05:39 UTC, evilpeach commented on scan/src/rpc/ValidatorHook.re
> +};
The default status of `staking/validators` is `bonded`. So, we should combine `getValidatorStatus` and `getValidatorCount` together.

2020-03-10 05:39 UTC, evilpeach commented on scan/src/rpc/ValidatorHook.re
>    let decodeValidator = json =>
change the function name to `decodeResult`

2020-03-10 05:39 UTC, evilpeach commented on scan/src/rpc/ValidatorHook.re
>    let decodeValidators = json =>
change to decodeList

2020-03-10 05:39 UTC, evilpeach commented on scan/src/rpc/ValidatorHook.re
add decode for the single validator

2020-03-10 11:44 UTC, taobun approved these changes

2020-03-10 13:51 UTC, evilpeach approved these changes

2020-03-10 14:26 UTC, sorawit approved these changes

2020-03-10 14:26 UTC, merged