676 request hook
bandprotocol/bandchain pull request #726
Opened 2020-03-06 07:55 UTC by evilpeach

Fixes #676 

[Document](https://docs.google.com/spreadsheets/d/1JwzzcJl0bDQdi1I8T3KiZloRX6RaGvZ3Vi4ZIRmUbCM/edit#gid=469360780)

[API](http://d3n-debug.bandprotocol.com:1317/zoracle/request/1)

2020-03-06 08:14 UTC, taobun requested changes

2020-03-06 08:14 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +    isResolved: bool,
isResolved changed to resolveStatus already.

2020-03-06 08:14 UTC, taobun commented on scan/src/rpc/RequestHook.re
>    let decodeReports = json => JsonUtils.Decode.(json |> field("reports", list(decode)));
Remove this function

2020-03-06 08:14 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +let getRequestList = (~page=1, ~limit=10, ()) => {
getList

2020-03-06 08:14 UTC, taobun commented on scan/src/rpc/RequestHook.re
>    let json = AxiosHooks.use({j|zoracle/request/$reqID|j});
Change to id

2020-03-06 14:34 UTC, taobun requested changes

2020-03-06 14:34 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +  let decode = json => JsonUtils.Decode.(json |> field("result", decode));
Rename this function

2020-03-07 09:24 UTC, taobun commented
Do we need to fix in DataSourceHook that refers to this Request type?

2020-03-07 09:26 UTC, sorawit submitted a review, later dismissed

2020-03-07 12:58 UTC, taobun approved these changes

2020-03-07 13:00 UTC, sorawit approved these changes

2020-03-07 15:52 UTC, merged