scan: implement data source page requests and revisions tables ui
bandprotocol/bandchain pull request #766
Opened 2020-03-07 19:21 UTC by prin-r

Fix #670

2020-03-09 04:01 UTC, evilpeach requested changes

2020-03-09 04:01 UTC, evilpeach commented on scan/src/pages/DataSourceIndexPage.re
> +       | DataSourceRequests => <DataSourceTable />
Let's name it to `DataSourceRequestTable`

2020-03-09 04:01 UTC, evilpeach commented on scan/src/components/RevisionTable.re
> +    ]);
Remove unused styles

2020-03-09 04:01 UTC, evilpeach commented on scan/src/components/data-source/DataSourceTable.re
> +    ]);
remove this as well

2020-03-09 11:56 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-03-10 12:38 UTC, evilpeach submitted a review, later dismissed

2020-03-11 03:58 UTC, evilpeach commented
@prin-r Please fix conflict

2020-03-12 06:22 UTC, evilpeach submitted a review, later dismissed
LGTM

2020-03-12 08:07 UTC, evilpeach approved these changes

2020-03-12 08:49 UTC, taobun approved these changes

2020-03-12 14:22 UTC, merged