Implement UI for all validators page
bandprotocol/bandchain pull request #778
Opened 2020-03-11 09:59 UTC by Benzbeeb

2020-03-12 10:38 UTC, evilpeach commented
@Benzbeeb Please fix conflict.

2020-03-12 14:12 UTC, taobun requested changes

2020-03-12 14:12 UTC, taobun commented on scan/index.html
> +<head>
What?

2020-03-12 14:12 UTC, taobun commented on scan/src/reusable/InfoHL.re
> +     | Address(address, textColor) =>
unused testColor ?

2020-03-13 03:19 UTC, taobun approved these changes
LGTM

2020-03-13 04:05 UTC, evilpeach approved these changes

2020-03-13 06:23 UTC, merged