scan: Tx index bottom part and support Request Msg Type
bandprotocol/bandchain pull request #784
Opened 2020-03-12 06:20 UTC by evilpeach

Fixes #732

2020-03-12 15:13 UTC, taobun submitted a review, later dismissed
LGTM!

2020-03-13 03:40 UTC, taobun requested changes

2020-03-13 03:40 UTC, taobun commented on scan/src/components/TxIndexPageTable.re
> +        <Text value="REPORT REPIOD" size=Text.Sm weight=Text.Thin spacing={Text.Em(0.06)} />
REPORT PERIOD

2020-03-13 04:19 UTC, prin-r approved these changes

2020-03-13 05:04 UTC, taobun approved these changes

2020-03-13 05:14 UTC, merged