scan: AccountIndexPage bottom part
bandprotocol/bandchain pull request #790
Opened 2020-03-12 15:20 UTC by evilpeach

Fixes #687

2020-03-15 16:07 UTC, taobun requested changes

2020-03-15 16:07 UTC, taobun commented on scan/src/components/account/AccountIndexDelegations.re
> +             <Row>
Row height different from design(50 px) but when render got (45px)

2020-03-16 04:43 UTC, taobun approved these changes

2020-03-16 06:49 UTC, prin-r approved these changes

2020-03-16 06:49 UTC, merged