Implement and wire up data source test execution
bandprotocol/bandchain pull request #791
Opened 2020-03-12 15:55 UTC by prin-r

Fix #681

2020-03-13 07:24 UTC, taobun requested changes

2020-03-13 07:24 UTC, taobun commented on scan/src/components/data-source/DataSourceExecute.re
> +                    calldataArr->Belt_Array.get(0)->Belt_Option.getWithDefault("");
Join calldata?

2020-03-13 08:39 UTC, prin-r commented on scan/src/components/data-source/DataSourceExecute.re
> +                    calldataArr->Belt_Array.get(0)->Belt_Option.getWithDefault("");
done

2020-03-15 05:36 UTC, taobun approved these changes

2020-03-15 10:21 UTC, evilpeach approved these changes

2020-03-15 10:21 UTC, merged