Implement oracle script index execution tab ui
bandprotocol/bandchain pull request #865
Opened 2020-03-16 10:49 UTC by prin-r

Fix #835

2020-03-16 16:52 UTC, taobun requested changes

2020-03-16 16:52 UTC, taobun commented on scan/src/App.re
>           | ScriptHomePage => <ScriptHomePage />
Rename to OracleScriptHomePage

2020-03-16 16:52 UTC, taobun commented on scan/src/pages/ScriptIndexPage.re
> +let make = (~codeHash, ~hashtag: Route.oracle_script_tab_t) => {
Remove this file?

2020-03-16 16:52 UTC, taobun commented on scan/src/reusable/InfoHL.re
> +  | DataSources(list(int))
list of DatasourceID? or int not sure

2020-03-16 16:52 UTC, taobun commented on scan/src/pages/OracleScriptIndexPage.re
> +  <div className=Styles.pageContainer>
The top part has liked design yet?

2020-03-16 16:52 UTC, taobun commented on scan/src/pages/OracleScriptIndexPage.re
> +  <div className=Styles.pageContainer>
It' ok to not like the design because there is a ticket to work on it.

2020-03-16 16:52 UTC, taobun commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +      <VSpacing size=Spacing.lg />
This would be a new ui  (report loading tube)? (Add todo and remove data source code)

2020-03-17 04:30 UTC, Benzbeeb commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +          "Request data"
change "Request data" to "Request "

2020-03-17 04:37 UTC, Benzbeeb requested changes
The space between logo and oracle script id is wrong

2020-03-17 09:31 UTC, taobun requested changes

2020-03-17 09:31 UTC, taobun commented on scan/src/components/ProgressBar.re
> +      <VSpacing size={`px(8)} />
Add more space here, now text look too close to the bar

2020-03-17 09:31 UTC, taobun commented on scan/src/components/ProgressBar.re
> +          "Pending " ++ (minimumValidators - reportedValidators |> Format.iPretty) ++ " Validators"
Make pending text to center

2020-03-17 13:06 UTC, taobun requested changes

2020-03-17 13:06 UTC, taobun commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +                   {kvs->Belt_List.map(entry =>
Add space between each value?

2020-03-17 13:06 UTC, taobun commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +                          <Text value={entry->Belt_List.getExn(0)} />
bold text?

2020-03-17 13:06 UTC, taobun commented on scan/src/components/oracle-script/OracleScriptExecute.re
> +               <VSpacing size=Spacing.sm />
Add more space

2020-03-17 13:30 UTC, taobun submitted a review, later dismissed
Thanks!

2020-03-17 15:00 UTC, evilpeach requested changes

2020-03-17 15:00 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptRequestTable.re
> +                      />
Use `<TypeID.Request id={ID.Request.ID(id)} />`

2020-03-17 15:00 UTC, evilpeach commented on scan/src/components/oracle-script/OracleScriptRequestTable.re
> +                      />
Use `<Type.Block Id={ID.Block.ID(blockHeight)} />`

2020-03-17 15:00 UTC, evilpeach commented on scan/src/components/ProgressBar.re
> +      height(`px(0)),
use `zero

2020-03-17 15:01 UTC, taobun commented on scan/src/components/oracle-script/OracleScriptRequestTable.re
> +                      />
You got it!

2020-03-17 15:31 UTC, evilpeach approved these changes

2020-03-18 03:01 UTC, taobun approved these changes

2020-03-18 03:05 UTC, Benzbeeb approved these changes

2020-03-18 03:07 UTC, merged