Revisit bridge contract
bandprotocol/bandchain pull request #868
Opened 2020-03-16 12:08 UTC by taobun

fixed #810

2020-03-16 12:15 UTC, sorawit requested changes

2020-03-16 12:15 UTC, sorawit commented on chain/client/proof.go
> +			return BlockRelayProof{}, fmt.Errorf("Inconsistency prefix signature byte")
inconsistent .. bytes

2020-03-16 13:07 UTC, sorawit requested changes

2020-03-16 13:07 UTC, sorawit commented on bridges/evm/test/Bridge.test.js
> +      (
Dont re-format it!

2020-03-16 13:23 UTC, taobun commented on bridges/evm/test/Bridge.test.js
> +      (
Fixed

2020-03-16 15:38 UTC, sorawit approved these changes
looks good

2020-03-18 08:17 UTC, prin-r approved these changes

2020-03-18 12:32 UTC, merged