Implement search functionality
bandprotocol/bandchain pull request #869
Opened 2020-03-16 13:10 UTC by Benzbeeb

2020-03-16 14:13 UTC, sorawit requested changes

2020-03-16 14:13 UTC, sorawit commented on scan/__tests__/Route_test.re
> +  test("test block prefix is B", () =>
Let's have this compared route directly if possible? We should not have tests that rely on `toString` unless necesssary.

2020-03-16 14:13 UTC, sorawit commented on scan/src/utils/Route.re
> +    capStr |> Js.String.startsWith("B")
Can we do

```
let search = (str) => {
    ...
    if (capStr |> Js.String.startswith("B")) {
        let%Opt blockID = String.sub(_, 1, len - 1) |> int_of_string_opt;
        Some(BlockIndexPage(blockID))
    } else if (...) {
        ...
    } |> Belt.Option.getWithDefault(_, NotFound)
}
```

2020-03-16 16:27 UTC, sorawit requested changes

2020-03-16 16:27 UTC, sorawit commented on scan/src/utils/Route.re
> +      } else if (len == 64) {
Let's also allow the case when string is `0x` prefixed.

2020-03-17 02:48 UTC, sorawit requested changes
Two things.
- We should also redirect to the search page if user press "Enter"
- We should clear the search box after we redirect

2020-03-17 06:07 UTC, sorawit requested changes

2020-03-17 06:07 UTC, sorawit commented on scan/src/components/SearchBar.re
> +      onKeyPress={event =>
Let's do this logic in `onKeyDown`

2020-03-17 06:07 UTC, sorawit requested changes

2020-03-17 06:07 UTC, sorawit commented on scan/src/utils/Route.re
> +      } else if (len == 64 || str |> Js.String.startsWith("0x") && len == 66) {
Let's add paren here for clarity. `xxx && (xxx || xxx)`

2020-03-17 09:01 UTC, sorawit approved these changes

2020-03-17 09:02 UTC, sorawit submitted a review, later dismissed

2020-03-17 13:12 UTC, taobun requested changes

2020-03-17 13:12 UTC, taobun commented on scan/src/utils/Route.re
> +        Some(ValidatorIndexPage(str |> Address.fromBech32, Delegators));
Go to proposed block?

2020-03-17 15:08 UTC, taobun requested changes

2020-03-17 15:08 UTC, taobun commented on scan/src/pages/ScriptIndexPage.re
> +        <InfoHL info={InfoHL.Text(oracleScriptID |> string_of_int)} header="SCRIPT HASH" />
It will be changed in other pr

2020-03-17 15:08 UTC, taobun commented on scan/__tests__/Route_test.re
> +  test("test block route", () =>
transaction

2020-03-17 15:08 UTC, taobun commented on scan/__tests__/Route_test.re
> +  test("test block route prefix is 0x", () =>
transaction

2020-03-17 15:08 UTC, taobun commented on scan/__tests__/Route_test.re
> +  test("test oracle script route", () =>
account

2020-03-18 06:59 UTC, taobun approved these changes

2020-03-18 14:24 UTC, sorawit approved these changes

2020-03-18 16:36 UTC, merged