scan: patch to have pagination
bandprotocol/bandchain pull request #870
Opened 2020-03-17 07:41 UTC by evilpeach

Fixes #824 
- [x] TxHomePage
- [x] ValidatorHomePage
- [x] DataSourceHomePage

2020-03-17 13:27 UTC, taobun requested changes

2020-03-17 13:27 UTC, taobun commented on scan/src/pages/DataSourceHomePage.re
> +  let dataSourcesCountOpt = DataSourceHook.getList();
Why we use page=1 and limit =10 as data source count?
*Note: If it is used for temporary. please add TODO

2020-03-18 04:57 UTC, taobun approved these changes

2020-03-18 11:15 UTC, prin-r approved these changes

2020-03-18 11:23 UTC, merged