scan: Price Card on Landing Page and wire up
bandprotocol/bandchain pull request #874
Opened 2020-03-17 11:57 UTC by evilpeach

Fixes #812

2020-03-17 13:45 UTC, taobun requested changes

2020-03-17 13:45 UTC, taobun commented on scan/src/components/ChainInfoHighlights.re
> +                               color={usd24HrChange >= 0. ? Colors.green4 : Colors.red5}
Different green with design

2020-03-17 13:52 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +                               color={usd24HrChange >= 0. ? Colors.green4 : Colors.red5}
Green Color in design is wrong hex.

2020-03-18 04:21 UTC, Benzbeeb requested changes
the position of the graph in the landing page isn't matching with the design

2020-03-18 07:06 UTC, taobun approved these changes

2020-03-18 07:15 UTC, Benzbeeb approved these changes

2020-03-18 07:16 UTC, merged