Implement validator index delegator table
bandprotocol/bandchain pull request #880
Opened 2020-03-18 03:52 UTC by Benzbeeb

Fixed #806

2020-03-18 06:26 UTC, evilpeach requested changes

2020-03-18 06:26 UTC, evilpeach commented on scan/src/components/validator/DelegatorsTable.re
> +  let fixWidth = style([width(`px(230))]);
remove unused

2020-03-18 06:26 UTC, evilpeach commented on scan/src/components/validator/DelegatorsTable.re
> +           <Text block=true value="NO BLOCK" weight=Text.Regular color=Colors.blue4 />
`NO DELEGATORS`

2020-03-19 03:20 UTC, taobun approved these changes

2020-03-19 09:27 UTC, evilpeach approved these changes
LGTM

2020-03-19 10:02 UTC, merged