Make bandoracled support execution to aws lambda
bandprotocol/bandchain pull request #881
Opened 2020-03-18 05:55 UTC by prin-r

Fix #830

2020-03-18 07:11 UTC, taobun requested changes

2020-03-18 07:11 UTC, taobun commented on chain/byteexec/byteexec.go
> +	requestBody, err := json.Marshal(map[string]string{
Use `grequests` library to wrap the request.

2020-03-18 07:11 UTC, taobun commented on chain/cmd/bandoracled/main.go
> +	flagReporterURL      = "reporter-url"
flagExecuteEndPoint = "execute-endpoint"

2020-03-18 07:11 UTC, taobun commented on chain/cmd/bandoracled/main.go
> +		"The URL of reporter end-point which will receive 3 parameters (executable, timeout, calldata)",
execute

2020-03-19 03:25 UTC, taobun requested changes

2020-03-19 03:25 UTC, taobun commented on chain/cmd/bandoracled/main.go
> +			if executeEndPoint == "" {
Use viper.IsSet(flagExecuteEndPoint)

2020-03-19 07:19 UTC, taobun approved these changes

2020-03-19 09:47 UTC, sorawit approved these changes

2020-03-20 05:25 UTC, merged