Implement validator index reports table
bandprotocol/bandchain pull request #883
Opened 2020-03-18 07:14 UTC by Benzbeeb

Fixed #807

2020-03-18 16:17 UTC, taobun requested changes

2020-03-18 16:17 UTC, taobun commented on scan/src/components/validator/ReportsTable.re
> +           <Text block=true value="NO BLOCK" weight=Text.Regular color=Colors.blue4 />
NO REPORTS

2020-03-18 16:17 UTC, taobun commented on scan/src/components/validator/ReportsTable.re
> +         </div>}
Add pagination and mock pageCount

2020-03-18 16:17 UTC, taobun commented on scan/src/components/validator/ReportsTable.re
> +    ),
Add 1 more report, I want to see table more

2020-03-19 06:39 UTC, taobun requested changes

2020-03-19 06:39 UTC, taobun commented on scan/src/components/validator/ReportsTable.re
> +                        <Text value=hash block=true code=true ellipsis=true />
set font weight Medium

2020-03-19 17:13 UTC, taobun commented
@Benzbeeb Fix conflict first

2020-03-20 06:49 UTC, prin-r submitted a review, later dismissed

2020-03-20 06:49 UTC, taobun requested changes

2020-03-20 06:49 UTC, taobun commented on scan/src/pages/ValidatorIndexPage.re
> +       | Delegators => <div> <Text value="Delegators" /> </div>
LUL

2020-03-20 06:52 UTC, Benzbeeb commented on scan/src/pages/ValidatorIndexPage.re
> +       | Delegators => <div> <Text value="Delegators" /> </div>
Shame on me

2020-03-20 08:01 UTC, taobun requested changes

2020-03-20 08:01 UTC, taobun commented on scan/src/components/validator/ReportsTable.re
> +           //  <Pagination currentPage="1" pageCount onPageChange={newPage => setPage(_ => newPage)} />
LUL

2020-03-20 08:17 UTC, evilpeach requested changes

2020-03-20 08:17 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +  let fixWidth = style([width(`px(230))]);
remove

2020-03-20 08:17 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +                        <Text value=oracleScriptDescription block=true code=true />
support `text-overflow` if the length of the word exceeds max-width.

2020-03-20 08:17 UTC, evilpeach commented on scan/src/components/validator/ReportsTable.re
> +                    <Col size=1.>
Add more space between OracleScript column and DataSource column

2020-03-20 13:10 UTC, taobun approved these changes

2020-03-21 09:35 UTC, prin-r approved these changes

2020-03-21 09:37 UTC, evilpeach approved these changes
LGTM Thanks!

2020-03-21 09:39 UTC, merged