chain: implement collect dataSource fee from requester
bandprotocol/bandchain pull request #884
Opened 2020-03-18 10:20 UTC by evilpeach

Fixes #756

2020-03-18 10:25 UTC, sorawit requested changes

2020-03-18 10:25 UTC, sorawit commented on chain/x/zoracle/handler.go
> +	err = keeper.PayDataSourcesFee(ctx, id, msg.Sender)
PayDataSourceFees

2020-03-18 10:25 UTC, sorawit commented on chain/x/zoracle/internal/keeper/request.go
> +// PayDataSourcesFee send fees to the owner of requested data sources.
sends

2020-03-18 10:25 UTC, sorawit commented on chain/x/zoracle/internal/keeper/request.go
> +		if dataSource.Fee.IsZero() {
Let's also do nothing if the sender is the same as owner

2020-03-18 16:21 UTC, taobun requested changes

2020-03-18 16:21 UTC, taobun commented on chain/x/zoracle/internal/keeper/request.go
> +func (k Keeper) PayDataSourcesFee(ctx sdk.Context, id types.RequestID, sender sdk.AccAddress) sdk.Error {
Can you add a simple test for this function? By set a request. data source and raw data request and make sure the balance of requester is reduced.

2020-03-19 00:20 UTC, sorawit requested changes

2020-03-19 00:20 UTC, sorawit commented on chain/x/zoracle/internal/keeper/request.go
> +// PayDataSourceFees sends fees to the owner of requested data sources.
owners of the requested

2020-03-19 01:20 UTC, sorawit approved these changes

2020-03-19 03:50 UTC, taobun approved these changes
LGTM

2020-03-19 04:31 UTC, merged