Implement home page Market Cap card UI & Wireup
bandprotocol/bandchain pull request #892
Opened 2020-03-18 13:15 UTC by Benzbeeb

Fixed #813

2020-03-18 14:27 UTC, sorawit commented on scan/src/rpc/PriceHook.re
> +  Js.Console.log(Some(Price.decode(usd, btc, band)));
Remove logging

2020-03-19 10:07 UTC, evilpeach requested changes

2020-03-19 10:07 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
>                               <Text value={marketcap->Format.fPretty} code=true />
weight = Thin

2020-03-19 12:44 UTC, evilpeach approved these changes
LGTM

2020-03-19 17:13 UTC, taobun approved these changes

2020-03-20 03:09 UTC, merged