Implement home page LATEST BLOCK card UI & Wireup
bandprotocol/bandchain pull request #893
Opened 2020-03-18 13:36 UTC by Benzbeeb

Fixed #814

2020-03-18 16:31 UTC, taobun requested changes

2020-03-18 16:31 UTC, taobun commented on scan/src/components/ChainInfoHighlights.re
> +          extraComponent={<Text value=moniker code=true />}
Block number different from design?

2020-03-19 10:01 UTC, evilpeach requested changes

2020-03-19 10:01 UTC, evilpeach commented on scan/src/components/TypeID.re
> +    | Landing => style([pointerEvents(`auto)])
```
| Title => style([pointerEvents(`none)])
| Landing
| Subtitle
| Text => style([pointerEvents(`auto)]);
```

2020-03-19 10:01 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +          extraComponent={<Text value=moniker code=true />}
- remove `code=true`
- add `nowrap=true ellipsis=true block=true` for text-overflow is ellipsis
- Test it if the word is long. It will show properly. Example `Validator...`

2020-03-19 10:01 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
>            extraTopRight={<TimeAgos time={info.latestBlock.timestamp} />}
Let's increase font size but you have to shorten like seconds to secs. @sorawit @taobun  Do you have any suggestions.

2020-03-20 14:17 UTC, taobun requested changes

2020-03-20 14:17 UTC, taobun commented on scan/src/components/ChainInfoHighlights.re
> +    // let latestBlock = info.latestBlock.getProposerMoniker;
Remove this line

2020-03-20 14:58 UTC, taobun approved these changes

2020-03-21 09:37 UTC, evilpeach approved these changes
LGTM

2020-03-21 09:41 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
>            extraTopRight={<TimeAgos time={info.latestBlock.timestamp} />}
As I've discussed with them, we just use `seconds` for now.

2020-03-21 09:51 UTC, merged