fix style
bandprotocol/bandchain pull request #894
Opened 2020-03-18 17:14 UTC by prin-r

Fix #815

2020-03-19 00:19 UTC, sorawit commented
Please rename this PR

2020-03-20 03:27 UTC, evilpeach requested changes

2020-03-20 03:27 UTC, evilpeach commented on scan/src/components/ChainInfoHighlights.re
> +    Js.Console.log(validators);
remove log

2020-03-21 06:33 UTC, taobun approved these changes

2020-03-21 09:50 UTC, evilpeach approved these changes

2020-03-21 11:03 UTC, merged