Allow validators to register address to send report transactions - Implement handlers and keepers
bandprotocol/bandchain pull request #909
Opened 2020-03-19 13:42 UTC by Benzbeeb

Fixed #848

2020-03-19 14:19 UTC, sorawit requested changes

2020-03-19 14:19 UTC, sorawit commented on chain/cmd/bandoracled/main.go
> +		zoracle.NewMsgReportData(requestID, reports, sdk.ValAddress(bandClient.Sender()), sdk.AccAddress(bandClient.Sender())),
This the casting necessary?

2020-03-19 14:19 UTC, sorawit commented on chain/x/zoracle/client/cli/tx.go
> +			msg := types.NewMsgReportData(requestID, dataset, sdk.ValAddress(cliCtx.GetFromAddress()), sdk.AccAddress(cliCtx.GetFromAddress()))
ditto

2020-03-19 14:19 UTC, sorawit commented on chain/x/zoracle/handler.go
> +			return handleMsgAddOracleAddress(ctx, keeper, msg)
Where is MsgRemoveOracleAddress?

2020-03-19 14:19 UTC, sorawit commented on chain/x/zoracle/handler.go
> +			sdk.NewAttribute(types.AttributeKeyValidator, msg.Validator.String()),
Add reporter here too

2020-03-19 14:19 UTC, sorawit commented on chain/x/zoracle/handler.go
> +			sdk.NewAttribute(types.AttributeKeyValidator, msg.Validator.String()),
ditto

2020-03-19 15:55 UTC, taobun requested changes

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/types/msgs_test.go
> +		{false, NewMsgReportData(requestID, data, failValidator, reporter)},
Add invalid reporter too

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/alias.go
> +	MsgRemoveOracleAdderess = types.MsgRemoveOracleAdderess
Add NewMsg... in var

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/client/cli/tx.go
> +			msg := types.NewMsgReportData(requestID, dataset, sdk.ValAddress(cliCtx.GetFromAddress()), sdk.AccAddress(cliCtx.GetFromAddress()))
Add // TODO: Receive validator address as flag

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report.go
> +		}
Why we need this code?

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report.go
> +
If found is false, we must return err with validator not in list?

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report.go
> +		}
And if this reporter is not an illegal reporter of the validator.  It should return another error

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report_test.go
> +	}, sdk.ValAddress([]byte("validator2")), sdk.AccAddress([]byte("validator1")))
Why this test passed?

2020-03-19 15:55 UTC, taobun commented on chain/x/zoracle/internal/keeper/report_test.go
> +	}, sdk.ValAddress([]byte("validator2")), sdk.AccAddress([]byte("validator2")))
Add new unit test to test invalid reporter

2020-03-20 04:25 UTC, sorawit requested changes

2020-03-20 04:25 UTC, sorawit commented on chain/x/zoracle/internal/keeper/report.go
> +		if agent.Equals(validValidator) {
Is this correct?

2020-03-20 04:36 UTC, sorawit requested changes

2020-03-20 04:36 UTC, sorawit commented on chain/x/zoracle/internal/keeper/report.go
> +			"AddReport: Reporter (%s) is unauthorized permission to be reporter.",
%s is not an authorized reporter of %s

2020-03-20 04:38 UTC, sorawit requested changes

2020-03-20 04:38 UTC, sorawit commented on chain/x/zoracle/internal/keeper/report.go
> +			"AddReport: Reporter (%s) and (%s) is not on the reporter list.",
Validator (%s) is not on the reporter list.

2020-03-20 06:25 UTC, sorawit approved these changes
Looks good

2020-03-20 08:06 UTC, taobun approved these changes

2020-03-20 08:07 UTC, merged