Design and implement database table for keeping validators uptime
bandprotocol/bandchain pull request #934
Opened 2020-03-20 11:24 UTC by taobun

fixed #844

2020-03-20 12:53 UTC, sorawit requested changes

2020-03-20 12:53 UTC, sorawit commented on chain/db/table.go
> +type ValidatorStatus struct {
Let's call this `Validator`. We will add more things to this table.

2020-03-20 12:53 UTC, sorawit commented on chain/db/validator.go
> +	operatorAddress string,
Let's make this take `sdk.ValAddress` and `Pubkey` types respectively.

2020-03-20 12:53 UTC, sorawit commented on chain/db/metadata.go
> +	return b.SetMetadataValue(KeyUptimeLookBackDuration, fmt.Sprintf("%d", duration))
Why don't we make `SetMetadataValueInt64` for the sake of consistency?

2020-03-22 08:53 UTC, sorawit approved these changes

2020-03-22 09:14 UTC, evilpeach approved these changes

2020-03-22 15:30 UTC, merged