scan: GraphQL apollo + Metadata subscription
bandprotocol/bandchain pull request #960
Opened 2020-03-23 17:25 UTC by evilpeach

Fixes #911 
Fixes #912

2020-03-23 22:47 UTC, sorawit requested changes

2020-03-23 22:47 UTC, sorawit commented on scan/src/subscriptions/MetadataSub.re
> +  lastProcessedHeight: int,
Let's make this `ID.Block.t` so we are safe safe safe!

2020-03-24 02:57 UTC, sorawit requested changes

2020-03-24 02:57 UTC, sorawit commented on scan/src/ApolloClient.re
> +let graphQL = "d3n-debug.bandprotocol.com:5433/v1/graphql";
Please make this configurable. It will be different depending on whether we run on https.

2020-03-24 02:57 UTC, sorawit commented on scan/src/ApolloClient.re
> +// /* Create an HTTP Link */
this looks messy

2020-03-24 03:04 UTC, sorawit requested changes

2020-03-24 03:04 UTC, sorawit commented on scan/src/subscriptions/MetadataSub.re
> +  arr->Belt.Array.keepMap(a => {a##key == field ? Some(a##value) : None})[0];
Remove unnecessary parenthesis

2020-03-24 06:00 UTC, sorawit submitted a review, later dismissed

2020-03-24 06:13 UTC, sorawit approved these changes

2020-03-24 06:18 UTC, taobun approved these changes

2020-03-24 06:27 UTC, merged