Implement and wireup subscribe hook for data sources
bandprotocol/bandchain pull request #979
Opened 2020-03-24 12:27 UTC by taobun

fixed #940

2020-03-24 15:12 UTC, sorawit requested changes

2020-03-24 15:12 UTC, sorawit commented on scan/src/subscriptions/DataSourceRevisionSub.re
> +  height: int,
Shouldn't this be `ID.Block.t`?

2020-03-25 03:49 UTC, sorawit approved these changes
Let's ship it!

2020-03-26 00:41 UTC, sorawit commented
@evilpeach Let's review and merge this.

2020-03-26 03:55 UTC, Benzbeeb approved these changes

2020-03-26 03:56 UTC, merged

2020-03-26 04:02 UTC, prin-r approved these changes