Implement caching layer for transaction
bandprotocol/bandchain pull request #980
Opened 2020-03-24 14:01 UTC by Benzbeeb

Fixed #923

2020-03-24 14:51 UTC, taobun requested changes

2020-03-24 14:51 UTC, taobun commented on chain/db/db.go
> +		"CASCADE",
Please change it back to RESTRICT

2020-03-24 14:51 UTC, taobun commented on chain/db/db.go
> +		b.ctx.BlockGasMeter().GasConsumed(),
This is not gas used. Gasused get from response of DeliverTx

2020-03-24 14:51 UTC, taobun commented on chain/db/db.go
> +		b.ctx.BlockGasMeter().GasConsumedToLimit(),
tx.Fee.Gas

2020-03-24 14:51 UTC, taobun commented on chain/db/db.go
> +		tx.Fee.Gas,
tx.Fee.Amount

2020-03-24 14:51 UTC, taobun commented on chain/db/transaction.go
> +	gasFee uint64,
Receive as sdk.Coins

2020-03-24 14:51 UTC, taobun commented on chain/db/table.go
> +	GasFee      uint64 `gorm:"not null"`
String type

2020-03-25 02:54 UTC, sorawit requested changes

2020-03-25 02:54 UTC, sorawit commented on chain/app/db_app.go
> +			uint64(res.GasUsed),
I don't think we need to do type casting. Just use whaever.

2020-03-25 08:00 UTC, taobun requested changes

2020-03-25 08:00 UTC, taobun commented on chain/db/table.go
> +	GasUse      int64  `gorm:"not null"`
GasUsed

2020-03-25 08:00 UTC, taobun commented on chain/db/transaction.go
> +	gasUse int64,
ditto

2020-03-25 08:03 UTC, taobun approved these changes

2020-03-25 08:07 UTC, sorawit approved these changes

2020-03-25 08:40 UTC, merged