Implement report table caching layer
bandprotocol/bandchain pull request #985
Opened 2020-03-25 10:35 UTC by tansawit

#929

2020-03-25 10:58 UTC, sorawit requested changes

2020-03-25 10:58 UTC, sorawit commented on chain/go.sum
> +github.com/cosmos/cosmos-sdk v0.38.1 h1:DTuxIJeMpB//ydq+ObAjQgsaiwYBZ8T7NDzXjyiL1Kg=
This has no effect on code correctness, but shouldn't be in this change.

2020-03-25 10:58 UTC, sorawit commented on chain/db/table.go
> +	Validator    string `gorm:"primary_key;foreignkey:Report"`
Do we need `foreignkey:Report`? I don't see it being one on other tables.

2020-03-25 10:58 UTC, sorawit commented on chain/db/reports.go
> +}
Please always add trailing endlines.

2020-03-25 10:58 UTC, sorawit commented on chain/db/reports.go
> +	if err != nil {
This check should come right after the error is created. Move it to line 20.

2020-03-25 11:46 UTC, sorawit requested changes

2020-03-25 11:46 UTC, sorawit commented on chain/db/db.go
> +	db.Model(&ReportDetail{}).AddForeignKey(
Remove

2020-03-25 12:21 UTC, sorawit submitted a review, later dismissed

2020-03-25 12:30 UTC, sorawit commented on chain/db/db.go
> +    "validators(consensus_address)",
Fix code format

2020-03-25 12:30 UTC, sorawit commented on chain/db/db.go
> +    "RESTRICT",
also here

2020-03-25 12:30 UTC, sorawit commented on chain/db/db.go
> +
also here

2020-03-25 15:47 UTC, taobun requested changes

2020-03-25 15:47 UTC, taobun commented on chain/db/db.go
> +
Add foreign key to the transaction by txhash

2020-03-26 00:40 UTC, sorawit submitted a review, later dismissed
Looks good.

2020-03-26 03:07 UTC, taobun requested changes

2020-03-26 03:07 UTC, taobun commented on chain/db/db.go
> +		"validators(consensus_address)",
operator_address

2020-03-26 03:19 UTC, taobun approved these changes

2020-03-26 05:07 UTC, sorawit approved these changes

2020-03-26 06:10 UTC, merged