Design and implement message field for tx table
bandprotocol/bandchain pull request #986
Opened 2020-03-25 12:10 UTC by Benzbeeb

2020-03-25 12:19 UTC, sorawit requested changes

2020-03-25 12:19 UTC, sorawit commented on chain/db/db.go
> +		jsonMap["dataSourceId"] = events["edit_data_source.id"]
Don't type out event name directly. Use the names defined in `zoracle` module.

2020-03-25 12:19 UTC, sorawit commented on chain/db/db.go
> +		return fmt.Sprint(string(jsonString)), nil
Let's return this after the switch? This is crazy repetition.

2020-03-26 12:36 UTC, taobun requested changes

2020-03-26 12:36 UTC, taobun commented on chain/app/db_app.go
> +		messages := app.dbBand.HandleTransaction(stdTx, txHash, logs)
Please make it into 2 step
1. Create transaction without message.
Handle transaction
2. Update msgs to transaction later

2020-03-26 12:36 UTC, taobun commented on chain/db/db.go
> +		jsonMap["requestID"] = events[zoracle.EventTypeRequest+"."+zoracle.AttributeKeyID]
We need oraclescriptName

2020-03-26 12:36 UTC, taobun commented on chain/db/db.go
> +	case zoracle.MsgAddOracleAddress:
ValidatorMoniker

2020-03-26 12:36 UTC, taobun commented on chain/db/db.go
> +	case zoracle.MsgRemoveOracleAdderess:
ValidatorMoniker

2020-03-26 16:21 UTC, taobun requested changes

2020-03-26 16:21 UTC, taobun commented on chain/app/db_app.go
> +		app.dbBand.UpdateTransaction(
Why this code doesn't be in HandleTransaction?

2020-03-27 02:42 UTC, taobun requested changes

2020-03-27 02:42 UTC, taobun commented on chain/db/db.go
> +	case zoracle.MsgRemoveOracleAdderess:
Rebase master?

2020-03-27 05:20 UTC, taobun submitted a review, later dismissed

2020-03-27 06:28 UTC, sorawit requested changes

2020-03-27 06:28 UTC, sorawit commented on chain/app/db_app.go
> +			make([]map[string]interface{}, 0),
Can we put nil?

2020-03-27 06:28 UTC, sorawit commented on chain/db/db.go
> +	b.UpdateTransaction(
nit: I think this can be one line.

2020-03-27 06:28 UTC, sorawit commented on chain/db/db.go
>  	// Just proof of concept
Let's remove this comment.

2020-03-27 06:28 UTC, sorawit commented on chain/db/transaction.go
> +	messages []map[string]interface{},
Why do we take this parameter if we are always passing nil?

2020-03-27 06:28 UTC, sorawit requested changes

2020-03-27 06:28 UTC, sorawit commented on chain/db/table.go
> +	Messages    json.RawMessage `sql:"json"`
Does it need to be not null?

2020-03-27 07:56 UTC, taobun approved these changes

2020-03-27 08:21 UTC, sorawit approved these changes

2020-03-27 08:24 UTC, merged