Design and implement borsh decode function
bandprotocol/bandchain pull request #987
Opened 2020-03-25 15:32 UTC by taobun

fixed #932

2020-03-25 15:53 UTC, sorawit requested changes

2020-03-25 15:53 UTC, sorawit commented on scan/src/bindings/Borsh.re
> +// Test by this test
Instead of having this as comment, let's create an actual test file.

2020-03-26 11:14 UTC, sorawit approved these changes

2020-03-26 11:14 UTC, sorawit requested changes

2020-03-26 11:14 UTC, sorawit commented on scan/src/bindings/Borsh.re
> +    let new_value = borsh.deserialize(schemaMap, model, data)
camelcase?

2020-03-26 17:31 UTC, sorawit approved these changes

2020-03-28 07:04 UTC, evilpeach approved these changes
LGTM

2020-03-28 13:18 UTC, merged