Implement request index page ui top part
bandprotocol/bandchain pull request #988
Opened 2020-03-25 16:25 UTC by prin-r

Fix #858

2020-03-26 02:24 UTC, sorawit commented
Please fix the conflict now that I landed #990

2020-03-26 07:52 UTC, taobun requested changes

2020-03-26 07:52 UTC, taobun commented on scan/src/rpc/RequestHook.re
> +      resolveStatus: Unknown, // TODO , fix this Mock
Why this line need to change?

2020-03-27 02:36 UTC, taobun requested changes

2020-03-27 02:36 UTC, taobun commented on scan/src/rpc/RequestHook.re
>        resolveStatus: json |> field("resolveStatus", intstr) |> getResolveStatus,
resolveStatus: json |> field("resolveStatus", int) |> getResolveStatus,

2020-03-27 07:30 UTC, evilpeach requested changes

2020-03-27 07:30 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +               prefix="Last updated "
remove this prefix

2020-03-27 07:30 UTC, evilpeach commented on scan/src/reusable/InfoHL.re
> +     | TxHash(txHash, width) => <TxLink txHash width />
font size should be 14px

2020-03-27 07:30 UTC, evilpeach commented on scan/src/reusable/InfoHL.re
> +                <ValidatorMonikerLink validator size=Text.Lg weight=Text.Medium underline=true />
remove `weight=Text.Medium`, use the default value

2020-03-27 07:30 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +             />
Please set `spacing=Text.Em(0.03)` of header in InfoHL.

2020-03-27 08:12 UTC, evilpeach requested changes

2020-03-27 08:12 UTC, evilpeach commented on scan/src/pages/RequestIndexPage.re
> +  let pageContainer = style([paddingTop(`px(40))]);
PaddingTop is too wide. Let's squeeze them to 20px

2020-03-27 08:22 UTC, evilpeach approved these changes
LGTM

2020-03-27 08:27 UTC, taobun approved these changes

2020-03-27 08:40 UTC, merged